(() => {
'use strict';
const $ = (s, el = document) => el.querySelector(s);
const $$ = (s, el = document) => [...el.querySelectorAll(s)];
const page = document.body.dataset.page;
const paths = {
 design:'M4 19h16M5 15 15 5l4 4L9 19H5v-4Zm8-8 4 4M5 5h4M5 8V4',
 home:'m3 10 9-7 9 7M5 9v11h5v-6h4v6h5V9',
 file:'M6 3h8l4 4v14H6V3Zm8 0v5h4',
 folder:'M3 7h7l2 2h9v11H3V7Zm0 0V5h7l2 2',
 'folder-plus':'M3 7h7l2 2h9v11H3V7Zm9 5v5m-3-2h6',
 space:'m3 5 6-2 6 3 6-2v16l-6 2-6-3-6 2V5Zm6-2v16m6-13v16',
 issue:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM8 12l3 3 5-6',
 review:'M8 5H5v16h14V5h-3M9 3h6v5H9V3Zm-1 10 2 2 5-5m-7 8h8',
 share:'M8 12 17 6M8 12l9 6M8 12a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0Zm13-7a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0Zm0 14a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0Z',
 send:'m3 4 18 8-18 8 4-8-4-8Zm4 8h14',
 users:'M14 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM4 21v-4a5 5 0 0 1 10 0v4M17 4a3 3 0 0 1 0 6m0 4a4 4 0 0 1 4 4v3',
 bridge:'M3 7h16m-4-4 4 4-4 4M21 17H5m4-4-4 4 4 4',
 settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1 1-3Z',
 search:'M16 10a6 6 0 1 1-12 0 6 6 0 0 1 12 0Zm-2 4 6 6',
 clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM12 7v6l4 2',
 bell:'M5 17h14l-2-3V9a5 5 0 0 0-10 0v5l-2 3Zm5 3h4M12 2v2',
 help:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0ZM9 8a3 3 0 0 1 6 1c0 2-3 2-3 5m0 3v.5',
 upload:'M7 17H6a4 4 0 0 1-1-8 7 7 0 0 1 14-1 4.5 4.5 0 0 1 0 9h-2M12 21V11m-4 4 4-4 4 4',
 panel:'M3 4h18v16H3V4Zm12 0v16',
 layers:'m12 3 10 5-10 5L2 8l10-5ZM2 12l10 5 10-5M2 16l10 5 10-5',
 camera:'M3 7h5l2-3h4l2 3h5v13H3V7Zm13 6a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z',
 building:'M4 21V3h11v18M15 8h5v13M8 7h3M8 11h3M8 15h3M2 21h20',
 trash:'M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7',
 arrow:'m9 5 7 7-7 7',
 check:'m5 12 4 4L19 6'
};
function icon(key){return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[key] || paths.file}"/></svg>`;}
function hydrate(el=document){$$('[data-icon]',el).forEach(n=>{n.innerHTML=icon(n.dataset.icon);n.removeAttribute('data-icon');});}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
let toastTimer;
function notify(text){const t=$('#toast');t.textContent=text;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2600);}
const navItems=[['files','file','成果资料库','file-management.html'],['space','space','空间场景','gis.html'],['issues','issue','问题','workflows.html#issues'],['reviews','review','审阅','workflows.html#reviews'],['transmittals','send','资料分发','workflows.html#transmittals']];
function navLink(n){return `<a href="${n[3]}" data-nav="${n[0]}" title="${n[2]}">${icon(n[1])}<span class="nav-text">${n[2]}</span>${n[4]?`<span class="nav-count">${n[4]}</span>`:''}</a>`;}
$('#cdeNav').innerHTML=`<div class="nav-caption">项目数据与协作</div>${navItems.map(navLink).join('')}<div class="nav-group">${navLink(['activity','clock','活动记录','workflows.html#activity'])}</div><div class="nav-bottom">${[['members','users','成员与权限'],['bridge','bridge','跨项目桥接'],['settings','settings','项目设置']].map(n=>navLink([...n,`workflows.html#${n[0]}`])).join('')}</div><div class="nav-footer"><span>全生命周期数字底座</span><span>v0.2</span></div>`;
if(page==='design-modeling')$('#cdeNav').innerHTML='<div class="nav-caption">建模工作台</div>'+navLink(['modeling','layers','道路接入与建模','road-modeling.html'])+'<div class="nav-group"><div class="nav-caption">共享资料入口</div>'+navLink(['library','file','成果资料库 ↗','file-management.html'])+'</div><div class="nav-bottom"><div class="nav-footer">数据接入 · 三维建模</div></div>';
const stages=[['道路接入与建模','layers','路线数据 · 专业配置 · 三维成果'],['设计期','design','成果管理 · 专业协同'],['施工期','building','施工交付 · 现场协作'],['运营期','settings','资产移交 · 运营维护']];
let stage=page==='operations'?'运营期':page==='construction'?'施工期':page==='design-modeling'?'道路接入与建模':'设计期';
$('#cdeHeader').innerHTML=`<div class="app-switcher"><button class="app-switch" id="appSwitch" aria-haspopup="true" aria-expanded="false"><span class="app-glyph">${icon(page==='operations'?'settings':page==='construction'?'building':page==='design-modeling'?'layers':'design')}</span><span id="stageName">${esc(stage)}</span><span class="down">⌄</span></button><div class="switch-menu" id="switchMenu" hidden><h3>切换项目应用</h3>${stages.map((s,i)=>`<button class="switch-option ${s[0]===stage?'selected':''}" data-stage="${s[0]}"><span class="app-glyph">${icon(s[1])}</span><span><strong>${s[0]}</strong><small>${s[2]}</small></span><span class="tick">${s[0]===stage?'✓':''}</span></button>`).join('')}<div class="switch-foot">同一项目 · 应用切换不代表数据移交</div></div></div><button class="project-picker" data-action="project"><span class="project-square">${icon('building')}</span>XX高速公路 <span class="down">⌄</span></button><span class="header-spacer"></span><div class="platform-wordmark">全生命周期数字底座<small>COMMON DATA ENVIRONMENT</small></div><div class="header-tools"><button class="quiet-button" data-action="help" aria-label="帮助">${icon('help')}</button><button class="quiet-button" data-action="notifications" aria-label="通知">${icon('bell')}</button><button class="user-avatar" data-action="profile" aria-label="当前用户张工">ZG</button></div>`;
function activeNav(key){$$('[data-nav]').forEach(a=>{a.classList.toggle('active',a.dataset.nav===key);if(a.dataset.nav===key)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});}
activeNav(page);
$('#appSwitch').onclick=()=>{const open=$('#switchMenu').hidden;$('#switchMenu').hidden=!open;$('#appSwitch').setAttribute('aria-expanded',String(open));};
$$('[data-stage]').forEach(b=>b.onclick=()=>{stage=b.dataset.stage;if(stage==='道路接入与建模'&&page!=='design-modeling'){location.href='road-modeling.html';return;}if(stage==='运营期'&&page!=='operations'){location.href=window.LC?LC.stageHref(stage):'operations.html#twin';return;}if(stage==='施工期'&&page!=='construction'){location.href=window.LC?LC.stageHref(stage):'construction.html#home';return;}if(stage==='设计期'&&['operations','construction','design-modeling'].includes(page)){location.href='file-management.html';return;}$('#stageName').textContent=stage;try{sessionStorage.setItem('cde-stage',stage);}catch{}$$('[data-stage]').forEach(n=>{n.classList.toggle('selected',n===b);$('.tick',n).textContent=n===b?'✓':'';});$('#switchMenu').hidden=true;$('#appSwitch').setAttribute('aria-expanded','false');notify(`已切换至${stage}应用展示，共享同一示例项目`);});
document.addEventListener('click',e=>{if(!e.target.closest('.app-switcher')){$('#switchMenu').hidden=true;$('#appSwitch').setAttribute('aria-expanded','false');}});
function selected(){if(window.DESIGN?.selected())return window.DESIGN.selected();if(page==='files' && typeof activeItem!=='undefined' && activeItem)return {name:activeItem.name,code:activeItem.code,version:activeItem.version,person:activeItem.uploader,date:activeItem.updated};if(page==='space' && typeof results!=='undefined'){const r=results[selectedResult];return {name:r.fileName,code:r.code,version:r.version,person:r.uploader,date:r.uploaded};}return {name:'桥梁设计模型',code:'DES-BR-001',version:'V3',person:'李工',date:'2025-05-21 14:18'};}
function dialog(title,body,primary='确认',onConfirm=()=>notify('界面演示，未保存或发送数据')){
 const old=$('#cdeDialog');if(old)old.remove();const d=document.createElement('dialog');d.id='cdeDialog';d.className='cde-dialog';
 d.innerHTML=`<header><h2>${title}</h2><button class="quiet-button" data-close aria-label="关闭">×</button></header><div class="dialog-content">${body}</div><footer><small>仅作界面演示</small><button class="text-button" data-close>取消</button>${primary?`<button class="cde-primary" id="dialogConfirm">${primary}</button>`:''}</footer>`;
 document.body.append(d);d.showModal();$$('[data-close]',d).forEach(b=>b.onclick=()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});if(primary)$('#dialogConfirm',d).onclick=()=>{onConfirm(d);d.close();};return d;
}
function fileCard(f=selected()){return `<div class="dialog-file">${icon('file')}<span>${esc(f.name)}</span><span class="version-pill">${esc(f.version)}</span></div>`;}
function shareDialog(){const d=dialog('资料分发',`<h3>分发文件</h3>${fileCard()}<p>按当前版本创建分发快照，供接收方查阅并确认。</p><h3>共享给</h3><label class="radio-row"><input name="recipient" type="radio" checked>项目成员</label><label class="radio-row"><input name="recipient" type="radio">外部参与单位</label><label class="radio-row"><input name="recipient" type="radio">其他项目</label><div class="dialog-tabs"><button class="active" data-sharetab="email">成员分发</button><button data-sharetab="link">共享链接</button></div><div id="shareEmail"><label class="field">接收人 / 单位<select><option>王工 · 总体设计组</option><option>赵工 · 桥梁设计组</option><option>XX高速建设管理处</option></select></label></div><div id="shareLink" hidden><label class="field">链接有效期<select><option>7 天</option><option>30 天</option></select></label><p>链接将在正式分发后生成。</p></div><label class="field">分发说明<textarea placeholder="请输入本次分发用途与接收要求">请查收桥梁设计成果，供桥梁专业设计使用。</textarea></label>`,'预览分发单',()=>{location.href='workflows.html#transmittals';});$$('[data-sharetab]',d).forEach(b=>b.onclick=()=>{$$('[data-sharetab]',d).forEach(n=>n.classList.toggle('active',n===b));$('#shareEmail').hidden=b.dataset.sharetab!=='email';$('#shareLink').hidden=b.dataset.sharetab!=='link';});}
function reviewDialog(){dialog('发起审阅',`${fileCard()}<label class="field">审阅名称<input value="桥梁设计成果专业审阅"></label><label class="field">审阅工作流<select><option>专业校审 · 两级审批</option><option>项目负责人 · 一级审批</option></select></label><div class="review-flow"><div>提交人<small>李工</small></div>›<div>专业校核<small>王工</small></div>›<div>负责人审核<small>张工</small></div></div><label class="field">截止日期<input type="date" value="2026-09-18"></label>`,'查看审阅示例',()=>location.href='workflows.html#reviews');}
function issueDialog(){dialog('创建问题',`<label class="field">问题标题<input placeholder="描述需要协调或解决的问题" value="桥位控制点坐标复核"></label><label class="field">问题类型<select><option>设计协调</option><option>数据质量</option><option>成果完整性</option></select></label><label class="field">责任人<select><option>李工 · 测量专业</option><option>赵工 · 桥梁专业</option></select></label><label class="field">关联文件</label>${fileCard()}<label class="field">问题描述<textarea>请复核桥位控制点坐标与最新设计成果的一致性，并补充校核记录。</textarea></label>`,'查看问题示例',()=>location.href='workflows.html#issues');}
function historyMarkup(kind,f=selected()){
 if(kind==='history'){const count=Math.max(1,parseInt(f.version.slice(1))||1);return `<h3 style="font-size:14px;font-weight:500">版本历史记录</h3><ul class="history-list">${Array.from({length:count},(_,i)=>count-i).map((v,i)=>`<li><span class="version-pill">V${v}</span><div><h4>${esc(f.name)} ${i===0?'<span class="tag final">当前版本</span>':''}</h4><p>${esc(f.person)} · ${i===0?esc(f.date):'历史上传时间（示例）'}<br>${i===0?'当前成果版本':'修订前存档 · 可追溯查看'}</p></div></li>`).join('')}</ul><div class="section-note">版本记录为界面示例，文件样例信息沿用原有数据。</div>`;}
 return `<h3 style="font-size:14px;font-weight:500">${kind==='upload'?'上传记录':'操作记录'}</h3><ul class="history-list">${(kind==='upload'?[[`上传 ${esc(f.version)} 版本`,`${esc(f.person)} · ${esc(f.date)}`],['文件校验完成','文件编码与目录信息已核对']]:[['查看文件','张工 · 本次浏览'],['更新文件属性',`${esc(f.person)} · ${esc(f.date)}`],['关联空间位置','关联至对应工点']]).map(a=>`<li><span class="activity-dot"></span><div><h4>${a[0]}</h4><p>${a[1]}</p></div></li>`).join('')}</ul><div class="section-note">活动时间线为演示记录。</div>`;
}
function setupExisting(){if(!['files','space'].includes(page))return;
 const layout=page==='files'?$('.file-layout'):$('.gis-window');
 $$('.tree-row .folder').forEach(n=>n.innerHTML=icon('folder'));
 if(page==='space'){ const originalSelect=selectResult; selectResult=(id)=>{originalSelect(id);layout.classList.add('details-open');}; }
 const originalRender=page==='files'?renderDetail:renderResult;
 const render=()=>{originalRender();const container=page==='files'?$('#detailContent'):$('#objectDetails');if(['history','upload','operations'].includes(activeTab) && (page!=='files'||activeItem))container.innerHTML=historyMarkup(activeTab);if(page==='space')$('.detail-top strong',layout).textContent='关联成果详情';};
 if(page==='files')renderDetail=render;else renderResult=render;
 if(page==='files'){
  const originalRows=renderRows;renderRows=()=>{originalRows();$$('#fileRows tr').forEach(tr=>{const tds=tr.children;if(!tr.classList.contains('folder-row')){const name=tds[2].textContent;tds[2].innerHTML=`<span class="file-type-mark">${name.includes('表')?'XLS':'DWG'}</span>${esc(name)}`;tds[5].innerHTML=`<span class="version-pill">${esc(tds[5].textContent)}</span>`;tds[0].innerHTML='<input type="checkbox" aria-label="选择此文件">';}tr.addEventListener('click',e=>{if(!tr.classList.contains('folder-row'))layout.classList.add('details-open');});});$('#selectAllFiles').checked=false;applyFileSearch();};
  const applyFileSearch=()=>{const term=$('#fileSearch').value.trim().toLowerCase();let visible=0;$$('#fileRows tr').forEach(r=>{r.hidden=!!term&&!r.textContent.toLowerCase().includes(term);if(!r.hidden)visible++;});$('#footerCount').textContent=`共 ${visible} 项`;};
  $('#fileSearch').addEventListener('input',applyFileSearch);$('#selectAllFiles').onchange=e=>$$('#fileRows tr:not([hidden]) input').forEach(c=>c.checked=e.target.checked);
  $('#fileRows').addEventListener('click',e=>{if(e.target.matches('input[type=checkbox]'))e.stopPropagation();},true);
  const treeSearch=$('.tree-search input');treeSearch.setAttribute('aria-label','搜索目录名称');treeSearch.addEventListener('input',()=>{const term=treeSearch.value.trim();$$('#directoryTree .tree-row').forEach(r=>{r.hidden=!!term&&!r.textContent.includes(term);});if(term)$$('#directoryTree details').forEach(d=>d.open=true);});
  renderRows();
 }
 render();
 $$('.detail-tabs button').forEach(b=>b.addEventListener('click',()=>{layout.classList.add('details-open');}));
 $$('[data-scope]').forEach(b=>b.onclick=()=>{const key=b.dataset.scope;$$('[data-scope]').forEach(n=>n.classList.toggle('active',n===b));$('.surface-replacement')?.remove();if(key==='main')return;
  if(page==='space'){actions[key==='recent'?'viewpoints':'layers']();$$('[data-scope]').forEach(n=>n.classList.toggle('active',n.dataset.scope==='main'));return;}
  const s=document.createElement('div');s.className='surface-replacement';
  if(key==='deleted')s.innerHTML=`<div class="empty-state">${icon('trash')}<h2>没有已删除的文件</h2><p>删除的文件将显示在这里，供项目管理员恢复。</p></div>`;
  else{s.innerHTML='<h3>最近浏览</h3>'+Object.entries(directories).flatMap(([k,v])=>v.items.filter(i=>i.type==='file').slice(0,1).map(i=>`<button class="recent-file" data-recent="${k}">${icon('file')}${esc(i.name)}<small>${esc(i.version)} · ${esc(i.updated)}</small></button>`)).slice(0,6).join('');$$('[data-recent]',s).forEach(n=>n.onclick=()=>{openDirectory(n.dataset.recent);s.remove();$$('[data-scope]').forEach(n=>n.classList.toggle('active',n.dataset.scope==='main'));});}
  $('.cde-workspace').append(s);
 });
 // Replace the original image-only modal with an offline document viewer.
 const m=page==='files'?$('#previewModal'):$('#gisFilePreview');
 const initialTitle=$('h2',m).innerHTML;const footer=$('footer span',m).textContent;
 $('.modal',m).className='modal preview-shell';$('.modal',m).innerHTML=`<header><div><span>文件查看器</span><h2>${initialTitle}</h2></div><div style="display:flex;gap:16px"><button class="text-button" data-action="share">${icon('share')}分发</button><button class="modal-close" aria-label="关闭文件预览">×</button></div></header><div class="preview-body"><aside class="preview-layers"><h3>图层</h3>${['0','C-ANNO-TEXT','C-ROAD','C-TOPO-FEAT','C-TOPO-MAJOR','C-TOPO-MINOR'].map(t=>`<label><input type="checkbox" checked>${t}</label>`).join('')}<p class="section-note">图层及批注工具展示</p></aside><div class="preview-canvas"><img src="assets/file-preview.svg" alt="工程成果图纸示例"><button class="issue-pin" data-action="issue" aria-label="查看关联问题 D-ISS-001">1</button><div class="markup-toolbar"><button class="active" aria-label="选择" data-viewtool="select">↖</button><button aria-label="批注" data-viewtool="markup">✎</button><button aria-label="添加文本" data-viewtool="text">T</button><button aria-label="签章" data-viewtool="stamp">${icon('review')}</button><button aria-label="创建问题" data-action="issue">${icon('issue')}</button><button aria-label="截图" data-viewtool="camera">${icon('camera')}</button></div><div class="viewer-bottom"><button data-viewtool="pan" aria-label="平移">✥</button><button data-viewtool="out" aria-label="缩小">−</button><button data-viewtool="reset">100%</button><button data-viewtool="in" aria-label="放大">＋</button><button data-viewtool="layers" aria-label="切换图层面板">${icon('layers')}</button></div></div></div><footer><span>${footer}</span><span>图纸、图层与批注均为演示</span></footer>`;
 $('.modal-close',m).onclick=()=>{m.classList.remove('open');m.setAttribute('aria-hidden','true');};let zoom=1;
 $$('[data-viewtool]',m).forEach(b=>b.onclick=()=>{const t=b.dataset.viewtool;const img=$('.preview-canvas>img',m);if(['in','out','reset'].includes(t)){zoom=t==='reset'?1:Math.max(.5,Math.min(2,zoom+(t==='in'?.1:-.1)));img.style.transform=`scale(${zoom})`;$('[data-viewtool=reset]',m).textContent=`${Math.round(zoom*100)}%`;}else if(t==='layers')$('.preview-layers',m).hidden=!$('.preview-layers',m).hidden;else if(t==='stamp'){if(!$('.stamp',m))$('.preview-canvas',m).insertAdjacentHTML('beforeend','<div class="stamp">已审阅 · 示例</div>');}else{notify('已选择'+b.getAttribute('aria-label')+'工具（界面演示）');$$('.markup-toolbar button',m).forEach(n=>n.classList.toggle('active',n===b));}});
 $$('input',m).forEach(c=>c.onchange=()=>notify(`${c.parentElement.textContent} 图层${c.checked?'显示':'隐藏'}（示意图不变）`));
}
const issues=[
 ['D-ISS-001','桥位控制点坐标复核','桥梁工点 K12+350','处理中','blue','设计协调','李工','2026-09-14'],
 ['D-ISS-002','横断面测量范围补充','道路标准横断面设计图','待处理','amber','成果完整性','张工','2026-09-15'],
 ['D-ISS-003','管线埋深数据与成果图核对','隧道设计成果图','待处理','amber','数据质量','赵工','2026-09-16'],
 ['D-ISS-004','隧道洞口地形图版本确认','隧道工点 K14+000','待复核','blue','版本协调','王工','2026-09-16'],
 ['D-ISS-005','控制点点之记附件补齐','桥梁设计参数','已关闭','green','成果完整性','赵工','2026-09-09'],
 ['D-ISS-006','路线中桩设计成果单位统一','路线设计参数表','已关闭','green','数据质量','李工','2026-09-08']
];
const reviews=[['REV-004','桥梁设计成果专业审阅','专业校审 · 两级审批','审阅中','blue','3 个文件','王工','2026-09-15'],['REV-003','隧道设计成果审阅','专业校审 · 两级审批','待审阅','amber','2 个文件','赵工','2026-09-16'],['REV-002','道路设计成果阶段审查','项目负责人 · 一级审批','已批准','green','6 个文件','张工','2026-09-09'],['REV-001','道路设计说明初稿审查','专业校审 · 两级审批','退回修改','red','5 个文件','李工','2026-09-08']];
const transmittals=[['TR-004','桥梁专业桥梁设计成果提资','用途：专业设计输入','待确认','amber','3 个文件','桥梁设计组','2026-09-11'],['TR-003','道路设计模型阶段成果分发','用途：路线方案设计','已送达','blue','6 个文件','路线设计组','2026-09-10'],['TR-002','桥梁设计参数正式移交','用途：施工测量准备','已确认','green','2 个文件','XX高速建设管理处','2026-09-09'],['TR-001','道路设计说明归档分发','用途：阶段成果归档','已确认','green','5 个文件','项目档案管理组','2026-09-08']];
const configs={issues:{title:'问题',sub:'跟踪问题、分派责任，并关联项目文件与空间位置',tab:'所有问题',action:'创建问题',type:'issue',columns:['编号','问题标题','状态','类型','责任人','截止日期'],data:issues},reviews:{title:'审阅',sub:'通过统一的审阅流程，确认成果版本与审批状态',tab:'所有审阅',action:'发起审阅',type:'review',columns:['编号','审阅名称','状态','文件数量','当前审阅人','截止日期'],data:reviews},transmittals:{title:'资料分发',sub:'受控分发指定版本的成果，保留接收与确认记录',tab:'所有分发',action:'创建分发',type:'share',columns:['编号','分发名称','状态','包含文件','接收方','分发日期'],data:transmittals}};
function status(r){return `<span class="status-chip ${r[4]}">${r[3]}</span>`;}
function head(title,sub){return `<div class="page-top"><div><h1>${title}</h1><p>${sub}</p></div><div class="page-top-actions"><span class="demo-label">演示项目</span><button class="quiet-button" data-action="help">${icon('help')}帮助</button></div></div>`;}
let currentWorkflow='issues';
function renderWorkflow(){const key=location.hash.slice(1)||'issues';currentWorkflow=key;activeNav(key);const host=$('#workflowContent');document.title=`${configs[key]?.title||'项目协作'}｜数字底座`;$('.record-drawer')?.remove();
 if(configs[key]){const c=configs[key];host.innerHTML=head(c.title,c.sub)+`<div class="workspace-tabs"><button class="active" data-wtab="all">${c.tab} (${c.data.length})</button><button data-wtab="mine">${key==='issues'?'分派给我的':key==='reviews'?'待我审阅':'待确认'}</button><span class="workspace-tabs-note">项目协作 <span>/</span> ${key==='issues'?'Issues':key==='reviews'?'Reviews':'Transmittals'}</span></div><div class="workflow-tools"><button class="cde-primary" data-action="${c.type}">＋ ${c.action}</button><span class="toolbar-divider"></span><select class="filter-select" id="statusFilter" aria-label="按状态筛选"><option value="">所有状态</option>${[...new Set(c.data.map(r=>r[3]))].map(t=>`<option>${t}</option>`).join('')}</select><span class="toolbar-spacer"></span><label class="local-search">${icon('search')}<input id="workflowSearch" placeholder="搜索编号或名称" aria-label="搜索编号或名称"></label><button class="text-button" data-action="export">导出 ↓</button></div><div class="workflow-table-wrap"><table class="workflow-table"><thead><tr>${c.columns.map(t=>`<th>${t}</th>`).join('')}</tr></thead><tbody id="workflowRows"></tbody></table><div id="workflowEmpty" class="empty-state" hidden><h2>没有符合条件的记录</h2><p>请调整搜索内容或状态筛选。</p></div></div>${key==='transmittals'?'<div class="workflow-hint">受控分发以指定文件版本形成快照，后续上传新版本不会改变已分发记录。</div>':''}<footer class="workflow-footer"><span id="workflowCount"></span><span>‹　 <button>1</button>　›</span><span>示例数据</span></footer>`;
 let mine=false;function rows(){const q=$('#workflowSearch').value.trim().toLowerCase(),filter=$('#statusFilter').value;const data=c.data.filter(r=>(!filter||r[3]===filter)&&(!q||r.join(' ').toLowerCase().includes(q))&&(!mine||(key==='issues'?r[6]==='张工':key==='reviews'?r[6]==='张工'&&['审阅中','待审阅'].includes(r[3]):r[3]==='待确认')));$('#workflowRows').innerHTML=data.map(r=>`<tr data-record="${r[0]}" tabindex="0"><td class="record-id">${r[0]}</td><td><strong>${r[1]}</strong><small>${r[2]}</small></td><td>${status(r)}</td><td>${r[5]}</td><td>${r[6]}</td><td>${r[7]}</td></tr>`).join('');$('#workflowCount').textContent=`共 ${data.length} 项`;$('#workflowEmpty').hidden=data.length>0;$$('[data-record]').forEach(tr=>{const open=()=>recordDrawer(c.data.find(r=>r[0]===tr.dataset.record),key);tr.onclick=open;tr.onkeydown=e=>{if(e.key==='Enter')open();};});}
 $('#workflowSearch').oninput=rows;$('#statusFilter').onchange=rows;$$('[data-wtab]').forEach(b=>b.onclick=()=>{mine=b.dataset.wtab==='mine';$$('[data-wtab]').forEach(n=>n.classList.toggle('active',n===b));rows();});rows();return;
 }
 if(key==='activity'){host.innerHTML=head('活动记录','查看项目文件、审阅和分发过程中的操作记录')+'<div class="workspace-tabs"><button class="active">全部活动</button><span class="workspace-tabs-note">项目活动 / 示例记录</span></div><div class="workflow-tools"><span class="demo-label">最近 7 天</span><span class="toolbar-spacer"></span><button class="text-button" data-action="export">导出 ↓</button></div><div class="workflow-table-wrap"><table class="workflow-table"><thead><tr><th>操作人</th><th>活动内容</th><th>类型</th><th>关联记录</th><th>时间</th></tr></thead><tbody>'+[['李工','上传桥梁设计模型 V3','版本更新','DES-BR-001','09-11 09:42'],['张工','创建桥梁专业桥梁设计成果提资','资料分发','TR-004','09-11 09:30'],['王工','开始桥梁设计成果专业审阅','审阅','REV-004','09-10 16:20'],['赵工','关闭控制点点之记附件问题','问题','D-ISS-005','09-09 14:18'],['张工','批准道路设计成果阶段审查','审阅','REV-002','09-09 11:06']].map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')+'</tbody></table></div><footer class="workflow-footer"><span>共 5 条活动</span><span>示例记录 · 非真实操作日志</span></footer>';return;}
 if(key==='members'){host.innerHTML=head('成员与权限','按参与单位与项目角色管理成果访问范围')+'<div class="workspace-tabs"><button class="active">项目成员</button></div><div class="workflow-tools"><button class="cde-primary" data-action="invite">＋ 邀请成员</button><span class="toolbar-spacer"></span><span class="demo-label">4 位示例成员</span></div><div class="workflow-table-wrap"><table class="workflow-table"><thead><tr><th>成员</th><th>单位 / 团队</th><th>角色</th><th>文件权限</th><th>状态</th></tr></thead><tbody>'+[['张工','总体设计组','项目管理员','查看 / 编辑 / 审批'],['李工','测量专业组','专业工程师','查看 / 上传 / 编辑'],['王工','总体设计组','专业审阅人','查看 / 批注 / 审阅'],['赵工','桥梁设计组','专业工程师','查看 / 上传']].map(r=>`<tr>${r.map((x,i)=>`<td>${i===0?`<strong class="member-name">${x}</strong>`:x}</td>`).join('')}<td><span class="status-chip green">已加入</span></td></tr>`).join('')+'</tbody></table></div>';return;}
 if(key==='bridge'){host.innerHTML=head('跨项目桥接','将批准的成果与关联项目共享，保留来源和版本信息')+'<div class="workspace-tabs"><button class="active">已桥接项目</button></div><div class="workflow-tools"><button class="cde-primary" data-action="bridge">＋ 创建桥接</button><span class="toolbar-spacer"></span><span class="demo-label">桥接关系展示</span></div><div class="workflow-table-wrap"><table class="workflow-table"><thead><tr><th>方向</th><th>关联项目</th><th>共享内容</th><th>版本策略</th><th>状态</th></tr></thead><tbody><tr><td class="record-id">发出 →</td><td><strong>外部施工协作项目</strong><small>另一项目的文件共享示例</small></td><td>已批准的设计成果</td><td>指定版本快照</td><td><span class="status-chip green">已建立</span></td></tr><tr><td class="record-id">接收 ←</td><td><strong>外部勘测协作项目</strong><small>外部勘测基础资料</small></td><td>勘测资料与路线边界</td><td>接收后确认</td><td><span class="status-chip blue">待确认</span></td></tr></tbody></table></div><div class="workflow-hint">Bridge 用于跨项目共享；同一项目的阶段切换无需创建桥接。当前演示未连接外部项目。</div>';return;}
 if(key==='settings'){host.innerHTML=head('项目设置','项目基础信息、成果标准与公共数据环境配置')+'<div class="workspace-tabs"><button class="active">常规</button></div><div class="settings-grid"><section class="settings-card"><h3>项目基础信息</h3>'+[['项目名称','XX高速公路'],['项目类型','公路工程'],['当前阶段','设计期'],['坐标系统','CGCS2000'],['项目管理员','张工']].map(r=>`<div class="settings-row"><span>${r[0]}</span><strong>${r[1]}</strong></div>`).join('')+'</section><section class="settings-card"><h3>成果管理规则</h3>'+[['版本控制','保留历史版本'],['文件编码','沿用项目编码体系'],['成果分类','中间成果 / 最终成果'],['正式分发','指定版本快照'],['操作记录','按文件与流程追溯']].map(r=>`<div class="settings-row"><span>${r[0]}</span><strong>${r[1]}</strong></div>`).join('')+'<p>配置内容仅用于展示项目公共数据环境的管理方式。</p></section></div>';return;}
 location.hash='issues';
}
function recordDrawer(r,key){$('.record-drawer')?.remove();const d=document.createElement('aside');d.className='record-drawer';d.innerHTML=`<div class="detail-top"><strong>${key==='issues'?'问题详情':key==='reviews'?'审阅详情':'分发详情'} · ${r[0]}</strong><button class="quiet-button" data-action="close-record" aria-label="关闭详情">×</button></div><div class="detail-record">${status(r)}<h2>${r[1]}</h2><dl><dt>${key==='transmittals'?'接收方':'责任人'}</dt><dd>${r[6]}</dd><dt>${key==='transmittals'?'分发日期':'截止日期'}</dt><dd>${r[7]}</dd><dt>关联内容</dt><dd>${r[2]}</dd><dt>说明</dt><dd>${key==='issues'?'请结合当前成果版本进行核对，处理完成后提交复核。':key==='reviews'?'按选定工作流完成校核与审核，审阅意见随文件版本保留。':'请接收方按分发的版本查收成果，并确认接收情况。'}</dd></dl><h3 style="font-size:13px;font-weight:500">${key==='issues'?'关联成果':'包含文件'}</h3>${fileCard({name:r[2].includes('工点')?'桥梁设计模型':r[1],version:'V3'})}<div class="detail-actions"><button class="primary-btn" data-action="${key==='issues'?'issue':key==='reviews'?'review':'share'}">${key==='issues'?'编辑问题':key==='reviews'?'查看工作流':'查看接收人'}</button><button data-action="record-files">查看文件</button></div><ul class="history-list"><li><span class="activity-dot"></span><div><h4>${r[3]}</h4><p>当前示例流程状态</p></div></li><li><span class="activity-dot"></span><div><h4>记录已创建</h4><p>张工 · 设计期</p></div></li></ul></div>`;$('.cde-workspace').append(d);}
function showSystemGuide(){
 const guide=window.SYSTEM_GUIDE;
 const d=dialog('系统使用说明',`<div class="guide-layout"><nav class="guide-nav" aria-label="README 章节"><div class="guide-label">使用指南 / 阅读目录</div>${guide.sections.filter(s=>!s.group).map((s,i)=>`<button data-guide-section="${s.id}"><span>${String(i+1).padStart(2,'0')}</span>${esc(s.title.split(' · ')[0])}</button>`).join('')}<div class="guide-label guide-page-label">逐页操作手册 · ${guide.sections.filter(s=>s.group).length} 页</div>${['道路接入与建模','设计期','施工期','运营期'].map(g=>`<details class="guide-group" ${$('#stageName').textContent===g?'open':''}><summary>${g}<small>${guide.sections.filter(s=>s.group===g).length} 页</small></summary>${guide.sections.filter(s=>s.group===g).map(s=>`<button data-guide-section="${s.id}">${esc(s.title)}</button>`).join('')}</details>`).join('')}<div class="guide-nav-note">当前应用：${esc($('#stageName').textContent)}<br>说明更新：2026-09-14</div></nav><article class="guide-article" id="guideArticle" tabindex="0" aria-label="章节正文"></article></div>`,'');
 d.classList.add('system-guide');d.setAttribute('aria-label','系统使用说明 README');
 function renderSection(id){const s=guide.sections.find(s=>s.id===id);$$('[data-guide-section]',d).forEach(b=>{b.classList.toggle('active',b.dataset.guideSection===id);if(b.dataset.guideSection===id)b.setAttribute('aria-current','true');else b.removeAttribute('aria-current');});const a=$('#guideArticle',d);a.innerHTML=`<div class="guide-eyebrow">全生命周期数字底座 / ${esc(s.group||'使用指南')}</div><h2>${esc(s.title)}</h2><p class="guide-intro">${esc(s.intro)}</p>${s.blocks.map(b=>b.kind==='h'?`<h3>${esc(b.text)}</h3>`:b.kind==='p'?`<p>${esc(b.text)}</p>`:b.kind==='steps'?`<ol class="guide-steps">${b.items.map(t=>`<li>${esc(t)}</li>`).join('')}</ol>`:b.kind==='list'?`<ul>${b.items.map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`:`<table><thead><tr><th>页面入口</th><th>可以做什么</th></tr></thead><tbody>${b.rows.map(r=>`<tr><td><a href="${esc(r[1])}">${esc(r[0])} ↗</a></td><td>${esc(r[2])}</td></tr>`).join('')}</tbody></table>`).join('')}`;const headings=[...a.querySelectorAll('h3')];if(headings.length>3){const jump=document.createElement('label');jump.className='guide-jump';jump.innerHTML='<span>本章内容</span><select aria-label="跳转到本章内容">'+headings.map((h,i)=>'<option value="'+i+'">'+esc(h.textContent)+'</option>').join('')+'</select>';a.querySelector('.guide-intro').after(jump);jump.querySelector('select').onchange=e=>headings[Number(e.target.value)].scrollIntoView({block:'start'});}a.scrollTop=0;}
 $$('[data-guide-section]',d).forEach(b=>b.onclick=()=>renderSection(b.dataset.guideSection));
 d.querySelector('footer').innerHTML='<small>页面操作以演示数据为准 · 打开说明不改变当前业务状态</small><button class="text-button" id="guideCurrent">本页怎么用</button><button class="text-button" id="guideDownload">下载使用说明</button><button class="cde-primary" id="guideClose">返回页面</button>';
 $('#guideClose',d).onclick=()=>d.close();$('#guideDownload',d).onclick=()=>{const u=URL.createObjectURL(new Blob([guide.markdown],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=u;a.download='README.md';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);};
 $('#guideArticle',d).addEventListener('click',e=>{if(e.target.closest('a'))d.close();});
 const currentManual=guide.sections.find(s=>{if(!s.route)return false;const u=new URL(s.route,location.href);return u.pathname===location.pathname&&(!u.hash||u.hash===(location.hash|| (page==='operations'?'#twin':page==='construction'?'#home':'')));});
 $('#guideCurrent',d).hidden=!currentManual;$('#guideCurrent',d).onclick=()=>{renderSection(currentManual.id);const b=d.querySelector('[data-guide-section="'+currentManual.id+'"]');b.closest('details').open=true;const nav=b.closest('.guide-nav');nav.scrollTop+=b.getBoundingClientRect().top-nav.getBoundingClientRect().top-nav.clientHeight/2;};
 renderSection('start');
}

const actions={
 share:shareDialog,review:reviewDialog,issue:issueDialog,
 details:()=>{const el=$('.file-layout')||$('.gis-window');el?.classList.toggle('details-open');},
 'close-detail':()=>($('.file-layout')||$('.gis-window'))?.classList.remove('details-open'),
 'close-record':()=>$('.record-drawer')?.remove(),
 'record-files':()=>location.href='file-management.html',
 upload:()=>{const d=dialog('上传文件',`<p>目标目录：设计成果 / 路线设计成果 / 桥梁设计成果</p><div class="dropzone">${icon('upload')}<br>将文件拖放到此处<br><small>或选择本地文件，预览上传列表</small><label class="field"><input type="file" multiple id="demoFiles" aria-label="选择演示文件"></label></div><div id="uploadList"></div><p>同名文件将作为新版本保留，已有版本可随时查看。</p>`,'完成演示',()=>notify('上传界面演示结束，未上传或保存文件'));$('#demoFiles',d).onchange=e=>{$('#uploadList',d).innerHTML=[...e.target.files].map(f=>`<p>${esc(f.name)} · ${(f.size/1024).toFixed(1)} KB · 待上传（示例）</p>`).join('');};},
 folder:()=>dialog('新建文件夹','<label class="field">文件夹名称<input placeholder="输入文件夹名称"></label><label class="field">说明<textarea placeholder="输入文件夹用途"></textarea></label>','完成演示'),
 more:()=>dialog('文件操作',`${fileCard()}<p>对当前选中的成果进行受控管理。</p><div style="display:flex;gap:16px"><button class="text-button" data-action="share">${icon('share')}分发</button><button class="text-button" data-action="review">${icon('review')}发起审阅</button><button class="text-button" data-action="issue">${icon('issue')}创建问题</button></div>`,'',()=>{}),
 activity:()=>location.href='workflows.html#activity',
 notifications:()=>dialog('项目通知','<ul class="history-list"><li><span class="activity-dot"></span><div><h4>有一条问题待处理</h4><p>横断面测量范围补充 · D-ISS-002</p></div></li><li><span class="activity-dot"></span><div><h4>成果已完成阶段审阅</h4><p>道路设计成果阶段审查 · REV-002</p></div></li></ul>','查看问题',()=>location.href='workflows.html#issues'),
 help:showSystemGuide,
 profile:()=>dialog('当前用户','<h3>张工</h3><p>总体设计组 · 项目管理员</p><p>可查看项目成果、审阅与分发记录。</p>','查看成员',()=>location.href='workflows.html#members'),
 project:()=>dialog('切换项目',`<div class="dialog-file">${icon('building')}<strong>XX高速公路</strong><span style="margin-left:auto;color:#087fb5">当前项目</span></div><p>当前原型包含一个示例项目，各阶段应用共享该项目。</p>`,'保持当前项目',()=>{}),
 export:()=>notify('导出操作展示：可导出当前列表；此原型不生成业务文件'),
 invite:()=>dialog('邀请成员','<label class="field">成员邮箱<input type="email" placeholder="输入项目成员邮箱"></label><label class="field">角色<select><option>专业工程师</option><option>审阅人</option><option>项目管理员</option></select></label>','完成演示',()=>notify('邀请界面演示结束，未发送邀请')),
 bridge:()=>dialog('创建跨项目桥接','<label class="field">目标项目<select><option>外部施工协作项目</option><option>外部资料归档项目</option></select></label><label class="field">共享范围<select><option>已批准的设计成果</option><option>选定文件夹</option></select></label><label class="field">共享策略<select><option>指定版本快照</option></select></label>','完成演示'),
 layers:()=>{const groups=[['geology','工程地质分区'],['boundary','地质分界线'],['hazard','地质风险区'],['survey','测量控制点'],['borehole','钻孔位置']];const d=dialog('图层管理',groups.map(([k,t])=>`<label class="radio-row"><input type="checkbox" data-layer="${k}" ${$(`[data-map-layer="${k}"]`)?.style.display!=='none'?'checked':''}>${t}</label>`).join(''),'完成',()=>{});$$('[data-layer]',d).forEach(c=>c.onchange=()=>$$(`[data-map-layer="${c.dataset.layer}"]`).forEach(n=>n.style.display=c.checked?'':'none'));},
 viewpoints:()=>{const d=dialog('已保存视点',[['bridge','桥梁工点 K12+350'],['roadbed','路基工点 K10+800'],['tunnel','隧道工点 K14+000']].map(r=>`<button class="recent-file text-button" data-viewpoint="${r[0]}" style="display:flex;width:100%;height:48px">${icon('camera')}${r[1]}</button>`).join(''),'关闭',()=>{});$$('[data-viewpoint]',d).forEach(b=>b.onclick=()=>{selectResult(b.dataset.viewpoint);$('.gis-window').classList.add('details-open');d.close();});}
};
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&actions[b.dataset.action]){e.preventDefault();actions[b.dataset.action]();}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#switchMenu').hidden=true;$('#appSwitch').setAttribute('aria-expanded','false');$('.record-drawer')?.remove();}});
window.CDE = {icon,esc,dialog,notify,hydrate,activeNav};
if(page==='workflows'){renderWorkflow();window.addEventListener('hashchange',renderWorkflow);}else if(!['operations','construction'].includes(page)) setupExisting();
if(page==='files'){
 const sourceCode=new URLSearchParams(location.search).get('asset-source');
 let sourceFound=false;if(sourceCode){for(const [key,dir] of Object.entries(directories)){const item=dir.items.find(i=>i.type==='file'&&i.code===sourceCode);if(item){sourceFound=true;openDirectory(key);activeItem=item;renderRows();renderDetail();document.querySelector('.file-layout').classList.add('details-open');break;}}}
if(sourceCode&&!sourceFound)notify('未找到指定成果编码，请核对来源关联');
}
hydrate();
})();
