(() => {
'use strict';
const {icon,esc,dialog,notify}=CDE,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const nav=[['home','home','项目概览'],['sheets','layers','施工图纸'],['files','folder','项目文件'],['issues','issue','现场问题'],['forms','review','质量与安全表单'],['rfis','share','技术澄清 RFI'],['submittals','send','材料与设备报审'],['schedule','clock','进度计划'],['cost','building','成本与变更'],['assets','settings','设备与移交'],['meetings','users','会议纪要'],['reports','panel','项目报表']];
const state={view:'home',query:'',filter:'全部状态',zone:'全部工点',selected:null,tab:'详情',sheet:'S-101',sheetVersion:'V3',zoom:1,pins:true,formAnswers:{},budgetTab:'budget',sheetLayout:'list'};
const zones=['全部工点','K12+350 大桥','K14+000 隧道','综合管理站'];
const today='2026-09-11';
const rows={
issues:[
{id:'ISS-001',title:'桥台预埋件位置与施工图不一致',type:'质量',zone:zones[1],status:'处理中',owner:'李工 · 桥梁分部',due:'2026-09-10',sheet:'S-101',rfi:'RFI-001',desc:'A2 桥台预埋件定位与 V3 图纸坐标不一致，请复核定位记录。暂停相关部位浇筑，待设计澄清后处理。'},
{id:'ISS-002',title:'隧道临时用电防护未封闭',type:'安全',zone:zones[2],status:'待处理',owner:'王工 · 安全部',due:'2026-09-11',sheet:'S-201',desc:'临时配电箱防护围挡缺失，请补齐防护并上传复查记录。'},
{id:'ISS-003',title:'排水管接头试验记录待补充',type:'质量',zone:zones[2],status:'待复核',owner:'赵工 · 机电分部',due:'2026-09-13',sheet:'S-202',desc:'现场整改已完成，试验记录待监理复核。'},
{id:'ISS-004',title:'管理站设备房门洞尺寸复核',type:'协调',zone:zones[3],status:'已关闭',owner:'陈工 · 房建分部',due:'2026-09-08',sheet:'S-301',desc:'已依据审定图纸复核并完成记录归档。'},
{id:'ISS-005',title:'桥面作业临边防护待加固',type:'安全',zone:zones[1],status:'待处理',owner:'王工 · 安全部',due:'2026-09-14',sheet:'S-102',desc:'北侧作业段防护需加固，验收后恢复作业。'}],
rfis:[
{id:'RFI-001',title:'桥台预埋件定位偏差处理方案',type:'结构专业',zone:zones[1],status:'审查中',owner:'周工 · 设计单位',due:'2026-09-12',sheet:'S-101',issue:'ISS-001',desc:'请明确 A2 桥台预埋件定位偏差的处理方式，以及是否需要调整配筋与施工顺序。',response:''},
{id:'RFI-002',title:'隧道消防管线与桥架净距确认',type:'机电专业',zone:zones[2],status:'已答复',owner:'张工 · RFI 经理',due:'2026-09-13',sheet:'S-202',desc:'请核实消防管线与电缆桥架的交叉布置。',response:'按审定深化图调整桥架标高，施工前复核检修空间。'},
{id:'RFI-003',title:'管理站屋面设备基础标高',type:'建筑专业',zone:zones[3],status:'草稿',owner:'陈工 · 房建分部',due:'2026-09-15',sheet:'S-301',desc:'请确认屋面设备基础与建筑完成面的标高关系。',response:''}],
submittals:[
{id:'SUB-001',title:'桥梁支座产品资料及型式试验报告',type:'产品资料',zone:zones[1],status:'审查中',owner:'刘工 · 专业监理',due:'2026-09-12',sheet:'S-101',spec:'桥梁工程 / 支座',package:'大桥支座采购包',desc:'提交支座技术参数、合格证明和型式试验报告。'},
{id:'SUB-002',title:'隧道射流风机设备报审',type:'设备资料',zone:zones[2],status:'待提交',owner:'赵工 · 机电分部',due:'2026-09-14',sheet:'S-201',spec:'隧道机电 / 通风',package:'隧道通风设备包',desc:'风机设备参数与安装维护手册。'},
{id:'SUB-003',title:'C50 混凝土配合比试验报告',type:'试验报告',zone:zones[1],status:'已批准',owner:'刘工 · 专业监理',due:'2026-09-08',sheet:'S-102',spec:'桥梁工程 / 混凝土',package:'桥面施工材料包',desc:'已完成配合比审查。'},
{id:'SUB-004',title:'配电柜深化接线图',type:'深化图纸',zone:zones[3],status:'退回修改',owner:'陈工 · 房建分部',due:'2026-09-16',sheet:'S-301',spec:'房建工程 / 配电',package:'管理站设备包',desc:'需补充回路编号与设计来源后重新提交。'}],
forms:[
{id:'FRM-001',title:'桥台钢筋与预埋件隐蔽验收',type:'质量检查',zone:zones[1],status:'进行中',owner:'刘工 · 专业监理',due:today,sheet:'S-101',desc:'浇筑前验收记录',items:['钢筋规格与间距核查','预埋件定位复核','保护层及垫块检查','隐蔽验收资料核对']},
{id:'FRM-002',title:'隧道施工临时用电巡检',type:'安全巡检',zone:zones[2],status:'进行中',owner:'王工 · 安全部',due:today,sheet:'S-201',desc:'每日现场安全巡检',items:['配电箱防护检查','漏电保护装置检查','线路敷设检查','作业人员交底记录']},
{id:'FRM-003',title:'桥面混凝土浇筑施工日报',type:'施工日报',zone:zones[1],status:'已完成',owner:'李工 · 桥梁分部',due:'2026-09-10',sheet:'S-102',desc:'气象、人员、设备和当日完成量均已记录。',items:['天气与作业条件','人员与机械投入','完成工程量','现场事项与附件']}],
assets:[
{id:'FAN-01',title:'左洞射流风机 01',type:'通风设备',zone:zones[2],status:'调试中',owner:'赵工 · 机电分部',due:'2026-09-20',sheet:'S-201',submittal:'SUB-002',desc:'安装完成，单机调试及运维手册待验证。'},
{id:'PUMP-01',title:'隧道排水泵 01',type:'排水设备',zone:zones[2],status:'已安装',owner:'赵工 · 机电分部',due:'2026-09-22',sheet:'S-202',desc:'设备已安装，待组织调试。'},
{id:'DB-01',title:'隧道低压配电柜',type:'供配电设备',zone:zones[2],status:'待移交',owner:'赵工 · 机电分部',due:'2026-09-18',sheet:'S-201',desc:'调试与资料验证通过，等待移交确认。'}],
meetings:[
{id:'MTG-001',title:'第 18 次施工协调例会',type:'周例会',zone:'全项目',status:'待召开',owner:'张工 · 项目经理',due:'2026-09-14',desc:'重点协调桥台预埋件方案、隧道通风设备报审与下周施工计划。'},
{id:'MTG-002',title:'隧道机电安装专题会',type:'专题会',zone:zones[2],status:'已发布',owner:'赵工 · 机电分部',due:'2026-09-09',desc:'确认机电安装界面与调试顺序，跟踪责任事项。'}]
};
const sheets=[['S-101','桥台一般构造及预埋件定位图',zones[1],'桥梁','V3'],['S-102','桥面铺装及排水构造图',zones[1],'桥梁','V2'],['S-201','隧道通风设备布置图',zones[2],'机电','V4'],['S-202','隧道排水系统安装图',zones[2],'机电','V2'],['S-301','管理站设备房平面图',zones[3],'房建','V2'],['S-302','管理站配电系统图',zones[3],'电气','V1']];
const tasks=[['ACT-01','桥台钢筋与预埋件安装',zones[1],1,13,76,'ISS-001'],['ACT-02','桥面混凝土浇筑',zones[1],8,19,42,'SUB-003'],['ACT-03','隧道通风设备安装',zones[2],5,22,60,'SUB-002'],['ACT-04','隧道排水系统试验',zones[2],14,25,0,'ISS-003'],['ACT-05','管理站配电安装',zones[3],11,27,20,'SUB-004'],['ACT-06','机电系统联合调试',zones[2],23,30,0,'FAN-01']];
const budgets=[['01','桥梁工程',3800,120,3410,3070],['02','隧道土建',6200,0,5890,4900],['03','隧道机电',1680,35,1490,920],['04','管理站工程',820,0,730,450]];
const changes=[{id:'PCO-001',title:'桥台预埋件处理潜在变更',status:'待评估',amount:18,source:'RFI-001',owner:'孙工 · 商务部',zone:zones[1],desc:'预计金额仅为待评估值，未计入已批准预算。'},{id:'CO-002',title:'桥梁施工临时工程调整',status:'已批准',amount:120,owner:'孙工 · 商务部',zone:zones[1],desc:'已批准变更计入预算。'},{id:'CO-003',title:'隧道电缆桥架调整',status:'已批准',amount:35,owner:'孙工 · 商务部',zone:zones[2],desc:'已批准变更计入预算。'}];
const host=$('#constructionWorkspace');
function pill(s){return `<span class="build-pill ${/关闭|批准|完成|发布|移交完成/.test(s)?'green':/退回|逾期/.test(s)?'red':/待|调试/.test(s)?'amber':'blue'}">${esc(s)}</span>`;}
function overdue(r){return r.due<today&&!/关闭|批准|完成|发布/.test(r.status);}
function button(action,text,primary=false){return `<button class="${primary?'cde-primary':'text-button'}" data-build="${action}">${text}</button>`;}
function go(v){state.selected=null;state.query='';state.filter='全部状态';state.tab='详情';if(location.hash==='#'+v)render();else location.hash=v;}
function navigateRecord(id){const type=Object.keys(rows).find(k=>rows[k].some(r=>r.id===id));if(type){state.selected=id;state.query='';state.filter='全部状态';state.zone='全部工点';state.tab='详情';location.hash=type;render();}else if(changes.some(r=>r.id===id)){state.budgetTab='changes';location.hash='cost';render();detail(changes.find(r=>r.id===id),'cost');}}
function find(id){return Object.values(rows).flat().find(r=>r.id===id)||changes.find(r=>r.id===id);}
function list(){return (rows[state.view]||[]).filter(r=>(state.zone==='全部工点'||r.zone===state.zone)&&(state.filter==='全部状态'||(state.filter==='已逾期'?overdue(r):r.status===state.filter))&&(!state.query||[r.id,r.title,r.owner,r.zone,r.type].join(' ').toLowerCase().includes(state.query.toLowerCase())));}
function navRender(){ $('#cdeNav').innerHTML=`<div class="build-nav-list">${nav.map(([v,i,t])=>`<a href="#${v}" data-build-nav="${v}" class="${state.view===v?'active':''}" ${state.view===v?'aria-current="page"':''}>${icon(i)}<span class="nav-text">${t}</span>${v==='issues'?`<span class="nav-count">${rows.issues.filter(r=>r.status!=='已关闭').length}</span>`:''}</a>`).join('')}</div><div class="build-nav-foot"><a href="file-management.html">${icon('folder')}<span class="nav-text">成果资料库</span></a><a href="operations.html#twin">${icon('settings')}<span class="nav-text">Tandem</span></a></div>`;}
function heading(title,sub){return `<header class="build-heading"><div><h1>${title}</h1></div><div class="build-heading-right">${button('help',icon('help')+' 项目帮助')}</div></header>`;}
function context(){const globalScope=['home','cost','reports','files'].includes(state.view);return `<div class="build-context">${icon('building')}<b>合同段 T1</b><span>/</span><select id="buildZone" ${globalScope?'disabled':''} aria-label="选择工点">${zones.map(z=>`<option ${(globalScope?zones[0]:state.zone)===z?'selected':''}>${z}</option>`).join('')}</select><span class="toolbar-spacer"></span><span>项目经理</span><span class="build-avatar">张</span><b>张工</b></div>`;}
function toolbar(primary){const statuses=['全部状态',...new Set((rows[state.view]||[]).map(r=>r.status)),'已逾期'];return `<div class="build-toolbar">${button('create',primary,true)}${button('export',icon('file')+' 导出')}<span class="toolbar-spacer"></span><select id="buildFilter" aria-label="按状态筛选">${statuses.map(s=>`<option ${s===state.filter?'selected':''}>${s}</option>`).join('')}</select><label class="build-search">${icon('search')}<input id="buildSearch" aria-label="搜索施工记录" value="${esc(state.query)}" placeholder="搜索名称、编号、责任人"></label></div>`;}
function table(data){return `<table class="build-table"><thead><tr><th>编号</th><th>标题 / 类型</th><th>状态</th><th>当前责任人</th><th>工点</th><th>截止日期</th></tr></thead><tbody>${data.map(r=>`<tr data-record-build="${r.id}" class="${state.selected===r.id?'selected':''}" tabindex="0"><td class="build-id">${r.id}</td><td><strong>${esc(r.title)}</strong><small>${esc(r.type)}</small></td><td>${pill(r.status)}</td><td>${esc(r.owner)}</td><td>${esc(r.zone)}</td><td class="${overdue(r)?'build-overdue':''}">${esc(r.due)}${overdue(r)?'<small>已逾期</small>':''}</td></tr>`).join('')}</tbody></table>${!data.length?'<div class="build-empty">没有符合条件的记录<br><button class="text-button" data-build="reset">清除筛选</button></div>':''}`;}
function recordPage(){const config={issues:['跟踪质量、安全与现场协调问题','创建问题'],forms:['标准化现场检查，关联不符合项并跟踪整改','创建表单'],rfis:['提交技术问题，指定审查人并确认正式答复','创建 RFI'],submittals:['按规范章节与报审包组织材料、设备和深化图审查','创建报审'],assets:['跟踪设备从安装、调试到资料验证与移交的状态','登记设备'],meetings:['汇总议题、关联记录并明确后续责任事项','创建会议']}[state.view];host.innerHTML=heading(nav.find(n=>n[0]===state.view)[2],config[0])+context()+`<div class="build-tabs"><button class="active">${state.view==='submittals'?'报审台账':state.view==='forms'?'全部表单':'全部记录'}</button>${state.view==='submittals'?button('packages','报审包与规范章节'):state.view==='forms'?button('templates','表单模板'):''}<span class="toolbar-spacer"></span></div>`+toolbar(config[1])+`<div class="build-table-wrap">${table(list())}</div><footer class="build-footer"><span id="buildCount">共 ${list().length} 条记录</span></footer>`;if(state.selected){const r=(rows[state.view]||[]).find(r=>r.id===state.selected);if(r)detail(r,state.view);else state.selected=null;}}
function home(){const open=rows.issues.filter(r=>r.status!=='已关闭'),urgent=Object.values(rows).flat().filter(overdue);host.innerHTML=heading('项目概览','从今日待办进入现场执行、技术协作与交付管理')+context()+`<div class="build-home"><div class="build-kpis">${[[open.length,'未关闭现场问题','issues','质量 / 安全 / 协调'],[rows.rfis.filter(r=>!['已关闭','已答复'].includes(r.status)).length,'待推进技术澄清','rfis','明确当前责任人'],[rows.submittals.filter(r=>r.status!=='已批准').length,'待完成报审','submittals','材料与设备审查'],[urgent.length,'已逾期事项','urgent','按示例日期计算']].map(([n,t,v,sub])=>`<button data-home="${v}"><span>${t} ${icon('arrow')}</span><strong>${n}</strong></button>`).join('')}</div><div class="build-home-grid"><section class="build-card"><header><h2>需要关注</h2><span>现场问题与技术协作</span></header>${[...open.slice(0,3),rows.rfis[0]].map(r=>`<button class="build-task" data-ref="${r.id}"><span class="build-task-icon">${icon(r.id.startsWith('RFI')?'share':'issue')}</span><span><b>${esc(r.title)}</b><small>${r.id} · ${esc(r.owner)} · ${esc(r.zone)}</small></span>${pill(overdue(r)?'已逾期':r.status)}${icon('arrow')}</button>`).join('')}</section><section class="build-card"><header><h2>快速访问</h2></header><div class="build-flow-vertical">${[['sheets','01','施工图纸','6 张已发布图纸 · 版本集可追溯'],['forms','02','质量与安全表单','质量验收、安全巡检与施工日报'],['rfis','03','技术澄清 RFI','关联问题、设计答复与潜在变更'],['assets','04','设备与移交','安装调试记录与运维资料验证']].map(([v,n,t,s])=>`<button data-home="${v}"><span><b>${t}</b></span>${icon('arrow')}</button>`).join('')}</div></section><section class="build-card build-wide"><header><h2>近期作业</h2><button class="text-button" data-home="schedule">打开进度计划 ↗</button></header><div class="build-upcoming">${tasks.slice(0,3).map(t=>`<button data-ref="${t[6]}"><small>${t[0]} · ${t[2]}</small><b>${t[1]}</b><div class="build-progress"><i style="width:${t[5]}%"></i></div><span>${t[5]}% 已完成 <small>09-${t[3].toString().padStart(2,'0')} — 09-${t[4]}</small></span></button>`).join('')}</div></section></div></div>`;}
function drawing(s){return `<svg viewBox="0 0 1000 610" class="build-drawing" aria-label="${s[1]}图纸示意" role="img"><rect x="30" y="25" width="940" height="555" fill="white" stroke="#6b8494"/><rect x="43" y="38" width="914" height="470" fill="none" stroke="#b3c0c8"/><g fill="none" stroke="#557183" stroke-width="1.6">${s[3]==='桥梁'?`<path d="M160 195H810V290H160ZM140 184H830V196H140ZM195 290V400H275V290M440 290V400H520V290M695 290V400H775V290"/><path d="M155 255H815M195 312H275M440 312H520M695 312H775"/>${Array.from({length:30},(_,i)=>`<path d="M${170+i*21} 200v83" stroke="#99adb9"/>`).join('')}<path d="M190 160H775M190 150v20M775 150v20M195 420H775M195 410v20M775 410v20"/><path d="M200 200l58 58m-58 0 58-58" stroke="#d08d3b" stroke-width="3"/>`:`<rect x="155" y="155" width="660" height="235"/><path d="M170 270H800M170 285H800M350 155v100M580 295v95"/>${Array.from({length:7},(_,i)=>`<rect x="${185+i*86}" y="190" width="45" height="30"/><path d="M${207+i*86} 220v50"/>`).join('')}<path d="M160 425H815M160 415v20M815 415v20"/>`}</g><g font-family="sans-serif" fill="#536c7b" text-anchor="middle"><text x="500" y="95" font-size="22">${s[1]}</text><text x="500" y="125" font-size="13">${s[2]} · 施工图示意</text><text x="490" y="152" font-size="13">尺寸详见审定施工图</text><text x="485" y="454" font-size="14">${s[0]}　平面 / 构造示意</text></g><path d="M43 508H957M650 508v59M805 508v59M650 537H957" stroke="#6b8494" fill="none"/><g font-size="12" fill="#536c7b"><text x="62" y="535">XX 高速公路　施工图纸</text><text x="62" y="555">演示图纸 · 不作为施工依据</text><text x="665" y="527">图号 ${s[0]}</text><text x="820" y="527">${state.sheetVersion}</text><text x="665" y="557">版本集：09 月施工发行</text></g></svg>`;}
function sheetsPage(){const data=sheets.filter(s=>(state.zone==='全部工点'||s[2]===state.zone)&&(!state.query||s.join(' ').toLowerCase().includes(state.query.toLowerCase())));host.innerHTML=heading('施工图纸','面向现场的已发布图纸，按版本集查阅并关联问题')+context()+`<div class="build-tabs"><button class="active">图纸 (${data.length})</button>${button('versions','版本集')}<span class="toolbar-spacer"></span><span>最新已发布版本</span></div><div class="build-toolbar">${button('publish','＋ 发布图纸',true)}${button('collections','图纸集')}${button('sheet-layout',state.sheetLayout==='list'?'缩略图视图':'列表视图')}<span class="toolbar-spacer"></span><label class="build-search">${icon('search')}<input id="sheetSearch" value="${esc(state.query)}" placeholder="搜索图号或名称" aria-label="搜索施工图纸"></label></div><div class="${state.sheetLayout==='list'?'build-table-wrap build-sheet-list':'build-sheet-grid'}">${state.sheetLayout==='list'?`<table class="build-table"><thead><tr><th>图号</th><th>图纸名称</th><th>当前版本</th><th>专业</th><th>工点</th><th>版本集</th></tr></thead><tbody>${data.map(s=>`<tr data-sheet="${s[0]}"><td class="build-id">${s[0]}</td><td><div class="build-sheet-row-title"><span>${drawing(s)}</span><strong>${s[1]}</strong></div></td><td><span class="version-pill">${s[4]}</span></td><td>${s[3]}</td><td>${s[2]}</td><td>09 月施工发行</td></tr>`).join('')}</tbody></table>${!data.length?'<div class="build-empty">没有符合条件的图纸</div>':''}`:data.map(s=>`<button class="build-sheet-card" data-sheet="${s[0]}"><div class="build-sheet-thumb">${drawing(s)}<span>${s[4]}</span></div><div><b>${s[0]} <span>${s[3]}</span></b><strong>${s[1]}</strong><small>${s[2]} · 2026-09-10 发布</small></div></button>`).join('')||'<div class="build-empty">没有符合条件的图纸</div>'}</div>`;}
function sheetViewer(id){const s=sheets.find(s=>s[0]===id)||sheets[0];state.sheet=s[0];state.sheetVersion=s[4];state.zoom=1;const d=dialog(s[0]+' · '+s[1],'<div id="sheetViewerContent"></div>','');d.classList.add('build-viewer');function paint(){const related=rows.issues.filter(r=>r.sheet===s[0]);$('#sheetViewerContent').innerHTML=`<div class="build-viewer-toolbar"><label>版本 <select id="sheetVersion">${[s[4],'V1'].filter((v,i,a)=>a.indexOf(v)===i).map(v=>`<option ${state.sheetVersion===v?'selected':''}>${v}</option>`).join('')}</select></label><span>${state.sheetVersion===s[4]?'当前发布版本':'历史存档版本 · 同一示意图'}</span><span class="toolbar-spacer"></span><button id="sheetZoomOut">−</button><span>${Math.round(state.zoom*100)}%</span><button id="sheetZoomIn">＋</button><button id="sheetPins">${state.pins?'隐藏':'显示'}问题标记</button></div><div class="build-viewer-body"><div class="build-sheet-canvas"><div style="transform:scale(${state.zoom})">${drawing(s)}${state.pins?related.map((r,i)=>`<button class="build-pin" style="left:${29+i*14}%;top:${41+i*6}%" data-pin="${r.id}" title="${esc(r.title)}">${i+1}</button>`).join(''):''}</div></div><aside><h3>关联问题 <span>${related.length}</span></h3>${related.map(r=>`<button class="build-viewer-issue" data-pin="${r.id}"><small>${r.id}</small><b>${esc(r.title)}</b>${pill(r.status)}</button>`).join('')||'<p>当前图纸暂无关联问题。</p>'}${button('sheet-create-issue','＋ 创建关联问题',true)}<button class="text-button lc-reference-button" data-lifecycle>核验设计来源与发行链 ↗</button>${[...new Set(WBS.docs.filter(d=>d.ref===s[0]).map(d=>d.wbs))].map(id=>`<a class="build-reference" href="construction.html?wbs=${id}#files">WBS ${id} · 工作包资料 ↗</a>`).join('')}<p class="build-note">已发布为本页示例状态；原始设计文件、审批与发行单尚待关联。</p></aside></div>`;$('#sheetVersion').onchange=e=>{state.sheetVersion=e.target.value;paint();};$('#sheetZoomIn').onclick=()=>{state.zoom=Math.min(1.5,state.zoom+.1);paint();};$('#sheetZoomOut').onclick=()=>{state.zoom=Math.max(.7,state.zoom-.1);paint();};$('#sheetPins').onclick=()=>{state.pins=!state.pins;paint();};$$('[data-pin]').forEach(b=>b.onclick=()=>{d.close();navigateRecord(b.dataset.pin);});}paint();}
function steps(values,current){return `<div class="build-steps">${values.map((v,i)=>`<div class="${i<=current?'done':''}"><span>${i+1}</span>${v}</div>`).join('')}</div>`;}
function detail(r,type){$('.build-drawer')?.remove();state.selected=r.id;const drawer=document.createElement('aside');drawer.className='build-drawer';drawer.setAttribute('aria-label','记录详情');const workflow=type==='rfis'?['草稿','审查中','已答复','已关闭']:type==='submittals'?['待提交','审查中','已批准']:type==='issues'?['待处理','处理中','待复核','已关闭']:type==='assets'?['已安装','调试中','待移交','移交完成']:[];
let body=`<p class="build-description">${esc(r.desc)}</p>${workflow.length?steps(workflow,workflow.indexOf(r.status)):''}<dl class="build-props"><dt>状态</dt><dd>${pill(r.status)}</dd><dt>当前责任人</dt><dd>${esc(r.owner)}</dd><dt>工点</dt><dd>${esc(r.zone)}</dd><dt>截止日期</dt><dd>${r.due||'待评估'}</dd>${r.spec?`<dt>规范章节</dt><dd>${r.spec}</dd><dt>报审包</dt><dd>${r.package}</dd>`:''}${r.amount?`<dt>预估金额</dt><dd>${r.amount} 万元</dd>`:''}</dl>`;
if(type==='rfis')body+=`<section class="build-detail-block"><h3>答复与责任流转</h3><p>施工方提交 → RFI 经理分派 → 设计审查 → 经理确认正式答复</p><label>正式答复<textarea id="rfiResponse" placeholder="输入设计澄清意见">${esc(r.response||'')}</textarea></label></section>`;
if(type==='submittals')body+=`<section class="build-detail-block"><h3>审查工作流</h3><p>提交方：施工分部<br>报审经理：张工<br>专业审查：刘工 / 周工</p><label>审查意见<textarea id="submittalResponse" placeholder="填写批准或退回意见">${esc(r.response||'')}</textarea></label></section>`;
if(type==='forms')body+=`<section class="build-detail-block"><h3>检查清单</h3>${r.items.map((t,i)=>`<label class="build-check-item"><span>${i+1}. ${t}</span><select data-answer="${r.id}-${i}" ${r.status==='已完成'?'disabled':''}>${['未检查','符合','不符合','不适用'].map(a=>`<option ${((state.formAnswers[r.id+'-'+i]||(r.status==='已完成'?'符合':'未检查'))===a)?'selected':''}>${a}</option>`).join('')}</select></label>`).join('')}<p>不符合项可创建关联问题，完成整改后再复核。</p></section>`;
if(type==='assets')body+=`<section class="build-detail-block"><h3>调试与移交清单</h3><p>接收确认与后续运营示例分开记录；当前页流转不自动同步运营数据。</p>${['设备安装验收','单机调试记录','运维手册与产品资料'].map((t,i)=>`<label class="build-check-item"><span>${t}</span><input type="checkbox" data-asset-check="${r.id}-${i}" ${r.checks?.[i]||r.status==='待移交'||r.status==='移交完成'?'checked':''}></label>`).join('')}</section>`;
if(type==='meetings')body+=`<section class="build-detail-block"><h3>议题与行动项</h3>${[['RFI-001','确认桥台预埋件答复 · 周工 · 09-12'],['SUB-002','提交风机报审资料 · 赵工 · 09-14'],['ISS-002','复查临时用电整改 · 王工 · 09-11']].map(([id,t])=>`<button class="build-reference" data-ref="${id}">${id}<span>${t}</span>↗</button>`).join('')}<label>会议记录<textarea id="meetingNote" placeholder="记录讨论结论与后续事项">${esc(r.note||'')}</textarea></label></section>`;
const refs=[r.issue,r.rfi,r.submittal,r.source,r.linkedIssue].filter(Boolean);body+=`<section class="build-detail-block"><h3>关联记录</h3>${r.sheet?`<button class="build-reference" data-sheet="${r.sheet}">${icon('layers')}<span>${r.sheet} · 关联施工图纸</span>↗</button>`:''}${refs.map(id=>`<button class="build-reference" data-ref="${id}">${icon('share')}<span>${id} · ${esc(find(id)?.title||'关联记录')}</span>↗</button>`).join('')}${!r.sheet&&!refs.length?'<p>暂无关联记录</p>':''}</section>`;
body+=`<section class="build-detail-block"><h3>工作包资料</h3>${[...new Set(WBS.docs.filter(d=>d.ref===r.id).map(d=>d.wbs))].map(id=>`<a class="build-reference" href="construction.html?wbs=${id}#files">${id} · ${WBS.node(id).name} ↗</a>`).join('')||'<p>当前记录尚未建立 WBS 文件归属。</p>'}</section>`;
let actions=type==='issues'?button('advance','推进处理状态',true)+button('issue-rfi','关联 / 创建 RFI'):type==='rfis'?button('advance','推进 RFI 流程',true)+button('rfi-change','查看 / 创建潜在变更'):type==='submittals'?button('advance','推进报审流程',true)+button('return-submittal','退回修改'):type==='forms'?button('complete-form','完成检查',true)+button('form-issue','从不符合项创建问题'):type==='assets'?button('advance','推进安装与移交',true)+button('operations','定位后续运营示例'):type==='meetings'?button('save-meeting','保存会议记录',true):'';
drawer.innerHTML=`<header><span>${r.id}</span><button class="quiet-button" data-build="close-detail" aria-label="关闭详情">×</button></header><div class="build-drawer-scroll"><h2>${esc(r.title)}</h2><div class="build-drawer-tabs"><button data-detail-tab="详情" class="${state.tab==='详情'?'active':''}">详情</button><button data-detail-tab="活动" class="${state.tab==='活动'?'active':''}">活动</button></div>${state.tab==='活动'?`<div class="build-activity">${(r.activity||['创建示例记录','分派至当前责任人']).map(t=>`<p><i></i>${esc(t)}<small>本次演示记录</small></p>`).join('')}</div>`:body}</div><footer>${actions}</footer>`;host.append(drawer);}
function schedule(){host.innerHTML=heading('进度计划','查看导入的总进度，跟踪作业完成情况与关联事项')+context()+`<div class="build-tabs"><button class="active">总进度计划</button>${button('workplan','短期作业计划')}<span class="toolbar-spacer"></span><span>09 月计划 · V3 · Primavera P6 示例</span></div><div class="build-toolbar">${button('import-schedule','导入计划',true)}${button('compare-schedule','版本比较')}<span class="toolbar-spacer"></span><span>2026 年 9 月　01 — 30 日</span></div><div class="build-gantt"><div class="build-gantt-header"><span>作业名称 / 工点</span><div>${[1,5,10,15,20,25,30].map(n=>`<span style="left:${(n-1)/30*100}%">${n} 日</span>`).join('')}</div></div>${tasks.filter(t=>state.zone==='全部工点'||t[2]===state.zone).map(t=>`<button class="build-gantt-row" data-task="${t[0]}"><span><b>${t[1]}</b><small>${t[0]} · WBS ${WBS.activityMap[t[0]]} · ${t[5]}%</small></span><div><i class="today-line" style="left:33.333%"></i><span class="gantt-bar ${t[6]==='ISS-001'?'risk':''}" style="left:${(t[3]-1)/30*100}%;width:${(t[4]-t[3]+1)/30*100}%"><i style="width:${t[5]}%"></i><b>${t[5]}%</b></span></div></button>`).join('')}<footer><span><i class="blue-dot"></i>计划作业</span><span><i class="amber-dot"></i>有关联风险</span><span>竖线：09-11 示例日期</span></footer></div>`;}
function cost(){const total=i=>budgets.reduce((n,b)=>n+b[i],0);host.innerHTML=heading('成本与变更','区分原始预算、批准变更与待评估风险')+context()+`<div class="build-tabs">${[['budget','预算'],['changes','变更事件'],['contracts','合同与支付']].map(([v,t])=>`<button data-cost-tab="${v}" class="${state.budgetTab===v?'active':''}">${t}</button>`).join('')}<span class="toolbar-spacer"></span><span>项目总览 · 单位：万元</span></div><div class="build-cost-kpis">${[[total(2),'原始预算'],[total(3),'已批准变更'],[total(2)+total(3),'修订预算'],[changes.filter(c=>c.status==='待评估').reduce((n,c)=>n+c.amount,0),'待评估潜在变更']].map(([n,t])=>`<div><span>${t}</span><strong>${n.toLocaleString()}<small> 万元</small></strong></div>`).join('')}</div><div class="build-toolbar">${button('cost-help','成本口径说明')}${state.budgetTab==='changes'?button('new-change','创建变更事件',true):''}<span class="toolbar-spacer"></span><span>潜在变更尚未计入修订预算</span></div><div class="build-table-wrap">${state.budgetTab==='budget'?`<table class="build-table cost-table"><thead><tr>${['预算编码','工程分项','原始预算','批准变更','修订预算','已签约','已支付'].map(t=>`<th>${t}</th>`).join('')}</tr></thead><tbody>${budgets.map(b=>`<tr>${[b[0],b[1],b[2],b[3],b[2]+b[3],b[4],b[5]].map(t=>`<td>${typeof t==='number'?t.toLocaleString():t}</td>`).join('')}</tr>`).join('')}</tbody></table>`:state.budgetTab==='changes'?`<table class="build-table"><thead><tr><th>编号</th><th>变更事件</th><th>状态</th><th>金额（万元）</th><th>来源</th><th>责任人</th></tr></thead><tbody>${changes.map(c=>`<tr data-change="${c.id}"><td class="build-id">${c.id}</td><td><strong>${esc(c.title)}</strong><small>${esc(c.zone)}</small></td><td>${pill(c.status)}</td><td>${c.amount}</td><td>${c.source||'审定变更记录'}</td><td>${esc(c.owner)}</td></tr>`).join('')}</tbody></table>`:`<table class="build-table cost-table"><thead><tr><th>合同编号</th><th>工程范围</th><th>已签约金额</th><th>已支付金额</th><th>未支付余额</th><th>状态</th></tr></thead><tbody>${budgets.map(b=>`<tr><td>HT-${b[0]}</td><td>${b[1]}</td><td>${b[4].toLocaleString()}</td><td>${b[5].toLocaleString()}</td><td>${(b[4]-b[5]).toLocaleString()}</td><td>${pill('履约中')}</td></tr>`).join('')}</tbody></table>`}</div>`;}
function files(){host.innerHTML='<header class="page-top"><div><h1>项目文件</h1></div></header><div class="wbs-workspace-tabs"><span>文件夹</span><small>WBS 工作分解结构</small></div>'+'<div id="wbsWorkspace"></div>';WBS.render($('#wbsWorkspace'));}
function reports(){const groups=[['现场问题',rows.issues],['技术澄清',rows.rfis],['报审事项',rows.submittals],['现场表单',rows.forms]];host.innerHTML=heading('项目报表','基于同一组示例记录汇总状态与待办')+context()+`<div class="build-toolbar">${button('report-export','导出项目摘要',true)}<span class="toolbar-spacer"></span><span>统计范围：全项目 · 截至 2026-09-11</span></div><div class="build-report-grid">${groups.map(([t,rs])=>`<section class="build-card"><header><h2>${t}</h2><b>${rs.length} 条</b></header><div class="build-report-bars">${[...new Set(rs.map(r=>r.status))].map(s=>{const n=rs.filter(r=>r.status===s).length;return `<div><span>${s}</span><div><i style="width:${n/rs.length*100}%"></i></div><b>${n}</b></div>`}).join('')}</div></section>`).join('')}<section class="build-card build-wide"><header><h2>逾期事项</h2><span>已关闭 / 完成的记录不计入</span></header>${Object.values(rows).flat().filter(overdue).map(r=>`<button class="build-task" data-ref="${r.id}"><span><b>${r.id} · ${esc(r.title)}</b><small>${esc(r.owner)} · 截止 ${esc(r.due)}</small></span>${pill('已逾期')}</button>`).join('')||'<div class="build-empty">当前没有逾期事项</div>'}</section></div>`;}
function render(){const v=location.hash.slice(1)||'home';state.view=nav.some(n=>n[0]===v)?v:'home';navRender();({home,sheets:sheetsPage,schedule,cost,files,reports}[state.view]||recordPage)();$('#buildZone')?.addEventListener('change',e=>{state.zone=e.target.value;state.selected=null;render();});$('#buildFilter')?.addEventListener('change',e=>{state.filter=e.target.value;state.selected=null;render();});$('#buildSearch')?.addEventListener('input',e=>{state.query=e.target.value;$('.build-table-wrap').innerHTML=table(list());$('#buildCount').textContent=`共 ${list().length} 条记录`;$('.build-drawer')?.remove();state.selected=null;});$('#sheetSearch')?.addEventListener('input',e=>{const pos=e.target.selectionStart;state.query=e.target.value;render();const el=$('#sheetSearch');el.focus();el.setSelectionRange(pos,pos);});}
function create(type=state.view,source){const labels={issues:'问题',rfis:'RFI',submittals:'报审',forms:'表单',assets:'设备',meetings:'会议'};const d=dialog('创建'+labels[type],`<label class="field">标题<input id="newTitle" value="${esc(source?.title||'')}" placeholder="输入${labels[type]}名称"></label><label class="field">工点<select id="newZone">${zones.slice(1).map(z=>`<option ${z===(source?.zone||state.zone)?'selected':''}>${z}</option>`).join('')}</select></label><label class="field">责任人<input id="newOwner" value="张工 · 项目管理部"></label><label class="field">截止日期<input id="newDue" type="date" value="2026-09-18"></label><label class="field">说明<textarea id="newDesc">${esc(source?.desc||'')}</textarea></label><p id="newError" class="build-overdue"></p>`,'创建示例记录');$('#dialogConfirm').onclick=()=>{const title=$('#newTitle').value.trim(),owner=$('#newOwner').value.trim(),due=$('#newDue').value;if(!title||!owner||!due){$('#newError').textContent='请填写标题、责任人和截止日期。';return;}const prefixes={issues:'ISS',rfis:'RFI',submittals:'SUB',forms:'FRM',assets:'AST',meetings:'MTG'};const r={id:prefixes[type]+'-'+String(rows[type].length+1).padStart(3,'0'),title,type:{issues:'现场协调',rfis:'技术澄清',submittals:'产品资料',forms:'现场检查',assets:'机电设备',meetings:'协调会议'}[type],zone:$('#newZone').value,status:{issues:'待处理',rfis:'草稿',submittals:'待提交',forms:'进行中',assets:'已安装',meetings:'待召开'}[type],owner,due,desc:$('#newDesc').value,sheet:source?.sheet||sheets.find(s=>s[2]===$('#newZone').value)?.[0],items:['资料核对','现场检查','结果确认'],response:''};if(type==='rfis'&&source){r.issue=source.id;source.rfi=r.id;}rows[type].push(r);d.close();navigateRecord(r.id);notify('已创建本次会话中的示例记录');};}
function log(r,t){(r.activity||(r.activity=[])).push(t);render();}
function advance(){const r=find(state.selected),type=state.view;const paths={issues:['待处理','处理中','待复核','已关闭'],rfis:['草稿','审查中','已答复','已关闭'],submittals:['待提交','审查中','已批准'],assets:['已安装','调试中','待移交','移交完成']};if(type==='rfis'){r.response=$('#rfiResponse')?.value||r.response;if(r.status==='审查中'&&!r.response.trim()){notify('请先填写正式答复');return;}}if(type==='submittals'){r.response=$('#submittalResponse')?.value||'';if(r.status==='审查中'&&!r.response.trim()){notify('请先填写审查意见');return;}if(r.status==='退回修改'){r.status='待提交';log(r,'修订后重新准备提交');return;}}if(type==='assets'&&['调试中','待移交'].includes(r.status)){
if(!$$('[data-asset-check]').every(c=>c.checked)){notify('请先完成安装、调试与资料检查');return;}
if(r.submittal&&find(r.submittal)?.status!=='已批准'){notify('关联设备报审尚未批准，不能进入移交');return;}
if(r.status==='待移交'){const d=dialog('移交接收确认',`<p>${esc(r.id)} · ${esc(r.title)}</p><p>请确认接收单位已核对设备、调试结果与资料清单。本动作仅形成当前施工页的示例记录。</p><label class="radio-row"><input id="handoverAccepted" type="checkbox">运营接收方已确认</label>`,'确认移交');$('#dialogConfirm').onclick=()=>{if(!$('#handoverAccepted').checked){notify('请先确认接收方验收');return;}r.status='移交完成';d.close();log(r,'运营接收方确认示例移交；未自动同步资产数据');};return;}
}const p=paths[type],idx=p.indexOf(r.status);if(idx===p.length-1){notify('当前流程已完成');return;}r.status=p[idx+1];r.owner=type==='rfis'?(r.status==='审查中'?'周工 · 设计单位':'张工 · RFI 经理'):type==='submittals'?'刘工 · 专业监理':r.owner;log(r,'状态更新为 '+r.status);}
function exportCSV(data,name){const keys=['id','title','status','owner','due','zone'];const csv='\ufeff'+[keys.join(','),...data.map(r=>keys.map(k=>'"'+String(r[k]||'').replace(/^[=+@-]/,"'$&").replace(/"/g,'""')+'"').join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('已生成本地 CSV 文件');}
function simple(title,body,primary='知道了'){dialog(title,body,primary,()=>notify('已查看演示流程'));}
const actions={
'sheet-layout':()=>{state.sheetLayout=state.sheetLayout==='list'?'grid':'list';render();},
'close-detail':()=>{state.selected=null;$('.build-drawer')?.remove();},reset:()=>{state.filter='全部状态';state.query='';state.zone='全部工点';render();},create:()=>create(),export:()=>exportCSV(list(),state.view+'施工记录'),advance,
'issue-rfi':()=>{const r=find(state.selected);if(r.rfi)navigateRecord(r.rfi);else create('rfis',r);},
'rfi-change':()=>{const r=find(state.selected);const c=changes.find(c=>c.source===r.id);if(c){state.budgetTab='changes';state.selected=null;location.hash='cost';render();detail(c,'cost');}else{changes.push({id:'PCO-'+String(changes.length+1).padStart(3,'0'),title:r.title+' · 潜在变更',status:'待评估',amount:0,source:r.id,owner:'孙工 · 商务部',zone:r.zone,desc:'尚未估价，需单独评估费用及工期影响。'});actions['rfi-change']();}},
'return-submittal':()=>{const r=find(state.selected);if(!$('#submittalResponse').value.trim()){notify('请填写退回原因');return;}r.response=$('#submittalResponse').value;r.status='退回修改';r.owner='施工分部 · 提交方';log(r,'退回修改：'+r.response);},
'complete-form':()=>{const r=find(state.selected);if(r.status==='已完成'){notify('该表单已完成');return;}if(r.items.some((t,i)=>!state.formAnswers[r.id+'-'+i]||state.formAnswers[r.id+'-'+i]==='未检查')){notify('请完成所有检查项');return;}if(r.items.some((t,i)=>state.formAnswers[r.id+'-'+i]==='不符合')&&!r.linkedIssue){notify('存在不符合项，请先创建关联问题');return;}r.status='已完成';log(r,'检查完成，不符合项通过关联问题继续跟踪');},
'form-issue':()=>{const r=find(state.selected);if(r.linkedIssue){navigateRecord(r.linkedIssue);return;}const failed=r.items.filter((t,i)=>state.formAnswers[r.id+'-'+i]==='不符合');if(!failed.length){notify('请先标记至少一个不符合项');return;}const id='ISS-'+String(rows.issues.length+1).padStart(3,'0');rows.issues.push({id,title:failed.join('、')+'待整改',type:'检查不符合项',zone:r.zone,status:'待处理',owner:r.owner,due:r.due,sheet:r.sheet,source:r.id,desc:'来自 '+r.title+'：'+failed.join('、')});r.linkedIssue=id;log(r,'已创建关联问题 '+id);notify('已创建 '+id+'，可从关联记录查看');},
'save-meeting':()=>{const r=find(state.selected);r.note=$('#meetingNote').value;log(r,'保存会议记录');notify('记录已保存在当前页面会话中');},operations:()=>{const a=LC.assets[state.selected];if(a)location.href=LC.opUrl(state.selected,a.facility);else LC.open();},
'sheet-create-issue':()=>{$('#cdeDialog').close();const s=sheets.find(s=>s[0]===state.sheet);create('issues',{title:'',zone:s[2],sheet:s[0],desc:'关联施工图纸 '+s[0]});},
help:()=>simple('Forma Build参考与演示说明','<p>按 Forma Build 的图纸、现场问题、表单、RFI、报审、进度及成本协作组织界面，并适配公路工点。</p><p>所有数据和图纸均为示例，编辑只保存在当前页面会话中。没有执行真实发布、通知、审批、资金或设备操作。</p><p>参考依据见项目中的《Forma Build参考与界面说明.md》。</p>'),
packages:()=>simple('报审包与规范章节',rows.submittals.map(r=>`<div class="build-dialog-row"><b>${r.package}</b><p>${r.spec} · ${r.id} · ${r.status}</p></div>`).join('')),
templates:()=>simple('现场表单模板','<div class="build-dialog-row"><b>质量验收</b><p>检查项目、验收结果、不符合项与关联问题</p></div><div class="build-dialog-row"><b>安全巡检</b><p>现场防护、临时用电、风险整改与复查记录</p></div><div class="build-dialog-row"><b>施工日报</b><p>天气、人员、机械、完成量与现场事项</p></div>'),
publish:()=>{const d=dialog('发布图纸 · 1 / 3',`<div id="publishStep"><div class="dropzone">选择文件 · PDF / RVT<br><small>使用本地图纸示例演示发布流程</small></div><label class="field">来源文件<input value="桥台施工发行图.pdf" readonly></label></div>`,'下一步');let step=1;$('#dialogConfirm').onclick=()=>{step++;if(step===2){$('#publishStep').innerHTML='<h3>2 / 3 · 图纸集与版本集</h3><label class="field">图纸集<select><option>合同段 T1 · 施工图</option></select></label><label class="field">版本集<input value="2026-09 施工发行"></label>'; }else if(step===3){$('#publishStep').innerHTML='<h3>3 / 3 · 复核图号与名称</h3><label class="field">图号<input value="S-101"></label><label class="field">图纸名称<input value="桥台一般构造及预埋件定位图"></label><p>正式产品支持 OCR 识别。本演示使用预填字段。</p>';$('#dialogConfirm').textContent='完成发布演示';}else{d.close();notify('发布流程演示完成，未上传真实文件');}};},
versions:()=>simple('版本集','<div class="build-dialog-row"><b>2026-09 施工发行</b><p>6 张图纸 · 最新版本 · 2026-09-10</p></div><div class="build-dialog-row"><b>2026-08 初次发行</b><p>历史版本 · 用于追溯</p></div>'),collections:()=>simple('图纸集','<p>合同段 T1 · 施工图</p><p>按桥梁、隧道机电、房建和电气专业筛选已发布图纸。</p>'),
'upload-files':()=>simple('上传项目文件','<div class="dropzone">将文件添加到当前施工文件夹</div><label class="field">版本说明<textarea placeholder="输入上传说明"></textarea></label>','完成上传演示'),
'import-schedule':()=>simple('导入进度计划','<div class="dropzone">Primavera P6 · Microsoft Project · Asta Powerproject</div><label class="field">计划版本<input value="09 月总进度计划 V4"></label><p>示例展示导入后的甘特图与事项关联，不解析真实计划文件。</p>','查看导入示例'),
'compare-schedule':()=>simple('计划版本比较','<div class="build-dialog-row"><b>V2 → V3</b><p>隧道通风设备安装：09-20 → 09-22<br>联合调试：09-21 → 09-23</p></div><p>原因：设备报审及到货安排调整。版本差异为示例记录。</p>'),
workplan:()=>simple('短期作业计划 · 未来两周',tasks.slice(0,4).map(t=>`<div class="build-dialog-row"><b>${t[1]}</b><p>${t[2]} · 已完成 ${t[5]}% · 关联 ${t[6]}</p></div>`).join('')),
'cost-help':()=>simple('成本口径','<p>修订预算 = 原始预算 + 已批准变更。</p><p>待评估潜在变更单列，不计入已批准预算；合同签约额与支付额分别展示。</p><p>所有金额均为示例万元，不形成真实计量或支付指令。</p>'),
'new-change':()=>simple('创建潜在变更','<label class="field">变更事项<input placeholder="描述变更范围"></label><label class="field">来源<select><option>RFI / 现场问题</option><option>合同指令</option></select></label><p>可从 RFI 详情创建与原始技术澄清关联的潜在变更。</p>'),
'report-export':()=>exportCSV(Object.values(rows).flat(),'施工项目摘要')
};
document.addEventListener('click',e=>{const b=e.target.closest('button,a,tr');if(!b)return;if(b.dataset.buildNav){state.selected=null;state.query='';state.filter='全部状态';state.tab='详情';}else if(b.dataset.home){if(b.dataset.home==='urgent'){go('reports');}else go(b.dataset.home);}else if(b.dataset.recordBuild){state.tab='详情';detail(find(b.dataset.recordBuild),state.view);}else if(b.dataset.ref){navigateRecord(b.dataset.ref);}else if(b.dataset.sheet){sheetViewer(b.dataset.sheet);}else if(b.dataset.detailTab){state.tab=b.dataset.detailTab;detail(find(state.selected),state.view);}else if(b.dataset.costTab){state.budgetTab=b.dataset.costTab;render();}else if(b.dataset.change){state.tab='详情';detail(find(b.dataset.change),'cost');}else if(b.dataset.task){const t=tasks.find(t=>t[0]===b.dataset.task);dialog(t[0]+' · '+t[1],`<p>${t[2]}</p><div class="build-dialog-row"><b>09-${t[3]} — 09-${t[4]}</b><p>完成比例 ${t[5]}% · 责任单位：施工分部</p></div><p>WBS：<a href="construction.html?wbs=${WBS.activityMap[t[0]]}#files">${WBS.activityMap[t[0]]} · 查看工作包资料 ↗</a></p><h3>关联事项</h3><button class="build-reference" id="taskRef">${t[6]} · ${find(t[6])?.title||''} ↗</button>`,'');$('#taskRef').onclick=()=>{$('#cdeDialog').close();navigateRecord(t[6]);};}else if(b.dataset.build){actions[b.dataset.build]?.();}});
document.addEventListener('change',e=>{if(e.target.dataset.answer)state.formAnswers[e.target.dataset.answer]=e.target.value;if(e.target.dataset.assetCheck){const r=find(state.selected);r.checks=$$('[data-asset-check]').map(c=>c.checked);}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){state.selected=null;$('.build-drawer')?.remove();}if(e.key==='Enter'&&e.target.matches('[data-record-build]'))e.target.click();});
$$('.header-tools [data-action="notifications"]').forEach(b=>{const old=b.dataset.action;delete b.dataset.action;b.dataset.build=old==='help'?'help':'home-notifications';});actions['home-notifications']=()=>simple('施工待办提醒',Object.values(rows).flat().filter(overdue).map(r=>`<div class="build-dialog-row"><b>${r.id} · ${esc(r.title)}</b><p>${esc(r.owner)} · 截止 ${esc(r.due)}</p></div>`).join('')||'<p>暂无逾期事项。</p>');
window.BUILD={state,rows,sheets,tasks,budgets,changes,render,list};window.addEventListener('hashchange',render);
LC.restoreBuild(rows,changes,state);
const requested=new URLSearchParams(location.search).get('record');
if(requested){const type=Object.keys(rows).find(k=>rows[k].some(r=>r.id===requested));if(type){state.selected=requested;history.replaceState(null,'','#'+type);render();}else if(sheets.some(s=>s[0]===requested)){history.replaceState(null,'','#sheets');render();sheetViewer(requested);}else{render();notify('未找到对应施工记录，请核对关联编号');}}else render();
const activity=new URLSearchParams(location.search).get('activity');if(activity&&tasks.some(t=>t[0]===activity)){history.replaceState(null,'','#schedule');render();$('#constructionWorkspace [data-task="'+activity+'"]')?.click();}
})();
