window.DESIGN_DATA=(()=>{
'use strict';const key='design-road-v1';
const seed={params:{name:'K线 · XX高速主线',start:10000,end:15000,lanes:4,laneWidth:3.75,shoulder:4.5,median:2,spans:4,spanLength:30,pierHeight:16,tunnelLength:800,tunnelRadius:6,lining:.6,curve:18},coordinate:{system:'CGCS2000',projection:'Gauss-Kruger',zone:'3° 分带',meridian:111,east:500000,north:0,elevation:0},models:{},issues:[],shares:[]};let saved;try{saved=JSON.parse(sessionStorage.getItem(key));}catch{}const state={...seed,...saved,params:{...seed.params,...saved?.params},coordinate:{...seed.coordinate,...saved?.coordinate}};
state.uploads=state.uploads||[];state.deleted=state.deleted||[];
state.fileMeta=state.fileMeta||{};state.customFolders=state.customFolders||[];state.fileVersions=state.fileVersions||{};
state.reviews=state.reviews||[];state.activities=state.activities||[];state.issues=state.issues||[];state.shares=state.shares||[];
const clone=v=>JSON.parse(JSON.stringify(v)),now=()=>new Date().toISOString(),uid=()=>crypto.randomUUID();
const groups=[{id:'road',name:'路',title:'道路工程',place:'K10+000 — K12+000'},{id:'bridge',name:'桥',title:'桥梁工程',place:'K12+350 大桥'},{id:'tunnel',name:'隧',title:'隧道工程',place:'K14+000 隧道'}];
function baseFiles(){return groups.flatMap(g=>[{id:g.id+'-model',code:{road:'DES-RD-001',bridge:'DES-BR-001',tunnel:'DES-TN-001'}[g.id],name:g.title+'设计模型',format:'MODEL',kind:'文件',group:g.id,version:state.models[g.id]?.version||'V1',status:'设计中',source:state.models[g.id]?'参数化生成 · 前端示例':'预置设计模型',updated:state.models[g.id]?.updated||'2026-09-14',owner:'设计一组'}, {id:g.id+'-drawing',code:'DES-'+g.id.toUpperCase()+'-002',name:{road:'路线平纵面与标准横断面图',bridge:'桥梁总体布置与桥墩构造图',tunnel:'隧道总体布置与衬砌断面图'}[g.id],format:'PDF',kind:'文件',group:g.id,version:'V2',status:'待校审',source:'设计图纸示例',updated:'2026-09-14',owner:'专业设计组'}, {id:g.id+'-data',code:'DES-'+g.id.toUpperCase()+'-003',name:{road:'K线 EI 设计数据包',bridge:'桥梁跨径与结构参数表',tunnel:'隧道洞身与断面参数表'}[g.id],format:g.id==='road'?'EI':'XLSX',kind:'文件',group:g.id,version:'V1',status:'设计中',source:'结构化设计数据示例',updated:'2026-09-14',owner:'专业设计组'}]);}
const folders=[
 ['road-route','路线设计','road'],['road-pavement','路基路面','road'],['road-drainage','排水与防护','road'],['road-models','三维模型','road'],
 ['bridge-general','总体布置','bridge'],['bridge-upper','上部结构','bridge'],['bridge-lower','下部结构','bridge'],['bridge-models','三维模型','bridge'],
 ['tunnel-general','总体设计','tunnel'],['tunnel-lining','洞身与衬砌','tunnel'],['tunnel-portal','洞口工程','tunnel'],['tunnel-models','三维模型','tunnel']
].map(([id,name,group])=>({id,name,group,parent:group,code:'DIR-'+id.toUpperCase(),kind:'文件夹',version:'目录快照'})).concat(state.customFolders);
const extra=[
 ['road-route','路线平面设计图','PDF'],['road-route','路线纵断面设计图','PDF'],['road-pavement','标准横断面设计图','PDF'],['road-pavement','路基土石方数量表','XLSX'],['road-pavement','路面结构设计说明','PDF'],['road-drainage','边沟与截水沟设计图','PDF'],['road-drainage','边坡防护设计图','PDF'],
 ['bridge-general','桥梁设计说明','PDF'],['bridge-upper','预应力箱梁一般构造图','PDF'],['bridge-upper','桥面铺装与防撞护栏设计图','PDF'],['bridge-lower','桥墩与盖梁构造图','PDF'],['bridge-lower','承台与桩基础设计图','PDF'],
 ['tunnel-general','隧道纵断面设计图','PDF'],['tunnel-lining','复合式衬砌设计图','PDF'],['tunnel-lining','初期支护参数表','XLSX'],['tunnel-portal','洞门一般构造图','PDF'],['tunnel-portal','洞口边仰坡防护设计图','PDF']
];
const eiSamples=['ICD','SQX','DMX','TXT','HDX','GZX'].map((format,i)=>({id:'ei-sample-'+format.toLowerCase(),code:'EI-K-'+String(i+1).padStart(3,'0'),name:'K主线示例.'+format,format,kind:'文件',group:'road',parent:'road-route',version:'V1',status:'示例数据',owner:'路线设计组',source:'预置 EI 示例索引',example:true,size:2048+i*1024,updated:'2026-09-14'}));
function rawFiles(){return [...baseFiles().map(f=>({...f,parent:f.format==='MODEL'?f.group+'-models':{road:'road-route',bridge:'bridge-general',tunnel:'tunnel-general'}[f.group]})),...extra.map(([parent,name,format],i)=>({id:'design-detail-'+i,code:'DES-D-'+String(i+1).padStart(3,'0'),name,format,kind:'文件',group:folders.find(f=>f.id===parent).group,parent,version:'V1',status:'设计中',owner:'专业设计组',source:'专业设计资料示例',updated:'2026-09-14'})),...eiSamples,...state.uploads];}
function allFiles(){return rawFiles().map(f=>{const meta=state.fileMeta[f.id]||{};const file={...f,...meta};if(f.format==='MODEL'&&state.models[f.group]){file.version=state.models[f.group].version;if(meta.statusVersion&&meta.statusVersion!==file.version){file.status='设计中';file.reviewStatus='未提交';}}return file;});}
function files(){return allFiles().filter(f=>!state.deleted.includes(f.id));}
function folderIds(id){const out=[id];for(let i=0;i<out.length;i++)for(const f of folders)if(f.parent===out[i]&&!out.includes(f.id))out.push(f.id);return out;}
function folderFiles(id){const ids=folderIds(id);return files().filter(f=>id==='root'||ids.includes(f.parent)||f.group===id);}
function children(id){return [...(id==='root'?groups.map(g=>object(g.id)):folders.filter(f=>f.parent===id)),...files().filter(f=>f.parent===id)];}
function path(id){const parts=[],seen=new Set();let o=object(id);if(!o)return '';while(o&&!seen.has(o.id)){seen.add(o.id);parts.unshift(o.name);o=o.id==='root'?null:object(o.parent||((o.group&&o.group!==o.id)?o.group:'root'));}return parts.join(' / ');}
function components(){const cs=[['RD-PAVE','主线路面','road','路面结构'],['RD-MEDIAN','中央分隔带','road','道路附属'],['BR-DECK','桥梁上部梁体','bridge','上部结构'],['TN-LINING','隧道衬砌','tunnel','衬砌结构'],['TN-PAVE','隧道路面','tunnel','路面结构'],['TN-PORTAL','隧道洞门','tunnel','洞门结构']];const n=(state.models.bridge?.params||state.params).spans;for(let i=1;i<n;i++)cs.push(['BR-PIER-'+i,'P'+i+'号桥墩','bridge','下部结构']);return cs.filter(c=>files().some(f=>f.id===c[2]+'-model')).map(([id,name,group,type])=>({id,code:id,name,group,type,kind:'构件',file:group+'-model',version:files().find(f=>f.id===group+'-model')?.version||'V1',status:'设计中'}));}
function object(id){if(id==='root')return{id:'root',code:'DESIGN-ROOT',name:'设计成果',kind:'文件夹',version:'目录快照'};const g=groups.find(g=>g.id===id);if(g)return{...g,code:'DIR-'+id.toUpperCase(),kind:'文件夹',group:id,parent:'root',version:'目录快照'};return folders.find(f=>f.id===id)||files().find(f=>f.id===id||f.code===id)||components().find(c=>c.id===id);}
function snapshot(ids){const selected=[...new Set((Array.isArray(ids)?ids:[ids]).filter(Boolean))].map(object).filter(Boolean);if(!selected.length)return null;const list=selected.flatMap(o=>o.kind==='文件夹'?folderFiles(o.id):o.kind==='构件'?[object(o.file)]:[o]).filter(Boolean), unique=[...new Map(list.map(f=>[f.id,f])).values()];const target=selected.length===1?selected[0]:{id:selected[0].id,name:selected.length+' 个已选对象',code:'MULTI',version:'多个版本',kind:'文件集'};return clone({...target,path:selected.length===1?path(target.id):'设计成果',objects:selected.map(o=>({id:o.id,name:o.name,kind:o.kind,code:o.code,version:o.version})),files:unique.map(f=>({...f,path:path(f.id)})),created:now()});}
function log(action,details={}){const item={id:'ACT-'+uid(),at:now(),actor:'张工',action,...clone(details)};state.activities.unshift(item);return item;}
function validateFolder(id){const f=object(id);if(!f||f.kind!=='文件夹')throw Error('请选择有效文件夹');return f;}
function uniqueName(name,parent,except){let next=name,n=1;while(files().some(f=>f.parent===parent&&f.name===next&&f.id!==except)){const i=name.lastIndexOf('.');next=i>0?name.slice(0,i)+' ('+(n++)+')'+name.slice(i):name+' ('+(n++)+')';}return next;}
function addFiles(list,parent){const folder=validateFolder(parent);const input=Array.from(list);if(!input.length)throw Error('请选择文件');const out=input.map(file=>{if(!file.name||file.size===0)throw Error('不能上传空文件');return{id:'upload-'+uid(),code:'UP-'+uid().slice(0,8).toUpperCase(),name:file.name,format:file.name.split('.').pop().toUpperCase(),kind:'文件',group:folder.group||'project',parent,version:'V1',status:'已上传',reviewStatus:'未提交',owner:'张工',source:'成果资料库上传',size:file.size,updated:now().slice(0,10)};});for(const f of out){f.name=uniqueName(f.name,parent);state.uploads.push(f);}log('上传文件',{fileIds:out.map(f=>f.id),name:out.map(f=>f.name).join('、'),version:'V1'});save();return out;}
function updateFile(id,patch){const f=files().find(x=>x.id===id);if(!f)throw Error('文件不存在或已删除');const allowed=['name','status','reviewStatus','owner','description','tags','parent','group','size','updated','statusVersion'];const next=Object.fromEntries(Object.entries(patch).filter(([k])=>allowed.includes(k)));if(next.name!==undefined){next.name=String(next.name).trim();if(!next.name)throw Error('文件名称不能为空');if(files().some(x=>x.id!==id&&x.parent===(next.parent||f.parent)&&x.name===next.name))throw Error('此文件夹已存在同名文件');}if(next.parent){const parent=validateFolder(next.parent);next.group=parent.group||'project';}state.fileMeta[id]={...state.fileMeta[id],...next};log('更新文件属性',{fileIds:[id],name:next.name||f.name,version:f.version});save();return object(id);}
function versions(id){const f=allFiles().find(x=>x.id===id);const saved=state.fileVersions[id]||[];return clone((f?[f,...saved.filter(v=>v.version!==f.version)]:saved).sort((a,b)=>(parseInt(b.version.slice(1))||0)-(parseInt(a.version.slice(1))||0)));}
function newVersion(id,file){const f=files().find(x=>x.id===id);if(!f)throw Error('文件不存在或已删除');if(!file?.name||file.size===0)throw Error('请选择非空版本文件');const format=file.name.split('.').pop().toUpperCase();if(format!==f.format&&!(f.format==='MODEL'&&['IFC','RVT','GLB','MODEL'].includes(format)))throw Error('新版本文件类型须与原文件一致');rememberVersions();const version='V'+(Math.max(...versions(id).map(v=>parseInt(v.version.slice(1))||1))+1);state.fileMeta[id]={...state.fileMeta[id],version,size:file.size,status:'已上传',reviewStatus:'未提交',statusVersion:version,updated:now().slice(0,10)};if(f.format==='MODEL'){state.models[f.group]={...state.models[f.group],version,updated:now().slice(0,10)};}log('上传新版本',{fileIds:[id],name:f.name,version,previousVersion:f.version});save();return object(id);}
function addFolder(name,parent='root'){const p=validateFolder(parent);name=String(name||'').trim();if(!name)throw Error('请输入文件夹名称');if(children(parent).some(f=>f.kind==='文件夹'&&f.name===name))throw Error('此位置已存在同名文件夹');const f={id:'folder-'+uid(),name,parent,group:p.group||null,code:'DIR-'+uid().slice(0,8).toUpperCase(),kind:'文件夹',version:'目录快照'};state.customFolders.push(f);folders.push(f);log('新建文件夹',{name,path:path(f.id)});save();return f;}
function moveFiles(ids,parent){const p=validateFolder(parent),selected=[...new Set(ids)].map(id=>files().find(f=>f.id===id));if(selected.some(f=>!f))throw Error('所选文件包含已删除的文件');if(new Set(selected.map(f=>f.name)).size!==selected.length)throw Error('所选文件包含同名文件，请分开移动');for(const f of selected)if(files().some(x=>x.id!==f.id&&x.parent===parent&&x.name===f.name))throw Error('目标文件夹已有同名文件：'+f.name);for(const f of selected)state.fileMeta[f.id]={...state.fileMeta[f.id],parent,group:p.group||'project'};log('移动文件',{fileIds:selected.map(f=>f.id),name:selected.map(f=>f.name).join('、'),destination:path(parent)});save();return selected.map(f=>object(f.id));}
function copyFiles(ids,parent){const p=validateFolder(parent),selected=[...new Set(ids)].map(id=>files().find(f=>f.id===id));if(selected.some(f=>!f))throw Error('所选文件包含已删除的文件');const out=selected.map(f=>{const c={...clone(f),id:'copy-'+uid(),code:'CP-'+uid().slice(0,8).toUpperCase(),name:uniqueName(f.name,parent),parent,group:p.group||'project',version:'V1',status:'已上传',reviewStatus:'未提交',source:'复制自 '+f.code+' · '+f.version,updated:now().slice(0,10)};state.uploads.push(c);return c;});log('复制文件',{fileIds:out.map(f=>f.id),name:out.map(f=>f.name).join('、'),destination:path(parent)});save();return out;}
function removeFiles(ids){const fs=files().filter(f=>ids.includes(f.id));for(const f of fs)if(!state.deleted.includes(f.id))state.deleted.push(f.id);if(fs.length)log('删除文件',{fileIds:fs.map(f=>f.id),name:fs.map(f=>f.name).join('、')});save();return fs.length;}
function removeFile(id){return removeFiles([id]);}
function restoreFiles(ids){const fs=allFiles().filter(f=>ids.includes(f.id)&&state.deleted.includes(f.id));for(const f of fs){if(files().some(x=>x.parent===f.parent&&x.name===f.name)){state.fileMeta[f.id]={...state.fileMeta[f.id],name:uniqueName(f.name,f.parent)};}state.deleted=state.deleted.filter(x=>x!==f.id);}if(fs.length)log('恢复文件',{fileIds:fs.map(f=>f.id),name:fs.map(f=>f.name).join('、')});save();return fs.length;}
function restoreFile(id){return restoreFiles([id]);}
function history(id){return clone(state.activities.filter(a=>a.fileIds?.includes(id)));}
function rememberVersions(){for(const f of allFiles()){const list=state.fileVersions[f.id]||(state.fileVersions[f.id]=[]),i=list.findIndex(v=>v.version===f.version);if(i<0)list.unshift(clone(f));else list[i]={...list[i],...clone(f)};}}
function save(){rememberVersions();try{sessionStorage.setItem(key,JSON.stringify(state));}catch{}document.dispatchEvent(new CustomEvent('design-data-changed'));}
function href(o){return (o.kind==='构件'?'gis.html?object=':'file-management.html?selected=')+encodeURIComponent(o.id);}
function nextId(prefix,list){return prefix+String(Math.max(0,...list.map(r=>parseInt(r.id.split('-').pop())||0))+1).padStart(3,'0');}
function createRecord(type,ids,data={},frozen){type=type==='share'?'transmittal':type;const t=frozen?clone(frozen):snapshot(ids);if(!t?.files.length)throw Error('请选择至少一份有效文件');if(t.files.some(f=>!object(f.id)))throw Error('所选文件已删除，请重新选择文件');if(!String(data.title||'').trim()||!data.person)throw Error('请填写标题与责任人 / 接收方');if(type==='issue'&&!String(data.description||'').trim())throw Error('请填写问题说明');if(type!=='transmittal'&&!data.due)throw Error('请选择截止日期');const list=type==='issue'?state.issues:type==='review'?state.reviews:state.shares;const r={id:nextId(type==='issue'?'D-ISS-':type==='review'?'REV-':'D-TR-',list),type,title:data.title.trim(),description:data.description||'',person:data.person,due:data.due||'',created:now(),updated:now(),status:type==='issue'?'未解决':type==='review'?'进行中':'已发送',target:t,history:[],...type==='review'?{workflow:data.workflow||'两步审批',step:1,reviewer:data.person,approver:data.approver||'项目负责人',fileDecisions:{}}:type==='transmittal'?{recipientStatus:'未查看',sourceReview:data.sourceReview||null}:{} };list.unshift(r);r.history.push({at:now(),actor:'张工',action:type==='issue'?'创建问题':type==='review'?'提交审阅':'创建分发'});if(type==='review')for(const f of t.files){const cur=object(f.id);if(cur&&cur.version===f.version)state.fileMeta[f.id]={...state.fileMeta[f.id],status:'审阅中',reviewStatus:'审阅中',statusVersion:f.version};}log(r.history[0].action,{recordId:r.id,fileIds:t.files.map(f=>f.id),name:r.title});save();return r;}
function updateIssue(id,status,note=''){const r=state.issues.find(x=>x.id===id);if(!r)throw Error('问题不存在');if(!['草稿','未解决','处理中','已回答','已关闭','待处理'].includes(status))throw Error('无效的问题状态');r.status=status;r.updated=now();r.history=r.history||[];r.history.push({at:now(),actor:'张工',action:'状态变更为 '+status,note});log('更新问题',{recordId:id,fileIds:r.target.files.map(f=>f.id),name:r.title,status});save();return r;}
function reviewAction(id,action,note='',decisions){const r=state.reviews.find(x=>x.id===id);if(!r)throw Error('审阅不存在');if(r.status==='已关闭')throw Error('审阅已结束');if(!['submit','approve','reject'].includes(action))throw Error('无效的审阅操作');if(action==='approve'&&(r.step||1)===1&&r.workflow!=='单步审批')throw Error('请先完成审阅，再进行最终批准');if(action==='submit'&&((r.step||1)!==1||r.workflow==='单步审批'))throw Error('当前步骤无需提交审阅');if(decisions&&Object.values(decisions).some(v=>!['已批准','已退回','批准并附注'].includes(v)))throw Error('无效的文件审阅结论');r.history=r.history||[];if(action==='submit'){r.step=2;r.status='进行中';r.person=r.approver||'项目负责人';}else{r.status='已关闭';r.result=action==='approve'?'已批准':'已退回';r.closed=now();r.fileDecisions={};for(const f of r.target.files){const decision=decisions?.[f.id]||(action==='approve'?'已批准':'已退回');if(!['已批准','已退回','批准并附注'].includes(decision))throw Error('无效的文件审阅结论');r.fileDecisions[f.id]=decision;const list=state.fileVersions[f.id]||[];const v=list.find(v=>v.version===f.version);if(v){v.reviewStatus=decision;v.status=decision;}const cur=allFiles().find(x=>x.id===f.id);if(cur&&cur.version===f.version)state.fileMeta[f.id]={...state.fileMeta[f.id],status:decision,reviewStatus:decision,statusVersion:f.version};}}if(action==='approve'&&Object.values(r.fileDecisions).includes('已退回'))r.result=Object.values(r.fileDecisions).every(s=>s==='已退回')?'已退回':'部分退回';r.updated=now();const label=action==='submit'?'完成审阅，提交批准':action==='approve'?'完成批准':'退回修改';r.history.push({at:now(),actor:'张工',action:label,note});log(label,{recordId:id,fileIds:r.target.files.map(f=>f.id),name:r.title});save();return r;}
function receiveTransmittal(id){const r=state.shares.find(x=>x.id===id);if(!r)throw Error('分发不存在');if(r.status==='作废')throw Error('此分发已作废');if(r.recipientStatus==='已确认')return r;r.recipientStatus='已确认';r.status='已发送';r.updated=now();r.history=r.history||[];r.history.push({at:now(),actor:r.person,action:'确认接收'});log('确认接收',{recordId:id,fileIds:r.target.files.map(f=>f.id),name:r.title});save();return r;}
function voidTransmittal(id,note){const r=state.shares.find(x=>x.id===id);if(!r)throw Error('分发不存在');if(r.status==='作废')throw Error('此分发已作废');if(!String(note||'').trim())throw Error('请填写作废原因');r.status='作废';r.updated=now();r.history=r.history||[];r.history.push({at:now(),actor:'张工',action:'分发作废',note});log('分发作废',{recordId:id,fileIds:r.target.files.map(f=>f.id),name:r.title});save();return r;}
if(!state.collaborationVersion){
 const definitions=[['D-ISS-001','主线路面结构厚度复核','RD-PAVE','路线设计组','未解决','核对 K10+000 — K12+000 路面结构与标准横断面。'],['D-ISS-002','桥墩构造与总体布置一致性','BR-PIER-1','桥梁设计组','处理中','复核 P1 桥墩中心线与总体布置图。'],['D-ISS-003','隧道衬砌断面确认','TN-LINING','隧道设计组','已关闭','设计复核完成，衬砌断面一致。']];
 if(!state.issues.length)for(const [id,title,target,person,status,description]of definitions){const t=snapshot(target);if(t?.files.length)state.issues.push({id,type:'issue',title,person,status,description,target:t,created:'2026-09-18T09:00:00.000Z',due:'2026-09-28',history:[{at:'2026-09-18T09:00:00.000Z',actor:'张工',action:'创建问题'}]});}
 if(!state.reviews.length){const t=snapshot(['road-drawing','bridge-drawing']);if(t?.files.length)state.reviews.push({id:'REV-001',type:'review',title:'道路及桥梁设计图纸审阅',person:'专业设计组',reviewer:'专业设计组',approver:'项目负责人',status:'进行中',step:1,workflow:'两步审批',description:'核对设计图纸及跨专业接口。',due:'2026-09-28',created:'2026-09-19T08:30:00.000Z',target:t,history:[{at:'2026-09-19T08:30:00.000Z',actor:'张工',action:'提交审阅'}],fileDecisions:{}});}
 if(!state.shares.length){const t=snapshot('tunnel-drawing');if(t?.files.length)state.shares.push({id:'D-TR-001',type:'transmittal',title:'隧道总体布置图 · 设计协调',person:'项目负责人',description:'供专业协调核查。',status:'已发送',recipientStatus:'未查看',created:'2026-09-19T10:00:00.000Z',target:t,history:[{at:'2026-09-19T10:00:00.000Z',actor:'张工',action:'创建分发'}]});}
 for(const r of [...state.issues,...state.reviews,...state.shares])if(!state.activities.some(a=>a.recordId===r.id))state.activities.push({id:'ACT-'+uid(),at:r.created||'2026-09-18T09:00:00.000Z',actor:'张工',action:r.id.startsWith('REV')?'提交审阅':r.id.startsWith('D-TR')?'创建分发':'创建问题',recordId:r.id,fileIds:r.target?.files?.map(f=>f.id)||[],name:r.title});
 for(const r of state.reviews.filter(r=>r.status==='进行中'))for(const f of r.target.files){const current=object(f.id);if(current?.version===f.version)state.fileMeta[f.id]={...state.fileMeta[f.id],status:'审阅中',reviewStatus:'审阅中',statusVersion:f.version};}
 state.collaborationVersion=2;save();
}
for(const r of state.reviews){if(['已批准','已退回'].includes(r.status)){r.result=r.status;r.status='已关闭';}else if(['待批准','审阅中'].includes(r.status)){if(r.status==='待批准')r.step=2;r.status='进行中';}}
for(const r of state.issues){if(r.status==='待处理')r.status='未解决';r.type='issue';r.history=r.history||[];}for(const r of state.shares){if(r.status==='待确认'){r.status='已发送';r.recipientStatus=r.recipientStatus||'未查看';}r.type='transmittal';r.history=r.history||[];}
rememberVersions();
return{state,groups,folders,addFiles,updateFile,newVersion,addFolder,moveFiles,copyFiles,removeFile,removeFiles,restoreFile,restoreFiles,allFiles,folderFiles,children,path,files,components,object,snapshot,save,href,history,versions,createRecord,updateIssue,reviewAction,receiveTransmittal,voidTransmittal,log};
})();
