/* Local Three.js scene. Parametric design visualization, not an EI geometry parser. */
window.DesignScene=class{
constructor(canvas,options={}){this.canvas=canvas;this.options=options;this.selected=null;this._filter='all';this.angle=.84;this.pitch=.68;this.distance=230;this.target=new THREE.Vector3(-35,4,0);this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#dbe9ef');this.scene.fog=new THREE.Fog('#dbe9ef',600,1100);this.camera=new THREE.PerspectiveCamera(40,1,.1,1800);this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=.96;this.scene.add(new THREE.HemisphereLight(0xcfe7ff,0x526343,1.65));const sun=new THREE.DirectionalLight(0xfff6df,2.5);sun.position.set(-100,210,70);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-260,right:260,top:170,bottom:-170,near:1,far:600});sun.shadow.bias=-.0002;sun.shadow.normalBias=.25;this.scene.add(sun);this.root=new THREE.Group();this.scene.add(this.root);this.ray=new THREE.Raycaster();this.rebuild();this.resize=new ResizeObserver(()=>this.draw());this.resize.observe(canvas);canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{this.drag={x:e.clientX,y:e.clientY,px:e.clientX,py:e.clientY,pan:e.shiftKey||e.button===2};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!this.drag)return;const dx=e.clientX-this.drag.px,dy=e.clientY-this.drag.py;this.drag.px=e.clientX;this.drag.py=e.clientY;if(this.drag.pan){this.target.x-=dx*this.distance*.0015*Math.cos(this.angle);this.target.z+=dx*this.distance*.0015*Math.sin(this.angle);this.target.y+=dy*this.distance*.001;}else{this.angle-=dx*.007;this.pitch=Math.max(.12,Math.min(1.5,this.pitch+dy*.006));}this.draw();};canvas.onpointerup=e=>{if(this.drag&&Math.hypot(e.clientX-this.drag.x,e.clientY-this.drag.y)<5){const r=canvas.getBoundingClientRect();this.ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),this.camera);const hit=this.ray.intersectObjects(this.root.children,true).find(h=>h.object.visible);this.setSelected(hit?.object.userData.id||null);this.options.onSelect?.(this.selected);}this.drag=null;};canvas.onpointercancel=()=>this.drag=null;canvas.onwheel=e=>{e.preventDefault();this.distance=Math.max(35,Math.min(650,this.distance*Math.exp(e.deltaY*.001)));this.draw();};}
mat(color,extra={}){return new THREE.MeshStandardMaterial({color,roughness:.86,metalness:0,...extra});}
mesh(geo,mat,id,group){const m=new THREE.Mesh(geo,mat.clone());m.userData={id,group};m.castShadow=group!=='terrain';m.receiveShadow=true;this.root.add(m);return m;}
box(x,y,z,w,h,d,mat,id,group){const m=this.mesh(new THREE.BoxGeometry(w,h,d),mat,id,group);m.position.set(x,y,z);return m;}
texture(){const c=document.createElement('canvas');c.width=512;c.height=512;const ctx=c.getContext('2d');ctx.fillStyle='#353d41';ctx.fillRect(0,0,512,512);let seed=7;for(let i=0;i<35000;i++){seed=(seed*16807)%2147483647;const x=seed%512;seed=(seed*16807)%2147483647;ctx.fillStyle=i%2?'#ffffff12':'#00000012';ctx.fillRect(x,seed%512,1,1);}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(18,1);t.colorSpace=THREE.SRGBColorSpace;return t;}
groundTexture(){const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d');ctx.fillStyle='#afb58b';ctx.fillRect(0,0,512,512);let seed=19;for(let i=0;i<16000;i++){seed=seed*16807%2147483647;const x=seed%512;seed=seed*16807%2147483647;ctx.fillStyle=['#647c4840','#d1bf9940','#556d3930','#eee1b030'][i%4];ctx.fillRect(x,seed%512,2+i%4,2+i%3);}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(12,8);t.colorSpace=THREE.SRGBColorSpace;return t;}
rebuild(params){this.root.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose();}});this.root.clear();const p={...DESIGN_DATA.state.params,...params};this.params=p;const road=p,cy=x=>Math.sin(Math.min(x,be)/115)*Number(p.curve||10);this.cy=cy;const lanes=Number(p.lanes||4),lw=Number(p.laneWidth||3.75),median=Number(p.median||2),shoulder=Number(p.shoulder||3.75),w=lanes*lw+median+shoulder*2;this.width=w;const bl=Math.max(40,Math.min(170,p.spans*p.spanLength)),bs=-bl/2,be=bl/2,h=Number(p.pierHeight||16);this.bounds={road:[-205,bs],bridge:[bs,be],tunnel:[be+16,be+100]};const asphalt=this.mat('#ffffff',{map:this.texture()}),line=this.mat('#f5f3db'),grass=this.mat('#668346'),concrete=this.mat('#bdc3bd'),dark=this.mat('#89928d'),rail=this.mat('#bdc9ce',{metalness:.65,roughness:.4});const verts=[],colors=[];const land=new THREE.PlaneGeometry(1000,650,100,65);land.rotateX(-Math.PI/2);const pa=land.attributes.position;for(let i=0;i<pa.count;i++){const x=pa.getX(i),z=pa.getZ(i);let y=-3+Math.sin(x*.026)*Math.cos(z*.033)*2;const lateral=Math.abs(z-cy(x));if(lateral>35)y+=Math.max(0,lateral-35)*.13+Math.sin(x*.013+z*.023)*4;pa.setY(i,y);const col=new THREE.Color().setHSL(.22+Math.sin(x*.04+z*.01)*.015,.16,.36+Math.sin(x*.05)*Math.cos(z*.045)*.055);colors.push(col.r,col.g,col.b);}land.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));land.computeVertexNormals();const groundMap=this.groundTexture();this.mesh(land,this.mat('#ffffff',{vertexColors:true,map:groundMap}),null,'terrain');
// Continuous deck, shoulders, edge lines and lane separators follow the route.
const strip=(a,b,z1,z2,y,mat,id,g)=>{const vs=[],uv=[],ix=[],n=Math.ceil((b-a)/3);for(let i=0;i<=n;i++){const x=a+(b-a)*i/n;vs.push(x,y,cy(x)+z1,x,y,cy(x)+z2);uv.push(i/n,0,i/n,1);if(i<n){const k=i*2;ix.push(k,k+1,k+2,k+1,k+3,k+2);}}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vs,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));geo.setIndex(ix);geo.computeVertexNormals();return this.mesh(geo,mat,id,g);};
for(const [a,b,g,id] of [[-205,bs,'road','RD-PAVE'],[bs,be,'bridge','BR-DECK'],[be,be+110,'tunnel','TN-PAVE']]){strip(a,b,-w/2,w/2,h,asphalt,id,g);if(g!=='tunnel')strip(a,b,-median/2,median/2,h+.16,grass,g==='road'?'RD-MEDIAN':id,g);const laneMedian=g==='tunnel'?Math.max(median,2*(Math.max(lanes/2*lw/2+1.8,Number(p.tunnelRadius))+.8-lanes*lw/4)):median;for(const side of [-1,1]){const inner=side*(laneMedian/2+.2),outer=side*(laneMedian/2+lanes/2*lw);strip(a,b,inner-.075,inner+.075,h+.025,line,id,g);strip(a,b,outer-.1,outer+.1,h+.03,line,id,g);for(let k=1;k<lanes/2;k++){const zz=side*(laneMedian/2+k*lw);for(let x=a;x<b;x+=10)strip(x,Math.min(x+5,b),zz-.085,zz+.085,h+.035,line,id,g);}if(g!=='tunnel'){for(let x=a;x<b;x+=4){const m=this.box(x,h+1,cy(x)+side*(w/2-.4),4,.32,.16,rail,id,g);m.rotation.y=-Math.atan(Math.cos(x/115)*p.curve/115);if(Math.round(x)%8<4)this.box(x,h+.5,cy(x)+side*(w/2-.4),.12,1,.12,rail,id,g);}}}
if(g==='road'){for(let x=a;x<b;x+=5){this.box(x,h-1.5,cy(x),5,2.5,w+1,dark,id,g);for(const side of [-1,1]){const geo=new THREE.BufferGeometry();const z=cy(x)+side*w/2,zz=z+side*(h+3)*1.3,dz=cy(x+5)-cy(x);geo.setAttribute('position',new THREE.Float32BufferAttribute([x,h-1,z,x+5,h-1,z+dz,x,-2,zz,x+5,h-1,z+dz,x+5,-2,zz+dz,x,-2,zz],3));geo.computeVertexNormals();this.mesh(geo,this.mat('#798d61',{side:THREE.DoubleSide}),id,g).receiveShadow=false;}}}}
// Box girder with visible beam depth, caps, columns and foundations.
for(let x=bs;x<be;x+=5)this.box(x,h-1.45,cy(x),5,2.4,w-.5,concrete,'BR-DECK','bridge');for(let i=1;i<p.spans;i++){const spanValues=p.spanLengths||Array(p.spans).fill(p.spanLength);const x=bs+bl*spanValues.slice(0,i).reduce((a,b)=>a+b,0)/spanValues.reduce((a,b)=>a+b,0),id='BR-PIER-'+i;this.box(x,-1,cy(x),7,2.5,w*.85,concrete,id,'bridge');const pierCount=p.pierType==='独柱墩'?1:2;for(let k=0;k<pierCount;k++){const zz=cy(x)+(pierCount===1?0:(k-.5)*w*.6);const m=this.mesh(new THREE.CylinderGeometry(1.15,1.35,h-3,20),concrete,id,'bridge');m.position.set(x,(h-3)/2,zz);}this.box(x,h-3,cy(x),4,2,w*.85,concrete,id,'bridge');}
// Twin tunnel bores: front portals and segment rings, with a cutaway roof option.
const tx=be+20,tl=Math.min(95,Math.max(35,p.tunnelLength/10)),radius=Math.max(lanes/2*lw/2+1.8,Number(p.tunnelRadius||6)),centers=[-(radius+.8),radius+.8];this.tunnelStart=tx;
for(const zoff of centers){const shape=new THREE.Shape();const outer=radius+Number(p.lining||.6);shape.moveTo(-outer,0);shape.lineTo(-outer,3);shape.absarc(0,3,outer,Math.PI,0,true);shape.lineTo(outer,0);shape.lineTo(radius,0);shape.lineTo(radius,3);shape.absarc(0,3,radius,0,Math.PI,false);shape.lineTo(-radius,0);shape.closePath();const geo=new THREE.ExtrudeGeometry(shape,{depth:tl,bevelEnabled:false,curveSegments:32});geo.rotateY(Math.PI/2);const m=this.mesh(geo,this.mat('#b9bcb0',{side:THREE.DoubleSide}),'TN-LINING','tunnel');m.position.set(tx,h,cy(tx)+zoff);this.tunnelMesh=m;const portal=new THREE.ExtrudeGeometry(shape,{depth:1.7,bevelEnabled:true,bevelSize:.12,bevelThickness:.12,bevelSegments:1});portal.rotateY(Math.PI/2);const pm=this.mesh(portal,this.mat('#d2d0bf'),'TN-PORTAL','tunnel');pm.position.set(tx-.8,h,cy(tx)+zoff);for(let x=tx+5;x<tx+tl;x+=10){for(const side of [-1,1])this.box(x,h+3.4,cy(tx)+zoff+side*(radius-.25),.8,.2,.2,this.mat('#fff6c3',{emissive:'#c6aa51',emissiveIntensity:.7}),'TN-LINING','tunnel');}}
// Hills around the tunnel give portal scale, while retaining a clear front opening.
const mountainShape=new THREE.Shape();mountainShape.moveTo(-85,-25);mountainShape.lineTo(-85,-3);for(let z=-80;z<=80;z+=8){const yy=7+35*Math.exp(-z*z/2800)+Math.sin(z*.16)*2.5;mountainShape.lineTo(z,yy);}mountainShape.lineTo(85,-25);mountainShape.closePath();for(const off of centers){const hole=new THREE.Path();const rr=radius+Number(p.lining)+.25;hole.moveTo(off-rr,-.5);hole.lineTo(off-rr,3);hole.absarc(off,3,rr,Math.PI,0,true);hole.lineTo(off+rr,-.5);hole.closePath();mountainShape.holes.push(hole);}const mg=new THREE.ExtrudeGeometry(mountainShape,{depth:tl+35,bevelEnabled:false,curveSegments:30});mg.rotateY(Math.PI/2);const mp=mg.attributes.position;for(let i=0;i<mp.count;i++)mp.setX(i,mp.getX(i)+mp.getY(i)*1.2);mg.computeVertexNormals();const rockMap=this.groundTexture();rockMap.repeat.set(.05,.05);const mountain=this.mesh(mg,this.mat('#b1aa87',{map:rockMap}),null,'terrain');mountain.position.set(tx+2,h,cy(tx));
// Sparse vegetation establishes scale around the engineered corridor.
for(let i=0;i<95;i++){const x=-230+((Math.sin(i*78.233)*43758.5453)%1+1)%1*510,z=(i%2?1:-1)*(50+((Math.sin(i*12.9898)*13758.5453)%1+1)%1*100),y=-1+Math.sin(x*.026)*Math.cos(z*.033)*2+Math.max(0,Math.abs(z-cy(x))-35)*.13+Math.sin(x*.013+z*.023)*4;const tree=this.mesh(new THREE.ConeGeometry(2+(i%3)*.4,7+i%4,7),this.mat(i%2?'#47613c':'#526c42'),null,'terrain');tree.position.set(x,y+3,z);}
this.setSelected(this.selected);this.draw();}
set filter(v){this._filter=v;this.focus(v);this.draw();}get filter(){return this._filter;}
focus(v){const b=this.bounds[v];if(b){this.target.set((b[0]+b[1])/2,this.params.pierHeight||16,this.cy((b[0]+b[1])/2));this.distance=v==='road'?145:v==='bridge'?165:105;this.pitch=v==='tunnel'?.23:.52;this.angle=v==='tunnel'?-Math.PI/2+.2:.25;}else{this.target.set(-25,8,0);this.distance=305;this.pitch=.63;this.angle=.22;}}
setSelected(id){this.selected=id;this.root.traverse(m=>{if(m.material?.emissive)m.material.emissive.set(m.userData.id&&m.userData.id===id?'#07567e':'#000000');});this.draw();}
draw(){if(!this.renderer)return;const r=this.canvas.getBoundingClientRect();if(!r.width||!r.height)return;this.renderer.setSize(r.width,r.height,false);this.camera.aspect=r.width/r.height;this.camera.updateProjectionMatrix();this.camera.position.set(this.target.x+this.distance*Math.cos(this.pitch)*Math.sin(this.angle),this.target.y+this.distance*Math.sin(this.pitch),this.target.z+this.distance*Math.cos(this.pitch)*Math.cos(this.angle));this.camera.lookAt(this.target);if(this.options.catalog){const visible=DESIGN_DATA.groups.filter(g=>DESIGN_DATA.object(g.id+'-model')).map(g=>g.id);this.root.traverse(o=>{if(o.userData.group&&o.userData.group!=='terrain')o.visible=visible.includes(o.userData.group);});}this.renderer.render(this.scene,this.camera);}
reset(){this.focus(this._filter);this.draw();}
destroy(){this.resize?.disconnect();this.root.traverse(o=>{o.geometry?.dispose();o.material?.map?.dispose();o.material?.dispose();});this.renderer.dispose();}
};
