/* Local Three.js scene. Parametric design visualization, not an EI geometry parser. */
window.DesignScene=class{
constructor(canvas,options={}){this.canvas=canvas;this.options=options;this.selected=null;this._filter='all';this.angle=.84;this.pitch=.68;this.distance=230;this.target=new THREE.Vector3(-35,4,0);this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#e4eaec');this.scene.fog=new THREE.Fog('#e4eaec',420,850);this.camera=new THREE.PerspectiveCamera(40,1,.1,1800);this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.05;this.scene.add(new THREE.HemisphereLight(0xe6efff,0x73796b,2.0));const sun=new THREE.DirectionalLight(0xfff8e9,2.2);sun.position.set(-100,210,70);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-260,right:260,top:170,bottom:-170,near:1,far:600});sun.shadow.bias=-.0002;sun.shadow.normalBias=.25;this.scene.add(sun);this.root=new THREE.Group();this.scene.add(this.root);this.ray=new THREE.Raycaster();this.rebuild();this.resize=new ResizeObserver(()=>this.draw());this.resize.observe(canvas);canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{this.drag={x:e.clientX,y:e.clientY,px:e.clientX,py:e.clientY,pan:e.shiftKey||e.button===2};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!this.drag)return;const dx=e.clientX-this.drag.px,dy=e.clientY-this.drag.py;this.drag.px=e.clientX;this.drag.py=e.clientY;if(this.drag.pan){this.target.x-=dx*this.distance*.0015*Math.cos(this.angle);this.target.z+=dx*this.distance*.0015*Math.sin(this.angle);this.target.y+=dy*this.distance*.001;}else{this.angle-=dx*.007;this.pitch=Math.max(.12,Math.min(1.5,this.pitch+dy*.006));}this.draw();};canvas.onpointerup=e=>{if(this.drag&&Math.hypot(e.clientX-this.drag.x,e.clientY-this.drag.y)<5){const r=canvas.getBoundingClientRect();this.ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),this.camera);const hit=this.ray.intersectObjects(this.root.children,true).find(h=>h.object.visible);this.setSelected(hit?.object.userData.id||null);this.options.onSelect?.(this.selected);}this.drag=null;};canvas.onpointercancel=()=>this.drag=null;canvas.onwheel=e=>{e.preventDefault();this.distance=Math.max(30,Math.min(580,this.distance*Math.exp(e.deltaY*.001)));this.draw();};}
mat(color,extra={}){return new THREE.MeshStandardMaterial({color,roughness:.86,metalness:0,...extra});}
mesh(geo,mat,id,group){const m=new THREE.Mesh(geo,mat.clone());m.userData={id,group,baseEmissive:mat.emissive?.getHex()||0};m.castShadow=group!=='terrain';m.receiveShadow=true;this.root.add(m);return m;}
box(x,y,z,w,h,d,mat,id,group){const m=this.mesh(new THREE.BoxGeometry(w,h,d),mat,id,group);m.position.set(x,y,z);return m;}
texture(){const c=document.createElement('canvas');c.width=512;c.height=512;const ctx=c.getContext('2d');ctx.fillStyle='#353d41';ctx.fillRect(0,0,512,512);let seed=7;for(let i=0;i<35000;i++){seed=(seed*16807)%2147483647;const x=seed%512;seed=(seed*16807)%2147483647;ctx.fillStyle=i%2?'#ffffff12':'#00000012';ctx.fillRect(x,seed%512,1,1);}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(18,1);t.colorSpace=THREE.SRGBColorSpace;return t;}
groundTexture(){const c=document.createElement('canvas');c.width=c.height=512;const ctx=c.getContext('2d');ctx.fillStyle='#a4ad8c';ctx.fillRect(0,0,512,512);let seed=19;for(let i=0;i<16000;i++){seed=seed*16807%2147483647;const x=seed%512;seed=seed*16807%2147483647;ctx.fillStyle=['#647c4840','#d1bf9940','#556d3930','#eee1b030'][i%4];ctx.fillRect(x,seed%512,2+i%4,2+i%3);}const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(12,8);t.colorSpace=THREE.SRGBColorSpace;return t;}
rebuild(params){this.root.traverse(o=>{o.geometry?.dispose();if(o.material){o.material.map?.dispose();o.material.dispose();}});this.root.clear();const p={...DESIGN_DATA.state.params,...params};this.params=p;const road=p,cy=x=>Math.sin(Math.min(x,be)/115)*Number(p.curve||10);this.cy=cy;const lanes=Number(p.lanes||4),lw=Number(p.laneWidth||3.75),median=Number(p.median||2),shoulder=Number(p.shoulder||3.75),w=lanes*lw+median+shoulder*2;this.width=w;const bl=Math.max(40,Math.min(170,p.spans*p.spanLength)),bs=-bl/2,be=bl/2,h=Number(p.pierHeight||16);this.bounds={road:[-205,bs],bridge:[bs,be],tunnel:[be+16,be+100]};const asphalt=this.mat('#ffffff',{map:this.texture()}),line=this.mat('#f5f3db'),grass=this.mat('#668346'),concrete=this.mat('#bdc3bd'),dark=this.mat('#89928d'),rail=this.mat('#bdc9ce',{metalness:.65,roughness:.4});const verts=[],colors=[];const groundY=(x,z)=>{const lateral=Math.abs(z-cy(x)),approach=Math.max(0,Math.min(1,(bs-x)/55));return -3+Math.sin(x*.024)*Math.cos(z*.032)*1.4+(h-3)*approach*Math.exp(-lateral*lateral/3800)+Math.max(0,lateral-50)*.055;};this.groundY=groundY;const land=new THREE.PlaneGeometry(650,300,130,60);land.rotateX(-Math.PI/2);const pa=land.attributes.position;for(let i=0;i<pa.count;i++){const x=pa.getX(i),z=pa.getZ(i);let y=groundY(x,z);const lateral=Math.abs(z-cy(x));pa.setY(i,y);const col=new THREE.Color().setHSL(.21+Math.sin(x*.018+z*.017)*.018,.13,.48+Math.sin(x*.025)*Math.cos(z*.04)*.045);colors.push(col.r,col.g,col.b);}land.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));land.computeVertexNormals();const groundMap=this.groundTexture();this.mesh(land,this.mat('#ffffff',{vertexColors:true,map:groundMap}),null,'terrain');
// Continuous deck, shoulders, edge lines and lane separators follow the route.
const strip=(a,b,z1,z2,y,mat,id,g)=>{const vs=[],uv=[],ix=[],n=Math.ceil((b-a)/3);for(let i=0;i<=n;i++){const x=a+(b-a)*i/n;vs.push(x,y,cy(x)+z1,x,y,cy(x)+z2);uv.push(i/n,0,i/n,1);if(i<n){const k=i*2;ix.push(k,k+1,k+2,k+1,k+3,k+2);}}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(vs,3));geo.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));geo.setIndex(ix);geo.computeVertexNormals();return this.mesh(geo,mat,id,g);};
for(const [a,b,g,id] of [[-205,bs,'road','RD-PAVE'],[bs,be,'bridge','BR-DECK'],[be,be+110,'tunnel','TN-PAVE']]){strip(a,b,-w/2,w/2,h,asphalt,id,g);if(g!=='tunnel')strip(a,b,-median/2,median/2,h+.16,grass,g==='road'?'RD-MEDIAN':id,g);const laneMedian=g==='tunnel'?Math.max(median,2*(Math.max(lanes/2*lw/2+1.8,Number(p.tunnelRadius))+.8-lanes*lw/4)):median;for(const side of [-1,1]){const inner=side*(laneMedian/2+.2),outer=side*(laneMedian/2+lanes/2*lw);strip(a,b,inner-.13,inner+.13,h+.025,line,id,g);strip(a,b,outer-.14,outer+.14,h+.03,line,id,g);for(let k=1;k<lanes/2;k++){const zz=side*(laneMedian/2+k*lw);for(let x=a;x<b;x+=12)strip(x,Math.min(x+6,b),zz-.13,zz+.13,h+.035,line,id,g);}if(g!=='tunnel'){for(let x=a;x<b;x+=4){const m=this.box(x,h+1,cy(x)+side*(w/2-.4),4,.32,.16,rail,id,g);m.rotation.y=-Math.atan(Math.cos(x/115)*p.curve/115);if(Math.round(x)%8<4)this.box(x,h+.5,cy(x)+side*(w/2-.4),.12,1,.12,rail,id,g);}}}
if(g==='road'){for(let x=a;x<b;x+=5){this.box(x,h-1.5,cy(x),5,2.5,w+1,dark,id,g);for(const side of [-1,1]){const geo=new THREE.BufferGeometry();const z=cy(x)+side*w/2,zz=z+side*Math.max(5,(h-groundY(x,z))*1.5),dz=cy(x+5)-cy(x),zz2=cy(x+5)+side*w/2+side*Math.max(5,(h-groundY(x+5,cy(x+5)+side*w/2))*1.5),gy=groundY(x,zz)+.1,gy2=groundY(x+5,zz2)+.1;geo.setAttribute('position',new THREE.Float32BufferAttribute([x,h-1,z,x+5,h-1,z+dz,x,gy,zz,x+5,h-1,z+dz,x+5,gy2,zz2,x,gy,zz],3));geo.computeVertexNormals();this.mesh(geo,this.mat('#9ba185',{side:THREE.DoubleSide,map:groundMap}),id,g).receiveShadow=false;}}}}
// Box girder with visible beam depth, caps, columns and foundations.
for(let x=bs;x<be;x+=5){for(const side of [-1,1]){const beam=this.box(x,h-1.65,cy(x)+side*(median/2+(w-median)/4),5,2.6,(w-median)/2-1.1,concrete,'BR-DECK','bridge');beam.rotation.y=-Math.atan(Math.cos(x/115)*p.curve/115);this.box(x,h-2.9,cy(x)+side*(median/2+(w-median)/4),5,.35,(w-median)/2-2.8,dark,'BR-DECK','bridge');}}for(const x of [bs,be]){this.box(x,h-3.2,cy(x),3.5,4,w+.5,concrete,'BR-DECK','bridge');for(const side of [-1,1])this.box(x-2,h-2.5,cy(x)+side*(w/2+1),7,5,.65,concrete,'BR-DECK','bridge');}for(let i=1;i<p.spans;i++){const spanValues=p.spanLengths||Array(p.spans).fill(p.spanLength);const x=bs+bl*spanValues.slice(0,i).reduce((a,b)=>a+b,0)/spanValues.reduce((a,b)=>a+b,0),id='BR-PIER-'+i;this.box(x,-1,cy(x),7,2.5,w*.85,concrete,id,'bridge');const pierCount=p.pierType==='独柱墩'?1:2;for(let k=0;k<pierCount;k++){const zz=cy(x)+(pierCount===1?0:(k-.5)*w*.6);const m=this.mesh(new THREE.CylinderGeometry(1.15,1.35,h-3,20),concrete,id,'bridge');m.position.set(x,(h-3)/2,zz);}this.box(x,h-3,cy(x),4,2,w*.85,concrete,id,'bridge');}
// Twin tunnel bores: front portals and segment rings, with a cutaway roof option.
const tx=be+20,tl=Math.min(95,Math.max(35,p.tunnelLength/10)),radius=Math.max(lanes/2*lw/2+1.8,Number(p.tunnelRadius||6)),centers=[-(radius+.8),radius+.8];this.tunnelStart=tx;
for(const zoff of centers){const shape=new THREE.Shape();const outer=radius+Number(p.lining||.6);shape.moveTo(-outer,0);shape.lineTo(-outer,3);shape.absarc(0,3,outer,Math.PI,0,true);shape.lineTo(outer,0);shape.lineTo(radius,0);shape.lineTo(radius,3);shape.absarc(0,3,radius,0,Math.PI,false);shape.lineTo(-radius,0);shape.closePath();const geo=new THREE.ExtrudeGeometry(shape,{depth:tl,bevelEnabled:false,curveSegments:32});geo.rotateY(Math.PI/2);const m=this.mesh(geo,this.mat('#b9bcb0',{side:THREE.DoubleSide}),'TN-LINING','tunnel');m.position.set(tx,h,cy(tx)+zoff);this.tunnelMesh=m;const portal=new THREE.ExtrudeGeometry(shape,{depth:1.7,bevelEnabled:true,bevelSize:.12,bevelThickness:.12,bevelSegments:1});portal.rotateY(Math.PI/2);const pm=this.mesh(portal,this.mat('#d2d0bf'),'TN-PORTAL','tunnel');pm.position.set(tx-.8,h,cy(tx)+zoff);for(let x=tx+5;x<tx+tl;x+=10){for(const side of [-1,1])this.box(x,h+3.4,cy(tx)+zoff+side*(radius-.25),.8,.2,.2,this.mat('#fff6c3',{emissive:'#c6aa51',emissiveIntensity:.7}),'TN-LINING','tunnel');}}
// A continuous triangulated hill is cut back around the two tunnel mouths.
const mountWidth=Math.max(48,radius*6),mountLength=tl+85,mx=tx+mountLength/2-18,mz=cy(tx),hill=new THREE.PlaneGeometry(mountLength,mountWidth*2,72,52);hill.rotateX(-Math.PI/2);const hp=hill.attributes.position,hc=[];for(let i=0;i<hp.count;i++){const x=hp.getX(i)+mx,z=hp.getZ(i)+mz,u=(x-(tx-18))/mountLength,lateral=z-mz;const envelope=Math.pow(Math.max(0,Math.sin(Math.PI*u)),.7),height=(h+25)*envelope*Math.pow(Math.max(0,Math.cos(Math.PI*.5*lateral/mountWidth)),1.8);hp.setXYZ(i,x,groundY(x,z)+height,z);const tint=new THREE.Color().setHSL(.2+Math.sin(x*.07+z*.08)*.02,.15,.47+Math.sin(x*.08)*Math.cos(z*.13)*.045);hc.push(tint.r,tint.g,tint.b);}const hi=[],original=hill.index.array;for(let i=0;i<original.length;i+=3){const indices=[original[i],original[i+1],original[i+2]],x=indices.reduce((sum,j)=>sum+hp.getX(j),0)/3,z=indices.reduce((sum,j)=>sum+hp.getZ(j),0)/3;const opening=x<tx+10&&centers.some(off=>Math.abs(z-(mz+off))<radius+1.7);if(!opening)hi.push(...indices);}hill.setIndex(hi);hill.setAttribute('color',new THREE.Float32BufferAttribute(hc,3));hill.computeVertexNormals();this.mesh(hill,this.mat('#ffffff',{vertexColors:true,map:groundMap,side:THREE.DoubleSide}),null,'terrain');
// Small exposed rock fragments sit on the cut slopes at the portals.
for(const side of [-1,1])for(let k=0;k<7;k++){const rock=this.mesh(new THREE.DodecahedronGeometry(.9+(k%3)*.4,0),this.mat(k%2?'#a7ab98':'#8e9580',{flatShading:true,roughness:1}),null,'terrain');const rx=tx+5+k*2.3,rz=mz+side*(radius*2+3+k*.5);rock.scale.set(1.4,.65,.8);rock.position.set(rx,groundY(rx,rz)+1.6+k*.38,rz);rock.rotation.set(.25,k*.4,.13);}
// Concrete portal aprons, drainage channels and warm tunnel soffit lighting.
for(const off of centers){const portalZ=cy(tx)+off;this.box(tx-3,h+.07,portalZ,6,.15,radius*2,concrete,'TN-PORTAL','tunnel');strip(tx-7,tx-1,off-radius+.5,off+radius-.5,h+.16,asphalt,'TN-PAVE','tunnel');for(const side of [-1,1]){const wing=this.box(tx-4,h+1.4,portalZ+side*(radius+.4),8,2.8,.65,concrete,'TN-PORTAL','tunnel');wing.rotation.y=side*.16;this.box(tx-3,h+.28,portalZ+side*(radius-.25),7,.4,.36,dark,'TN-PORTAL','tunnel');}const wall=this.mat('#d0d1c9',{roughness:.92});for(let x=tx+10;x<tx+tl;x+=12){const ring=new THREE.TorusGeometry(radius+.04,.07,6,36,Math.PI),rm=this.mesh(ring,wall,'TN-LINING','tunnel');rm.rotation.y=Math.PI/2;rm.position.set(x,h+3,portalZ);}}
// A few accurately scaled vehicles and direction arrows make carriageways legible.
for(const x of [-177,-122,-85,-28,25,54]){if(x>be-8)continue;const side=x%2===0?1:-1,id=x<bs?'RD-PAVE':'BR-DECK',g=x<bs?'road':'bridge',z=cy(x)+side*(median/2+lw*.55),heading=-Math.atan(Math.cos(x/115)*p.curve/115);const paint=this.mat(x%3===0?'#a43829':x%3===1?'#e9edf0':'#51667b',{metalness:.25,roughness:.45});const car=this.box(x,h+.75,z,4.6,1.0,1.8,paint,id,g);car.rotation.y=heading;const glass=this.box(x-.35,h+1.45,z,2.2,.65,1.58,this.mat('#293d47',{metalness:.5,roughness:.3}),id,g);glass.rotation.y=heading;for(const wheelX of [-1.5,1.5])for(const wheelZ of [-.88,.88]){const wheel=this.mesh(new THREE.CylinderGeometry(.38,.38,.2,12),this.mat('#25292c'),id,g);wheel.rotation.x=Math.PI/2;wheel.position.set(x+wheelX,h+.38,z+wheelZ);}}
for(const x of [-155,-95,0,45])for(const side of [-1,1]){if(x>be-8)continue;const id=x<bs?'RD-PAVE':'BR-DECK',g=x<bs?'road':'bridge',z=side*(median/2+lw*.55),tip=x+side*2.5;strip(x-1.6,x+1.6,z-.11,z+.11,h+.04,line,id,g);const arrow=new THREE.BufferGeometry();arrow.setAttribute('position',new THREE.Float32BufferAttribute([tip,h+.05,cy(tip)+z,tip-side*1.3,h+.05,cy(tip-side*1.3)+z-.58,tip-side*1.3,h+.05,cy(tip-side*1.3)+z+.58],3));arrow.computeVertexNormals();this.mesh(arrow,this.mat('#f4f0de',{side:THREE.DoubleSide}),id,g);}
// Low, clustered vegetation gives scale without obscuring the engineering model.
for(let i=0;i<60;i++){const rnd=n=>((Math.sin(n*78.233)*43758.5453)%1+1)%1,x=-235+rnd(i+1)*480,z=(i%2?1:-1)*(34+rnd(i+100)*48);if(x>tx-20&&Math.abs(z-cy(tx))<mountWidth+7)continue;const y=groundY(x,z),height=3+rnd(i+60)*3;const trunk=this.mesh(new THREE.CylinderGeometry(.17,.24,height*.65,7),this.mat('#797160'),null,'terrain');trunk.position.set(x,y+height*.3,z);for(let k=0;k<3;k++){const crown=this.mesh(new THREE.IcosahedronGeometry(height*(.32+k*.035),1),this.mat(k%2?'#687b57':'#5e7350'),null,'terrain');crown.scale.y=1.2;crown.position.set(x+(k-1)*.5,y+height*(.55+k*.12),z+(k%2)*.5);}}
this.setSelected(this.selected);this.draw();}
set filter(v){this._filter=v;this.focus(v);this.draw();}get filter(){return this._filter;}
focus(v){this.view=v;const b=this.bounds[v];if(b){this.target.set((b[0]+b[1])/2,(this.params.pierHeight||16)+(v==='tunnel'?3:-3),this.cy((b[0]+b[1])/2));this.distance=v==='road'?114:v==='bridge'?144:76;this.pitch=v==='tunnel'?.18:.5;this.angle=v==='tunnel'?-Math.PI/2+.1:.18;}else{this.target.set(-22,(this.params.pierHeight||16)-2,1);this.distance=215;this.pitch=.62;this.angle=-.22;}}
setSelected(id){this.selected=id;this.root.traverse(m=>{if(m.material?.emissive)m.material.emissive.set(m.userData.id&&m.userData.id===id?'#07567e':m.userData.baseEmissive||0);});this.draw();}
draw(){if(!this.renderer)return;const r=this.canvas.getBoundingClientRect();if(!r.width||!r.height)return;this.renderer.setSize(r.width,r.height,false);this.camera.aspect=r.width/r.height;this.camera.updateProjectionMatrix();this.camera.position.set(this.target.x+this.distance*Math.cos(this.pitch)*Math.sin(this.angle),this.target.y+this.distance*Math.sin(this.pitch),this.target.z+this.distance*Math.cos(this.pitch)*Math.cos(this.angle));this.camera.lookAt(this.target);if(this.options.catalog){const visible=DESIGN_DATA.groups.filter(g=>DESIGN_DATA.object(g.id+'-model')).map(g=>g.id);this.root.traverse(o=>{if(o.userData.group&&o.userData.group!=='terrain')o.visible=visible.includes(o.userData.group);});}this.renderer.render(this.scene,this.camera);}
reset(){this.focus(this._filter);this.draw();}
destroy(){this.resize?.disconnect();this.canvas.onpointerdown=this.canvas.onpointermove=this.canvas.onpointerup=this.canvas.onpointercancel=this.canvas.onwheel=this.canvas.oncontextmenu=null;this.root.traverse(o=>{o.geometry?.dispose();o.material?.map?.dispose();o.material?.dispose();});this.renderer.dispose();}
};
