/* Explicit cross-stage references; application navigation never transfers business data. */
(() => {
'use strict';
const {esc,icon,dialog}=CDE;
const map={bridge:{name:'K12+350 大桥',survey:'DES-BR-001',surveyName:'桥梁设计模型',surveyVersion:'V1 · 设计示例',sheets:['S-101','S-102']},tunnel:{name:'K14+000 隧道',survey:'DES-TN-001',surveyName:'隧道设计模型',surveyVersion:'V1 · 设计示例',sheets:['S-201','S-202']},station:{name:'综合管理站',survey:null,sheets:['S-301','S-302']}};
const assets={'FAN-01':{facility:'tunnel',sheet:'S-201',submittal:'SUB-002'},'PUMP-01':{facility:'tunnel',sheet:'S-202'},'DB-01':{facility:'tunnel',sheet:'S-201'}};
function current(){if(window.DESIGN){const o=DESIGN.selected();return {facility:o?.group};}if(window.OPS){const a=OPS.selected();return {facility:a.facility,asset:a.id};}if(window.BUILD){if(BUILD.state.view==='files'&&window.WBS){const n=WBS.node(WBS.state.node),d=WBS.docs.find(d=>d.id===WBS.state.selected);return {facility:Object.keys(map).find(k=>map[k].name===n.zone),asset:assets[d?.ref]?d.ref:null,sheet:d?.ref?.startsWith('S-')?d.ref:null,record:d?.ref,wbs:n.id};}const r=Object.values(BUILD.rows).flat().find(r=>r.id===BUILD.state.selected);if(r){return {facility:Object.keys(map).find(k=>map[k].name===r.zone),asset:BUILD.rows.assets.includes(r)?r.id:null,sheet:r.sheet,record:r.id};}if(document.querySelector('.build-viewer[open]'))return {sheet:BUILD.state.sheet,facility:Object.keys(map).find(k=>map[k].sheets.includes(BUILD.state.sheet))};}const code=(typeof activeItem!=='undefined'&&activeItem?.code)||(typeof results!=='undefined'&&typeof selectedResult!=='undefined'&&results[selectedResult]?.code)||new URLSearchParams(location.search).get('asset-source');return {facility:Object.keys(map).find(k=>map[k].survey===code)};}
function opUrl(asset,facility,view='twin'){return 'operations.html?'+new URLSearchParams({...asset?{asset}:{},...facility?{facility}:{}})+'#'+view;}
function buildUrl(record,view='assets'){return 'construction.html?'+new URLSearchParams(record?{record}:{})+'#'+view;}
function stageHref(stage){const c=current();if(stage==='运营期')return opUrl(assets[c.asset]?c.asset:null,c.facility);if(stage==='施工期')return assets[c.asset]?buildUrl(c.asset):'construction.html#home';return 'file-management.html';}
function link(href,text){return `<a class="lc-link" href="${esc(href)}">${esc(text)} ↗</a>`;}
function open(override){const c={...current(),...override},f=map[c.facility],a=assets[c.asset];const d=dialog('阶段关联与交付核验',`<div class="lc-context"><b>${esc(c.asset||c.record||c.sheet||c.wbs||'项目级关联')}</b><span>${esc(f?.name||'XX 高速公路')}</span></div><p>业主应在设计阶段明确资产分类、唯一编码、信息要求和验收标准，设计与施工按要求持续补齐。</p><div class="lc-chain"><section><small>01 / 设计与公共数据环境</small><h3>明确成果用途与发行版本</h3>${f?.survey?`<p>设计阶段来源模型<br><b>${f.survey}</b> · ${window.DESIGN_DATA?.object(f.survey)?.version||f.surveyVersion}</p>${link('file-management.html?asset-source='+f.survey,f.surveyName)}<p class="lc-warning">仅作设计来源参考，不等于已批准施工图或设备设计模型。</p>`:`<p class="lc-warning">${f?'未建立该设施的设计成果关联。':'资料库按路、桥、隧管理设计成果。'}不按名称或相近桩号推定来源。</p>`}<p>施工图设计源文件、审查结论和发行单：<b>待建立关联</b></p>${link('workflows.html#reviews','查看设计审阅示例')}</section><section><small>02 / 施工管理</small><h3>执行、验证并形成交付包</h3><p>施工快照：2026-09-11<br>施工图 → 现场记录 → 竣工模型与资产清单</p>${c.sheet||a?.sheet?link(buildUrl(c.sheet||a.sheet,'sheets'),'查看关联施工图 '+(c.sheet||a.sheet)):''}${a?link(buildUrl(c.asset),'定位施工设备 '+c.asset):'<p class="lc-warning">当前对象没有已建立的施工设备映射。</p>'}${a?.submittal?link(buildUrl(a.submittal,'submittals'),'查看设备报审 '+a.submittal):''}<p>交付包应记录模型版本、资产编码、调试记录、手册及接收确认。本示例尚未登记已验收交付包。</p></section><section><small>03 / 运营数字孪生</small><h3>导入、映射、核验与运行</h3><p>预置运营快照：2026-10-11<br>沿用信息要求 → 模型导入 → 参数映射 → 完整性与准确性核验</p>${link(opUrl(a||window.OPS_DATA?.assets.some(x=>x.id===c.asset)?c.asset:null,c.facility),a||window.OPS_DATA?.assets.some(x=>x.id===c.asset)?'查看运营对象示例':'查看设施运营示例')}<p>编码相同表示显式示例映射；施工状态或文件不会因页面切换而自动同步。</p><p>实时监测还需配置连接、数据流和阈值，与竣工资料交付分开。</p></section></div><div class="lc-boundaries"><h3>生态中的连接方式</h3><p><b>同一项目：</b>Data Management 是共享文件基础，Build 的图纸与现场记录引用文件；“切换阶段”不是复制或发布数据。</p><p><b>跨项目：</b>Bridge 用于跨项目共享，需指定对象和更新策略。并非所有单文件共享都自动更新。</p><p><b>Build → Tandem：</b>竣工资料导出与模型导入不是同一个动作。官方 2025-08-08 支持文章将 Build 资产连接服务标为 Tandem Connect Beta，不能视为默认成熟同步。</p></div>`,'关闭',()=>{});d.classList.add('lc-dialog');const reset=document.createElement('button');reset.className='text-button';reset.textContent='重置本标签页演示数据';reset.onclick=()=>{resetting=true;window.WBS?.reset();try{sessionStorage.removeItem(key+'build');sessionStorage.removeItem(key+'ops');sessionStorage.removeItem('lifecycle-wbs-v1');sessionStorage.removeItem('design-road-v1');}catch{}location.href=document.body.dataset.page==='construction'?'construction.html#home':document.body.dataset.page==='operations'?'operations.html#twin':'file-management.html';};d.querySelector('footer').prepend(reset);}
const key='lifecycle-audit-v1-',read=t=>{try{return JSON.parse(sessionStorage.getItem(key+t)||'null');}catch{return null;}};let resetting=false;
function restoreBuild(rows,changes,state){const x=read('build');if(x?.rows){for(const k of Object.keys(rows))if(Array.isArray(x.rows[k]))rows[k].splice(0,rows[k].length,...x.rows[k]);if(Array.isArray(x.changes))changes.splice(0,changes.length,...x.changes);state.formAnswers=x.answers||{};}}
function restoreOps(data){const x=read('ops');if(Array.isArray(x))for(const a of data.assets){const saved=x.find(s=>s.id===a.id&&s.facility===a.facility);if(saved)Object.assign(a,saved);}}
window.addEventListener('pagehide',()=>{if(resetting)return;try{if(window.BUILD)sessionStorage.setItem(key+'build',JSON.stringify({rows:BUILD.rows,changes:BUILD.changes,answers:BUILD.state.formAnswers}));if(window.OPS_DATA)sessionStorage.setItem(key+'ops',JSON.stringify(OPS_DATA.assets));}catch{}});
window.LC={map,assets,current,open,opUrl,buildUrl,stageHref,restoreBuild,restoreOps};
const b=document.createElement('button');b.className='text-button lc-header-button';b.id='lifecycleTrace';b.innerHTML=icon('bridge')+'<span>阶段关联</span>';b.onclick=()=>open();document.querySelector('.project-picker').after(b);
document.addEventListener('click',e=>{if(e.target.closest('[data-lifecycle]'))open();});
})();
