/* Project onboarding UI. Drafts never imply a real BIM import or sensor connection. */
window.OPS_SETUP=(()=>{
const {esc,dialog}=CDE;const drafts={};let activeStep='model';
const steps=[['model','导入源模型','RVT / IFC → 元素与空间'],['asset','关联资产数据','元素 → 资产编码与文档'],['sensor','接入传感器','测点 → 连接 → 数据流'],['verify','核验并使用','来源核验 → 孪生与看板']];
const ctx=()=>{const o=OPS,a=o.selected(),f=o.facility();return{o,a,f,d:drafts[f.id]||(drafts[f.id]={})};};
function action(id,text){return `<button class="cde-primary" data-setup="${id}">${text}</button>`;}
function render(host){const {o,a,f,d}=ctx();host.innerHTML=`<div class="setup-steps">${[['model','模型'],['asset','资产关联'],['sensor','连接'],['verify','数据检查']].map(([id,t])=>`<button data-setup-tab="${id}" class="${activeStep===id?'active':''}">${t}</button>`).join('')}</div><div class="setup-body"><section class="setup-work"><div id="setupStep"></div></section><aside class="setup-lineage"><header><h3>关联对象</h3><select id="setupAsset" aria-label="查看资产来源">${o.assets().map(x=>`<option value="${x.id}" ${x.id===a.id?'selected':''}>${x.id} · ${esc(x.name)}</option>`).join('')}</select></header><dl class="op-props">${[['源模型',f.model],['元素 ID',a.sourceId],['资产编码',a.id],['分类',a.classification],['连接',a.connection||'未配置'],['数据流',a.stream||'未接入']].map(([k,v])=>`<dt>${k}</dt><dd>${esc(v)}</dd>`).join('')}</dl><button class="text-button" data-setup="trace">查看来源</button></aside></div>`;host.querySelector('#setupAsset').onchange=e=>{o.state.selected=e.target.value;render(host);};host.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.setupTab){activeStep=b.dataset.setupTab;render(host);}if(b.dataset.setup)open(b.dataset.setup);};paintStep(host);}
function paintStep(host){const {a,f,d}=ctx();const table=(heads,rows)=>`<table class="op-table"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;const panels={
model:`<div class="setup-section-head"><h2>源模型</h2>${action('model','导入模型')}</div>${table(['文件名称','格式','版本','状态'],[[f.model,f.model.split('.').pop().toUpperCase(),'V1','示例模型']])}<div class="setup-actions"><a href="#documents">打开模型文件</a></div>`,
asset:`<div class="setup-section-head"><h2>资产关联</h2>${action('asset','配置关联')}</div>${table(['来源字段','目标参数','当前值'],[['Element ID','模型元素',a.sourceId],['AssetCode','资产编码',a.id],['Manufacturer','制造商',a.manufacturer||'待补齐'],['Document','运维文档',a.manual||'待关联']])}<div class="setup-actions"><a href="#inventory">打开资产清单</a><a href="#handover">检查数据完整性</a></div>`,
sensor:`<div class="setup-section-head"><h2>连接配置</h2>${action('sensor','创建连接')}</div>${table(['连接','宿主资产','数据流','单位'],[[a.connection||'未配置',a.id,a.stream||'未接入',a.unit||'—']])}<div class="setup-actions"><a href="#connections">管理连接</a><a href="#streams">查看数据流</a></div>`,
verify:`<div class="setup-section-head"><h2>数据检查</h2><a class="text-button" href="#handover">查看全部资产</a></div>${table(['检查项','结果'],[['模型版本','V1 · 示例模型'],['模型元素',a.sourceId],['资产编码',a.id],['必填参数',OPS.missing(a).length?OPS.missing(a).map(x=>x[1]).join('、')+'待补齐':'已填写'],['监测来源',a.stream?'示例数据流':'未接入']])}<div class="setup-actions"><a class="cde-primary" href="#twin">打开孪生</a></div>`};host.querySelector('#setupStep').innerHTML=panels[activeStep]+`<div class="setup-drafts"><h3>配置草稿</h3><p>${esc(d[activeStep]||'尚未保存配置')}</p></div>`;}
function open(kind){if(kind==='trace'){LC.open();return;}const {a,f,o,d}=ctx();if(!['model','asset','sensor'].includes(kind))return;let step=0;const draft={source:'local',file:'',host:a.id,point:'SENSOR-'+a.id,field:'value',time:'timestamp',protocol:'网关 / API',unit:a.unit||'',model:f.model,manufacturerSource:'Manufacturer'};
const titles={model:'导入模型',asset:'配置资产关联',sensor:'接入传感器'};const titlesSteps=kind==='model'?['选择来源','检查导入设置','确认下一步']:kind==='asset'?['选择对象','核对参数来源','确认关联']:['绑定宿主与测点','映射监测字段','验证样例载荷'];
const modal=dialog(titles[kind],'<div id="setupWizard"></div>','');modal.classList.add('setup-dialog');
function draw(){const target=o.assets().find(x=>x.id===draft.host);const w=modal.querySelector('#setupWizard');w.innerHTML=`<div class="setup-wizard-steps">${titlesSteps.map((t,i)=>`<span class="${i===step?'active':''}">${i+1} ${t}</span>`).join('')}</div><div class="setup-wizard-context">${esc(f.name)} · ${esc(target.id)} · 前端配置示例</div>`;
if(kind==='model')w.innerHTML+=step===0?`<label class="field">模型来源<select id="setupSource"><option value="local" ${draft.source==='local'?'selected':''}>本地 RVT / IFC 文件</option><option value="cde" ${draft.source==='cde'?'selected':''}>Forma Data Management 文件引用（示例）</option></select></label><label class="field">选择文件<input type="file" id="setupModelFile" accept=".rvt,.ifc"></label><button class="text-button" id="setupUseSample">使用预置示例文件</button><p id="setupFileLabel">${esc(draft.file||'尚未选择文件')}</p><p>文件选择只读取名称，不上传或解析模型。选择公共数据环境来源时使用示例文件引用，不连接外部账号。</p>`:step===1?`<h3>${esc(draft.file)}</h3><label class="field">版本 / 来源<input value="V1 · ${draft.source==='cde'?'公共数据环境引用示例':'本地文件索引'}" readonly></label><label class="field">坐标检查<select><option>沿用源模型坐标，导入后核对位置</option></select></label><label class="radio-row"><input type="checkbox" checked> 默认视图可见</label><p>Revit 可按阶段 / 视图选择导入范围；IFC 按文件内容导入。这里不模拟真实几何处理。</p>`:`<h3>保存模型导入草稿</h3><p>${esc(draft.file)} → ${esc(f.name)}</p><p>下一步：检查元素与空间，应用设施模板并配置资产关联。现有示意模型保持原状。</p>`;
if(kind==='asset')w.innerHTML+=step===0?`<label class="field">目标资产<select id="setupHost">${o.assets().map(x=>`<option value="${x.id}" ${x.id===draft.host?'selected':''}>${x.id} · ${esc(x.name)}</option>`).join('')}</select></label><div class="setup-source"><b>${esc(f.model)} / ${target.sourceId}</b><p>元素标识来自模型；AssetCode 来自交付台账。当前使用显式预置映射，不按名称自动匹配。</p></div>`:step===1?`<table class="op-table"><thead><tr><th>来源字段（示例）</th><th>目标资产参数</th><th>当前值</th></tr></thead><tbody>${[['AssetCode','资产编码',target.id],['Manufacturer','制造商',target.manufacturer],['SerialNumber','序列号',target.serial],['文档链接','运维手册',target.manual]].map(r=>`<tr>${r.map((v,i)=>`<td>${i===0&&v==='Manufacturer'?'<select id="setupManufacturerMap" aria-label="制造商来源字段"><option>Manufacturer</option><option>交付台账.制造商</option><option>人工补齐</option></select>':esc(v||'待补齐')}</td>`).join('')}</tr>`).join('')}</tbody></table><p>来源台账尚未实际读取。重复编码或无法匹配的行应进入人工核验，不覆盖既有资产。</p>`:`<h3>确认对象关系</h3><p>${esc(f.model)} / ${target.sourceId} → ${target.id}</p><p>空间：${esc(f.spaces.find(x=>x[0]===target.space)?.[1])}<br>系统：${esc(f.systems.find(x=>x[0]===target.system)?.[1])}<br>文档：${esc(target.manual||'待关联')}</p><p>此处保存关联方案；实际补齐参数或文档请进入资产清单 / 数据交付。</p>`;
if(kind==='sensor')w.innerHTML+=step===0?`<label class="field">宿主资产<select id="setupHost">${o.assets().map(x=>`<option value="${x.id}" ${x.id===draft.host?'selected':''}>${x.id} · ${esc(x.name)}</option>`).join('')}</select></label><label class="field">外部测点标识<input id="setupPoint" value="${esc(draft.point)}"></label><label class="field">接入路径<select id="setupProtocol"><option>网关 / API</option><option ${draft.protocol!=='网关 / API'?'selected':''}>集成服务 / Tandem Connect</option></select></label><p>宿主将读数关联到设施中的对象；外部测点标识用于区分现场数据来源。</p>`:step===1?`<h3>${target.id} · ${esc(target.metric||'监测参数')}</h3><label class="field">数值字段<input id="setupValueField" value="${esc(draft.field)}"></label><label class="field">时间戳字段<input id="setupTimeField" value="${esc(draft.time)}"></label><label class="field">单位<input id="setupUnit" value="${esc(draft.unit)}"></label><p>采样间隔：5 分钟（示例）。单位需要与参数一致；数值与时间戳字段不能相同。</p>`:`<h3>样例校验通过 · 未连接现场</h3><pre>${esc(JSON.stringify({point:draft.point,host:target.id,[draft.time]:'2026-10-11T10:00:00+08:00',[draft.field]:target.value??0,unit:draft.unit},null,2))}</pre><p>目标：${target.connection||'待创建连接'} / ${target.stream||'待创建数据流'}<br>路径：${esc(draft.protocol)}</p><p>这里只核验字段配置并生成样例，不执行网络连通性或实时读数测试。保存草稿不会将离线设备标成在线。</p>`;
w.innerHTML+='<p id="setupError" role="alert"></p>';modal.querySelector('footer').innerHTML=`<small>步骤 ${step+1} / 3 · 配置演示</small><button class="text-button" id="setupBack">${step?'上一步':'取消'}</button><button class="cde-primary" id="setupNext">${step===2?'保存配置草稿':'下一步'}</button>`;
const input=id=>modal.querySelector('#'+id);if(input('setupSource'))input('setupSource').onchange=e=>draft.source=e.target.value;if(input('setupModelFile'))input('setupModelFile').onchange=e=>{draft.file=e.target.files[0]?.name||'';input('setupFileLabel').textContent=draft.file;};if(input('setupUseSample'))input('setupUseSample').onclick=()=>{draft.file=f.model;input('setupFileLabel').textContent=draft.file;};if(input('setupHost'))input('setupHost').onchange=e=>{draft.host=e.target.value;const x=o.assets().find(a=>a.id===draft.host);draft.unit=x.unit||'';draft.point='SENSOR-'+x.id;draw();};
input('setupBack').onclick=()=>{if(step){step--;draw();}else modal.close();};input('setupNext').onclick=()=>{if(kind==='model'&&step===0&&!/\.(ifc|rvt)$/i.test(draft.file)){input('setupError').textContent='请选择 RVT / IFC 文件或使用预置示例。';return;}if(kind==='asset'&&step===1)draft.manufacturerSource=input('setupManufacturerMap').value;if(kind==='sensor'){if(step===0){draft.point=input('setupPoint').value.trim();draft.protocol=input('setupProtocol').value;if(!draft.point){input('setupError').textContent='请填写外部测点标识。';return;}}if(step===1){draft.field=input('setupValueField').value.trim();draft.time=input('setupTimeField').value.trim();draft.unit=input('setupUnit').value.trim();if(!draft.field||!draft.time||!draft.unit||draft.field===draft.time||['point','host','unit'].includes(draft.field)||['point','host','unit'].includes(draft.time)){input('setupError').textContent='请填写不同的数值、时间戳字段及单位；字段不能占用 point、host、unit。';return;}}}if(kind==='sensor'&&step===1&&target.unit&&draft.unit!==target.unit){input('setupError').textContent='单位需与目标参数一致：'+target.unit+'；单位转换应在接入前完成。';return;}if(step<2){step++;draw();}else{d[kind]=kind==='model'?`${draft.file} · ${draft.source==='local'?'本地':'CDE'}导入方案已记录`:kind==='asset'?`${target.sourceId} → ${target.id}；制造商来源：${draft.manufacturerSource}；关联方案已记录`:`${draft.point} → ${target.id} · ${draft.field} / ${draft.unit} · 待真实接入`;o.state.selected=target.id;modal.close();activeStep=kind==='model'?'asset':kind==='asset'?'sensor':'verify';location.hash='setup';o.render();}};}
draw();}
return{render,open};
})();
