(() => {
'use strict';
const {icon,esc,dialog,notify,hydrate}=window.CDE;
const D=window.OPS_DATA,$=(s,e=document)=>e.querySelector(s),$$=(s,e=document)=>[...e.querySelectorAll(s)];
const host=$('#operationsWorkspace');
const nav=[['home','home','主页'],['facilities','building','设施'],['manage','settings','管理'],['twin','space','查看器'],['inventory','file','资产清单'],['spaces','layers','空间'],['systems','bridge','系统'],['documents','folder','模型文件'],['docs','file','文档'],['connections','share','连接'],['streams','clock','数据流'],['dashboard','panel','仪表板'],['handover','review','数据检查'],['setup','upload','接入配置'],['history','clock','历史记录']];
function navRender(view){const overview=['home','facilities','manage'].includes(view);document.body.classList.toggle('tandem-overview',overview);$('#cdeNav').innerHTML=(!overview?`<div class="nav-group"><div class="nav-caption">${esc(facility().name)}</div>${nav.slice(3).map(n=>`<a href="#${n[0]}" data-opsnav="${n[0]}" title="${n[2]}">${icon(n[1])}<span class="nav-text">${n[2]}</span></a>`).join('')}</div>`:'')+`<div class="nav-bottom"><a href="file-management.html">${icon('folder')}<span class="nav-text">Data Management</span></a><a href="#" data-op="sources">${icon('help')}<span class="nav-text">关于此演示</span></a></div>`;}
$('#appSwitch .app-glyph').classList.add('tandem-glyph');document.querySelector('.project-picker').insertAdjacentHTML('afterend',`<nav class="tandem-account-nav" aria-label="Tandem 账户导航">${nav.slice(0,3).map(n=>`<a href="#${n[0]}" data-opsnav="${n[0]}">${n[2]}</a>`).join('')}</nav>`);
const state={facility:'tunnel',selected:'FAN-01',system:'',space:'',status:'',search:'',color:'status',mode:'model',tab:'properties',time:23,range:'24h',zoom:1,filterOpen:true,inspector:true,inventory:true,trace:'downstream',view:'设施总览'};
const facility=()=>D.facilities.find(f=>f.id===state.facility);
const assets=()=>D.assets.filter(a=>a.facility===state.facility);
const selected=()=>D.assets.find(a=>a.id===state.selected)||assets()[0];
const label=(type,id)=>facility()[type].find(r=>r[0]===id)?.[1]||'未分配';
const missing=a=>D.required.filter(([k])=>!a[k]);
const valueAt=a=>a.online&&a.series.length?a.series[state.time]:null;
function status(a){const v=valueAt(a);if(a.online===null)return ['none','未接入'];if(a.online===false)return ['offline','离线'];if(v>a.limit)return ['critical','超限'];if(v>a.warning)return ['warning','预警'];return ['normal','正常'];}
const statusPill=a=>{const s=status(a);return `<span class="op-status ${s[0]}"><i></i>${s[1]}</span>`;};
const valueText=a=>valueAt(a)===null?'—':valueAt(a).toLocaleString('en-US',{maximumFractionDigits:2});
function filtered(){return assets().filter(a=>(!state.system||a.system===state.system)&&(!state.space||a.space===state.space)&&(!state.search||[a.id,a.name,a.classification,label('spaces',a.space),label('systems',a.system)].join(' ').toLowerCase().includes(state.search.toLowerCase()))&&(!state.status||(state.status==='attention'?['warning','critical','offline'].includes(status(a)[0]):state.status==='missing'?missing(a).length>0:status(a)[0]===state.status)));}
function go(view){if(location.hash==='#'+view)render();else location.hash=view;}
function switchFacility(id){state.facility=id;state.selected=assets()[0].id;resetFilters();state.view=facility().view;state.time=23;state.zoom=1;render();}
function resetFilters(){state.system='';state.space='';state.status='';state.search='';}
function top(title,sub){const overview=['home','facilities','manage'].includes(location.hash.slice(1)||'facilities');return `<header class="op-heading"><h1>${title}</h1><div class="op-heading-tools">${overview?'':`<button class="text-button" data-op="views">${icon('camera')}已保存视图</button>`}</div></header>${overview?'':`<div class="op-context"><button class="facility-select" data-op="facility-picker">${icon('building')}<strong>${facility().name}</strong><span>⌄</span></button><span class="toolbar-spacer"></span><label class="op-global-search">${icon('search')}<input id="opGlobalSearch" placeholder="搜索资产、空间、系统" aria-label="搜索资产"></label></div>`}`;}

function subTools(buttons='',extra=''){return `<div class="op-page-tools">${buttons}<span class="toolbar-spacer"></span>${extra}</div>`;}
const btn=(op,text,ic='')=>`<button class="text-button" data-op="${op}">${ic?icon(ic):''}${text}</button>`;
function filterPanel(){return `<aside class="op-filter"><div class="op-panel-title"><strong>筛选器</strong><button class="text-button" data-op="reset">重置</button></div><div class="op-filter-body"><div class="filter-section"><h3>设施空间 <small>${facility().spaces.length}</small></h3><button class="filter-row ${!state.space?'active':''}" data-space="">全部空间 <small>${assets().length}</small></button>${facility().spaces.map(([id,n])=>`<button class="filter-row ${state.space===id?'active':''}" data-space="${id}">${icon('layers')}<span>${n}</span><small>${assets().filter(a=>a.space===id).length}</small></button>`).join('')}</div><div class="filter-section"><h3>系统 <small>${facility().systems.length}</small></h3><button class="filter-row ${!state.system?'active':''}" data-system="">全部系统 <small>${assets().length}</small></button>${facility().systems.map(([id,n],i)=>`<button class="filter-row ${state.system===id?'active':''}" data-system="${id}"><i class="system-dot s${i}"></i><span>${n}</span><small>${assets().filter(a=>a.system===id).length}</small></button>`).join('')}</div><div class="filter-section"><h3>运行状态</h3>${[['','全部状态'],['attention','需关注'],['offline','离线'],['missing','数据待补齐']].map(([id,n])=>`<button class="filter-row ${state.status===id?'active':''}" data-status="${id}"><span>${n}</span><small>${assets().filter(a=>!id||(id==='attention'?['warning','critical','offline'].includes(status(a)[0]):id==='missing'?missing(a).length:status(a)[0]===id)).length}</small></button>`).join('')}</div><div class="op-filter-note">${icon('file')}源模型<br><b>${facility().model}</b><span>竣工交付版本 · V1</span></div></div></aside>`;}
function assetTable(list,compact=false){return `<table class="op-table ${compact?'compact':''}"><thead><tr><th>资产名称 / 编码</th><th>分类</th><th>空间</th><th>系统</th><th>运行状态</th>${compact?'':'<th>数据完整性</th>'}<th>最新读数</th></tr></thead><tbody>${list.map(a=>`<tr data-select="${a.id}" tabindex="0" class="${state.selected===a.id?'selected':''}"><td><strong>${a.name}</strong><small>${a.id}</small></td><td>${a.classification}</td><td>${label('spaces',a.space)}</td><td>${label('systems',a.system)}</td><td>${statusPill(a)}</td>${compact?'':`<td><span class="completeness ${missing(a).length?'incomplete':''}">${D.required.length-missing(a).length} / ${D.required.length} 项</span></td>`}<td>${valueText(a)} <small class="inline-unit">${a.unit}</small></td></tr>`).join('')}</tbody></table>${list.length?'':'<div class="op-empty">没有匹配的资产。请重置筛选条件。</div>'}`;}
function chart(a,{large=false}={}){if(!a.series.length)return `<div class="op-empty ${large?'large':''}">${icon('clock')}<b>${a.online===false?'数据连接离线':'尚未配置数据流'}</b><span>${a.online===false?'最后收到数据：'+a.updated:'该资产暂不提供时序读数'}</span></div>`;
 const values=state.range==='6h'?a.series.slice(18):a.series;const W=600,H=large?240:160,pad=36,high=Math.max(a.limit*1.1,...values)*1.05||1;const x=i=>pad+i*(W-pad*2)/(values.length-1),y=v=>H-pad-v/high*(H-pad*2);const path=values.map((v,i)=>`${i?'L':'M'}${x(i).toFixed(1)},${y(v).toFixed(1)}`).join(' ');const warning=y(a.warning),limit=y(a.limit);return `<svg class="op-chart ${large?'large':''}" viewBox="0 0 ${W} ${H}" role="img" aria-label="${a.name}${a.metric}趋势，${state.range}演示数据"><defs><linearGradient id="area-${a.id}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#078fca" stop-opacity=".16"/><stop offset="1" stop-color="#078fca" stop-opacity=".01"/></linearGradient></defs>${[0,.25,.5,.75,1].map(t=>`<path d="M${pad} ${y(high*t)}H${W-pad}" stroke="#e8edf1"/><text x="${pad-7}" y="${y(high*t)+3}" text-anchor="end">${(high*t).toFixed(high<3?1:0)}</text>`).join('')}<path d="M${pad} ${limit}H${W-pad}" stroke="#cf6565" stroke-dasharray="5 4"/><path d="M${pad} ${warning}H${W-pad}" stroke="#d6a440" stroke-dasharray="5 4"/><path d="${path}L${W-pad},${H-pad}H${pad}Z" fill="url(#area-${a.id})"/><path d="${path}" fill="none" stroke="#008fc7" stroke-width="2"/><circle cx="${x(values.length-1)}" cy="${y(values.at(-1))}" r="3.5" fill="#008fc7"/><text x="${pad}" y="${H-9}">${state.range==='6h'?'04:00':'昨日 11:00'}</text><text x="${W/2}" y="${H-9}" text-anchor="middle">${state.range==='6h'?'07:00':'23:00'}</text><text x="${W-pad}" y="${H-9}" text-anchor="end">10:00</text><text x="${W-pad}" y="16" text-anchor="end">${a.unit}</text></svg>`;}
function inspector(){if(!filtered().length)return '<aside class="op-inspector"><div class="op-panel-title"><strong>资产属性</strong></div><div class="op-empty">没有符合筛选条件的资产</div></aside>';const a=selected();const s=status(a);return `<aside class="op-inspector"><div class="op-panel-title"><strong>资产属性</strong><button class="quiet-button" data-op="toggle-inspector" aria-label="关闭资产属性">×</button></div><div class="asset-identity"><span class="asset-type-icon">${icon('settings')}</span><div><h2>${a.name}</h2><p>${a.id} · ${a.classification}</p></div></div><div class="op-detail-tabs">${[['properties','属性'],['documents','文档'],['streams','数据流']].map(([id,t])=>`<button data-inspector-tab="${id}" class="${state.tab===id?'active':''}">${t}</button>`).join('')}</div><div class="op-inspector-body">${state.tab==='properties'?`<div class="asset-state-line">${statusPill(a)}<span>${missing(a).length?'待补齐 '+missing(a).length+' 项':'交付数据完整'}</span></div><h3>基本信息</h3><dl class="op-props"><dt>所属设施</dt><dd>${facility().name}</dd><dt>空间位置</dt><dd>${label('spaces',a.space)}</dd><dt>关联系统</dt><dd><button class="inline-link" data-op="asset-system">${label('systems',a.system)} ↗</button></dd><dt>责任人</dt><dd>${a.responsible}</dd><dt>模型元素</dt><dd>${a.sourceId}</dd></dl><h3>运营资产数据</h3><dl class="op-props">${D.required.slice(0,5).map(([key,title])=>`<dt>${title}</dt><dd>${esc(a[key])||'<span class="missing-field">待补齐</span>'}</dd>`).join('')}</dl><div class="op-inspector-actions"><button class="text-button" data-setup-entry="asset">数据来源与关联</button>${btn('edit-asset','编辑资产','review')}${btn('locate-asset','模型定位','space')}${btn('asset-handover','检查交付','check')}</div>${a.stream?`<div class="asset-mini-reading"><div><span>${a.metric}</span>${statusPill(a)}</div><strong>${valueText(a)} <small>${a.unit}</small></strong>${chart(a)}<button class="inline-link" data-op="asset-stream">打开数据流趋势 ↗</button></div>`:''}`:state.tab==='documents'?`<h3>关联运维资料</h3>${a.manual?`<button class="op-doc-card" data-op="preview-manual">${icon('file')}<span>${esc(a.manual)}<small>运维资料 · V1 · PDF</small></span></button>`:'<div class="op-empty">运维手册待补齐</div>'}<button class="op-doc-card" data-op="design-source">${icon('file')}<span>阶段来源与交付核验<small>核对测量参考、施工记录与模型来源</small></span></button>${btn('construction-source','查看施工设备关联','building')}${btn('link-document','关联文档','folder')}`:`<div class="asset-state-line">${statusPill(a)}<span>${a.connection||'暂无连接'}</span></div><h3>${a.metric||'资产数据流'}</h3><div class="op-big-reading">${valueText(a)} <small>${a.unit}</small></div>${chart(a)}<dl class="op-props"><dt>采样间隔</dt><dd>${a.stream?'5 分钟':'—'}</dd><dt>预警上限</dt><dd>${a.warning??'—'} ${a.unit}</dd><dt>超限上限</dt><dd>${a.limit??'—'} ${a.unit}</dd><dt>最后接收</dt><dd>${a.stream?a.updated:'—'}</dd></dl>${btn('asset-stream','完整趋势','clock')}${btn('thresholds','阈值设置','settings')}`}</div></aside>`;}
const colors={normal:'#308ba7',warning:'#dd9a32',critical:'#ca5c5c',offline:'#9aa6af',none:'#8295a3'};
function iso(x,y,z=0){return [125+x*.96+y*.65,270+x*.30-y*.46-z];}
const pt=p=>p.map(n=>n.toFixed(1)).join(',');
function box(x,y,z,w,d,h,c,attrs=''){const p=[iso(x,y,z),iso(x+w,y,z),iso(x+w,y+d,z),iso(x,y+d,z)],t=[iso(x,y,z+h),iso(x+w,y,z+h),iso(x+w,y+d,z+h),iso(x,y+d,z+h)];return `<g ${attrs}><polygon points="${[p[0],p[1],t[1],t[0]].map(pt).join(' ')}" fill="${c}" stroke="#718a9b" stroke-width=".5"/><polygon points="${[p[1],p[2],t[2],t[1]].map(pt).join(' ')}" fill="${c}" style="filter:brightness(.85)" stroke="#718a9b" stroke-width=".5"/><polygon points="${t.map(pt).join(' ')}" fill="${c}" style="filter:brightness(1.14)" stroke="#718a9b" stroke-width=".5"/></g>`;}
function assetPosition(a,i){if(a.facility==='tunnel')return ({'FAN-01':[150,53,48],'FAN-02':[345,175,48],'PUMP-01':[420,270,16],'PUMP-02':[470,270,16],'CO-01':[245,68,34],'TEMP-01':[445,180,34],'DB-01':[95,265,24],'CAM-01':[20,50,40]})[a.id];if(a.facility==='bridge')return [[250,70,55],[260,110,-25],[455,80,55],[60,200,20],[510,125,50]][i];return [[390,180,40],[80,190,40],[160,75,24],[350,85,65],[190,180,65]][i];}
function scene({small=false,system=false}={}){
 const all=assets(),visible=new Set(filtered().map(a=>a.id));const base=[],lines=[];
 if(state.facility==='tunnel'){
  base.push(box(-20,0,-18,655,340,8,'#e0e7ec'));
  [20,145].forEach(y=>{base.push(box(0,y,0,610,85,7,'#aebbc6'));for(let x=12;x<610;x+=48){const p=iso(x,y+42,8),p2=iso(x+25,y+42,8);lines.push(`<path d="M${pt(p)}L${pt(p2)}" stroke="#f8fafb" stroke-width="2"/>`);}
   for(let x=0;x<=610;x+=61){const pts=Array.from({length:17},(_,j)=>{const angle=Math.PI*j/16;return iso(x,y+42+47*Math.cos(angle),7+63*Math.sin(angle));});base.push(`<path d="M${pts.map(pt).join('L')}" fill="none" stroke="#b1bfca" stroke-width="${x===0||x===610?3:1.2}" opacity=".65"/>`);}
   const p=iso(0,y+5,50),p2=iso(610,y+5,50);lines.push(`<path d="M${pt(p)}L${pt(p2)}" stroke="#6ba7ba" stroke-width="4" opacity=".7"/>`);
  });
  base.push(box(60,245,0,95,62,42,'#cbd8e1'),box(402,245,0,105,65,28,'#cbd8e1'));
  lines.push(`<path d="M${pt(iso(0,135,3))}L${pt(iso(450,135,3))}L${pt(iso(450,270,3))}" fill="none" stroke="#3ca1b6" stroke-width="5" opacity=".7"/>`);
 }else if(state.facility==='bridge'){
  base.push(box(-20,0,-72,650,270,8,'#e3eaf0'));[90,250,430,580].forEach(x=>base.push(box(x,75,-68,24,65,112,'#b6c6d1')));base.push(box(0,30,40,610,140,14,'#c4d1db'));[30,163].forEach(y=>base.push(box(0,y,54,610,5,12,'#8ca4b6')));base.push(box(22,185,0,95,65,40,'#cbd8e1'));for(let x=10;x<610;x+=45)lines.push(`<path d="M${pt(iso(x,100,55))}L${pt(iso(x+25,100,55))}" stroke="#fff" stroke-width="2"/>`);
 }else{
  base.push(box(-20,0,-12,590,300,8,'#e3eaf0'));[[30,30,220,95],[285,30,220,95],[30,150,220,95],[285,150,220,95]].forEach(([x,y,w,d])=>{base.push(box(x,y,0,w,d,8,'#cbd7e0'));base.push(box(x,y,8,w,4,80,'#c4d2de'),box(x,y,8,4,d,80,'#c4d2de'));base.push(box(x,y,43,w,d,5,'#dce5ec'));});lines.push(`<path d="M${pt(iso(65,195,50))}L${pt(iso(420,195,50))}L${pt(iso(420,70,50))}" fill="none" stroke="#58a2b8" stroke-width="5"/>`);
 }
 const nodes=all.map((a,i)=>{const xyz=assetPosition(a,i),[x,y]=iso(...xyz);const s=status(a);let color=colors[s[0]];if(state.color==='system')color=['#438fb1','#55a39b','#b4a562','#8e87b7'][facility().systems.findIndex(r=>r[0]===a.system)%4];const highlight=state.selected===a.id;return `<g class="scene-asset ${highlight?'selected':''} ${visible.has(a.id)?'':'dimmed'}" data-scene-asset="${a.id}" tabindex="0" role="button" aria-label="选择 ${a.name}" style="--asset-color:${color}"><title>${a.name} · ${s[1]}</title>${box(xyz[0]-10,xyz[1]-9,xyz[2]-5,22,20,13,color)}<circle cx="${x}" cy="${y-14}" r="${highlight?11:7}" fill="${color}" stroke="white" stroke-width="2.5"/><path d="M${x} ${y-7}v15" stroke="${color}" stroke-width="2"/>${highlight||system?`<g class="asset-label"><rect x="${x-65}" y="${y-48}" width="130" height="25" rx="3" fill="${highlight?'#167fa9':'#ffffff'}" stroke="${highlight?'#167fa9':'#d9e2e9'}"/><text x="${x}" y="${y-31}" text-anchor="middle" fill="${highlight?'white':'#546d7f'}">${a.id} ${a.stream?valueText(a)+' '+a.unit:''}</text></g>`:''}</g>`;}).join('');
 let tracing='';if(system){const list=all.filter(a=>!state.system||a.system===state.system);const pts=(state.trace==='upstream'?[...list].reverse():list).map(a=>pt(iso(...assetPosition(a,all.indexOf(a)))));tracing=`<path class="trace-path" d="M${pts.join('L')}" fill="none" stroke="#e3a144" stroke-width="5" stroke-dasharray="9 5"/>`;}
 return `<div class="op-scene ${small?'small':''} ${state.mode==='heat'?'heat-mode':''}"><div class="scene-label"><span>${system?'系统路径':state.mode==='heat'?'运行状态着色':'设施模型'}</span><small>${facility().view} · BIM 示意模型</small></div><div class="view-cube"><span>TOP</span><b>前　右</b></div><svg class="facility-svg" viewBox="0 0 1000 600" role="img" aria-label="${facility().name}数字孪生模型示意"><defs><pattern id="op-grid" width="35" height="35" patternUnits="userSpaceOnUse" patternTransform="matrix(1 .3 -.6 .45 180 200)"><path d="M35 0H0V35" fill="none" stroke="#d8e2e9" stroke-width=".7"/></pattern></defs><rect width="1000" height="600" fill="url(#op-grid)" opacity=".55"/><g id="modelTransform" style="transform:scale(${state.zoom});transform-origin:center">${base.join('')}${lines.join('')}${tracing}${nodes}<text x="135" y="445" class="scene-annotation">${state.facility==='tunnel'?'左洞 / 右洞 · 机电系统剖视':state.facility==='bridge'?'主桥结构 · 监测系统':'管理站 · 楼层与设备'}</text><text x="135" y="465" class="scene-annotation small">${facility().location}</text></g></svg><div class="scene-legend">${state.color==='system'?facility().systems.map(([id,n],i)=>`<span><i style="background:${['#438fb1','#55a39b','#b4a562','#8e87b7'][i%4]}"></i>${n}</span>`).join(''):`<span><i style="background:#308ba7"></i>正常</span><span><i style="background:#dd9a32"></i>预警</span><span><i style="background:#ca5c5c"></i>超限</span><span><i style="background:#9aa6af"></i>离线</span><span><i style="background:#8295a3"></i>未接入</span>`}</div>${!small?`<div class="scene-navigation"><button data-op="zoom-out" aria-label="缩小">−</button><button data-op="zoom-reset">${Math.round(state.zoom*100)}%</button><button data-op="zoom-in" aria-label="放大">＋</button><span></span><button data-op="toggle-inspector" title="资产属性">${icon('panel')}</button><button data-op="views" title="保存视图">${icon('camera')}</button></div>`:''}</div>`;
}
function twin(){host.innerHTML=top('查看器','在空间中浏览资产、系统与运行状态')+`<div class="op-view-toolbar"><button class="quiet-button" data-op="toggle-filters" aria-label="筛选面板">${icon('panel')}</button><button class="text-button" data-op="views">${icon('camera')}${state.view} ⌄</button><span class="toolbar-divider"></span><button class="text-button ${state.mode==='model'?'active':''}" data-mode="model">模型</button><button class="text-button ${state.mode==='heat'?'active':''}" data-mode="heat">状态着色</button><span class="toolbar-spacer"></span><label>着色依据 <select id="colorBy"><option value="status" ${state.color==='status'?'selected':''}>运行状态</option><option value="system" ${state.color==='system'?'selected':''}>系统分类</option></select></label><button class="quiet-button" data-op="toggle-inventory" aria-label="切换底部资产清单">${icon('file')}</button></div><div class="op-twin ${!state.filterOpen?'hide-filter':''} ${!state.inspector?'hide-inspector':''} ${!state.inventory?'hide-inventory':''}">${filterPanel()}<div class="twin-scene">${scene()}</div>${inspector()}<section class="twin-inventory"><div class="inventory-title"><strong>资产清单 <small>(${filtered().length})</small></strong><span>当前筛选范围</span><span class="toolbar-spacer"></span><label><input type="checkbox" checked disabled> 跟随选择</label>${btn('inventory-full','展开清单','panel')}</div><div class="op-table-scroll">${assetTable(filtered(),true)}</div></section></div><footer class="op-timebar"><span>${icon('clock')}历史时间</span><input type="range" id="timeSlider" min="0" max="23" value="${state.time}" aria-label="历史时间快照"><b>${state.time===23?'运营快照':`${state.time+11>=24?'今日':'昨日'} ${String((state.time+11)%24).padStart(2,'0')}:00`}</b><span>10-11 预置快照 · 非实时采集</span></footer>`;$('#colorBy').onchange=e=>{state.color=e.target.value;render();};$('#timeSlider').oninput=e=>{state.time=+e.target.value;render();};}
function inventory(){host.innerHTML=top('资产清单','按分类、空间和系统查找资产，维护运营属性')+subTools(`<button class="cde-primary" data-op="import-assets">${icon('upload')}导入资产数据</button>${btn('export-assets','导出','file')}${btn('reset','重置筛选')}`,`<select id="inventorySystem" class="filter-select" aria-label="按系统筛选"><option value="">全部系统</option>${facility().systems.map(([id,n])=>`<option value="${id}" ${state.system===id?'selected':''}>${n}</option>`).join('')}</select><label class="local-search">${icon('search')}<input id="assetSearch" value="${esc(state.search)}" placeholder="资产名称 / 编码" aria-label="搜索资产清单"></label>`)+`<div class="op-list-layout ${state.inspector?'with-inspector':''}"><div class="op-full-table">${assetTable(filtered())}</div>${state.inspector?inspector():''}</div><footer class="op-footer"><span>共 ${filtered().length} 个资产 · ${facility().name}</span><span>点击资产查看属性，可从属性面板定位到模型</span></footer>`;$('#inventorySystem').onchange=e=>{state.system=e.target.value;render();};$('#assetSearch').oninput=e=>{state.search=e.target.value;$('.op-full-table').innerHTML=assetTable(filtered());if($('.op-inspector'))$('.op-inspector').outerHTML=inspector();$('.op-footer span').textContent=`共 ${filtered().length} 个资产 · ${facility().name}`;};}
function facilities(){const selectedFacility=facility();host.innerHTML=top('设施','从项目设施进入数字孪生、已保存视图与仪表板')+`<div class="op-tabbar"><button class="active" data-facility-tab="owned">我方管理 (${D.facilities.length})</button><button data-facility-tab="shared">共享给我 (0)</button><button data-facility-tab="transferred">已转出 (0)</button><span class="toolbar-spacer"></span><button class="cde-primary" data-op="new-facility">＋ 新建设施</button></div><div class="facility-filterbar"><label>类型 <select id="facilityType"><option value="">全部类型</option>${[...new Set(D.facilities.map(f=>f.type))].map(t=>`<option>${t}</option>`).join('')}</select></label><input id="facilitySearch" aria-label="搜索设施" placeholder="搜索设施名称"></div><div class="facilities-layout"><section class="facility-list">${D.facilities.map(f=>{const fa=D.assets.filter(a=>a.facility===f.id);return `<button class="facility-card ${state.facility===f.id?'selected':''}" data-facility-card="${f.id}"><span class="facility-card-copy"><small>${f.type} · XX高速公路</small><strong>${f.name}</strong><span>${f.subtitle}</span><dl><dt>资产</dt><dd>${fa.length}</dd><dt>数据流</dt><dd>${fa.filter(a=>a.stream).length}</dd><dt>管理单位</dt><dd>${f.owner}</dd></dl><span class="facility-tag">运营中</span></span><span class="facility-illustration ${f.id}">${miniFacility(f.id)}</span></button>`;}).join('')}</section><aside class="facility-summary"><h2>${selectedFacility.name}</h2><p>${selectedFacility.location}</p><button class="cde-primary" data-op="open-facility">打开设施 ${icon('arrow')}</button><h3>仪表板 <small>1</small></h3><button class="op-saved-row" data-op="open-dashboard">${icon('panel')}资产运行状态 ${icon('arrow')}</button><h3>已保存视图</h3>${D.views.filter(v=>state.facility==='tunnel'||v.id!=='vent').map(v=>`<button class="op-saved-row" data-view="${v.id}">${icon('camera')}<span>${v.name}</span></button>`).join('')}<h3>资产数据完整性</h3>${completeMeter(assets())}</aside></div>`;const apply=()=>{const q=$('#facilitySearch').value.trim().toLowerCase(),type=$('#facilityType').value;$$('[data-facility-card]').forEach(c=>{const f=D.facilities.find(f=>f.id===c.dataset.facilityCard);c.hidden=!!((type&&f.type!==type)||(q&&!f.name.toLowerCase().includes(q)));});$('.facility-search-empty')?.remove();if(!$$('[data-facility-card]').some(c=>!c.hidden))$('.facility-list').insertAdjacentHTML('beforeend','<div class="op-empty facility-search-empty">没有符合条件的设施</div>');};$('#facilitySearch').oninput=apply;$('#facilityType').onchange=apply;}
function miniFacility(id){return `<svg viewBox="0 0 320 210" aria-hidden="true"><path d="m20 145 170-90 110 62-169 90Z" fill="#dce6ed" stroke="#b9cbd8"/>${id==='tunnel'?'<path d="m50 137 139-74q36-22 69 24l-139 75q-34-46-69-25Zm39 20 139-74" fill="#b9ccd9" stroke="#7197b0" stroke-width="2"/><path d="m116 159 144-73" stroke="#4298b7" stroke-width="7"/>':id==='bridge'?'<path d="m43 121 176-68 40 28-175 78Z" fill="#b8ccd9" stroke="#789bb1"/><path d="M99 143v37m57-58v32m58-55v33" stroke="#8aa9bd" stroke-width="13"/><path d="m61 123 173-68" stroke="#fff" stroke-width="2"/>':'<path d="m70 126 113-60 66 38v51l-114 60-65-37Z" fill="#9ebacc"/><path d="m70 126 66 39 113-61-66-38Z" fill="#d9e6ed"/><path d="M136 165v50m-48-81v27m21-15v28m48-12v27m27-42v27m27-40v27" stroke="#f6fafc" stroke-width="5"/>'}</svg>`;}
function completeMeter(list){const total=list.length*D.required.length,filled=total-list.reduce((n,a)=>n+missing(a).length,0),percent=Math.round(filled/total*100);return `<div class="complete-meter"><strong>${percent}<small>%</small></strong><span>${filled} / ${total} 项参数已填写</span><div><i style="width:${percent}%"></i></div></div>`;}
function spaces(){host.innerHTML=top('空间','通过设施空间定位设备，并查看关联资产与状态')+subTools(btn('space-template','空间层级','layers'),'')+`<div class="op-spaces-layout"><section class="op-space-cards">${facility().spaces.map(([id,n])=>{const aa=assets().filter(a=>a.space===id),warning=aa.filter(a=>['warning','critical','offline'].includes(status(a)[0])).length;return `<button class="space-card ${state.space===id?'selected':''}" data-open-space="${id}"><span class="space-outline">${icon('layers')}</span><div><small>${facility().name}</small><h2>${n}</h2><p>${aa.length} 个资产 · ${aa.filter(a=>a.stream).length} 条数据流</p></div><span class="op-status ${warning?'warning':'normal'}">${warning?warning+' 项需关注':'状态正常'}</span></button>`;}).join('')}</section><section class="space-preview"><header><h3>${state.space?label('spaces',state.space):'全部空间'}</h3>${btn('space-to-twin','在模型中查看','space')}</header>${scene({small:true})}<div class="op-table-scroll">${assetTable(filtered(),true)}</div></section></div>`;}
function systems(){if(!state.system)state.system=facility().systems[0][0];const aa=assets().filter(a=>a.system===state.system);if(!aa.some(a=>a.id===state.selected))state.selected=aa[0].id;host.innerHTML=top('系统','查看系统连接关系、路径与服务空间')+subTools(`<label class="op-select-label">系统<select class="filter-select" id="traceSystem">${facility().systems.map(([id,n])=>`<option value="${id}" ${id===state.system?'selected':''}>${n}</option>`).join('')}</select></label><span class="toolbar-divider"></span><button class="text-button ${state.trace==='downstream'?'active':''}" data-trace="downstream">下游路径</button><button class="text-button ${state.trace==='upstream'?'active':''}" data-trace="upstream">上游路径</button>`,`<span class="op-muted">${aa.length} 个关联资产 · ${new Set(aa.map(a=>a.space)).size} 个服务空间</span>`)+`<div class="op-system-layout"><div class="system-scene">${scene({system:true})}</div><aside class="system-topology"><h3>${label('systems',state.system)}</h3><p>起点：${selected().name}</p><div class="topology-root">${icon('bridge')}${label('systems',state.system)}</div><div class="topology-branches">${(state.trace==='downstream'?aa:[...aa].reverse()).map(a=>`<button class="topology-node ${a.id===state.selected?'active':''}" data-select="${a.id}"><span>${a.name}<small>${label('spaces',a.space)}</small></span>${statusPill(a)}</button>`).join('')}</div><h3>服务空间</h3>${[...new Set(aa.map(a=>a.space))].map(sp=>`<button class="op-saved-row" data-open-space="${sp}">${icon('layers')}${label('spaces',sp)}</button>`).join('')}</aside></div>`;$('#traceSystem').onchange=e=>{state.system=e.target.value;state.selected=assets().find(a=>a.system===state.system).id;render();};}
function streams(){const a=selected().stream?selected():assets().find(a=>a.stream);state.selected=a.id;host.innerHTML=top(state.streamTab==='connections'?'连接':'数据流','关联设备与时序读数，结合阈值查看当前及历史状态')+`<div class="op-tabbar"><button class="${state.streamTab!=='connections'?'active':''}" data-stream-tab="streams">数据流 (${assets().filter(a=>a.stream).length})</button><button class="${state.streamTab==='connections'?'active':''}" data-stream-tab="connections">连接配置</button><span class="toolbar-spacer"></span>${btn('new-connection','接入传感器','share')}</div>${state.streamTab==='connections'?`<div class="op-connection-table"><table class="op-table"><thead><tr><th>连接名称</th><th>宿主资产</th><th>空间</th><th>来源</th><th>采样间隔</th><th>数据状态</th><th>操作</th></tr></thead><tbody>${assets().filter(a=>a.stream).map(a=>`<tr><td><strong>${a.connection}</strong><small>${a.metric}</small></td><td>${a.name}</td><td>${label('spaces',a.space)}</td><td>运营网关 · 示例</td><td>5 分钟</td><td>${statusPill(a)}</td><td><button class="inline-link" data-connection="${a.id}">查看配置</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="op-stream-layout"><aside class="stream-list"><div class="op-panel-title"><strong>设施数据流</strong><small>${assets().filter(a=>a.stream).length} 条</small></div>${assets().filter(a=>a.stream).map(a=>`<button class="stream-item ${a.id===state.selected?'selected':''}" data-stream="${a.id}"><div><strong>${a.name}</strong>${statusPill(a)}</div><p>${a.metric} <b>${valueText(a)} <small>${a.unit}</small></b></p></button>`).join('')}</aside><section class="stream-detail"><header><div><small>${a.stream} · ${label('spaces',a.space)}</small><h2>${a.name} / ${a.metric}</h2></div>${statusPill(a)}</header><div class="stream-reading-row"><div class="op-big-reading">${valueText(a)} <small>${a.unit}</small></div><div><small>最后接收</small><strong>${a.updated}</strong></div><div><small>预警 / 超限</small><strong>${a.warning} / ${a.limit} ${a.unit}</strong></div><span class="toolbar-spacer"></span>${btn('thresholds','阈值设置','settings')}</div><div class="chart-range"><button data-range="6h" class="${state.range==='6h'?'active':''}">6 小时</button><button data-range="24h" class="${state.range==='24h'?'active':''}">24 小时</button><span class="toolbar-spacer"></span><span><i class="chart-key"></i>读数 <i class="chart-key warning"></i>预警线 <i class="chart-key critical"></i>超限线</span></div>${chart(a,{large:true})}<div class="stream-context"><section><h3>关联对象</h3><dl class="op-props"><dt>宿主资产</dt><dd>${a.id}</dd><dt>系统</dt><dd>${label('systems',a.system)}</dd><dt>连接</dt><dd>${a.connection}</dd></dl>${btn('stream-to-twin','在模型中定位','space')}</section></div></section></div>`}`;}
function dashboard(){const aa=assets(),ss=aa.filter(a=>a.stream),attention=ss.filter(a=>['warning','critical'].includes(status(a)[0])),offline=ss.filter(a=>!a.online),complete=aa.filter(a=>!missing(a).length);const graph=ss.find(a=>status(a)[0]==='warning')||ss[0];host.innerHTML=top('仪表板','结合资产状态、数据趋势与交付质量了解设施运行情况')+subTools(btn('open-facility','空间与资产','space')+btn('configure-dashboard','配置看板','settings'),'<span class="op-muted">预置运营快照 · 2026-10-11 10:00</span>')+`<div class="dashboard-scroll"><div class="op-kpis">${[['资产数量',aa.length,'当前设施资产','inventory',''],['需关注数据流',attention.length,'读数超过演示阈值','streams','amber'],['离线连接',offline.length,'需要检查数据来源','streams','gray'],['交付完整资产',complete.length+' / '+aa.length,'必填参数与运维手册','handover','']].map(r=>`<button class="op-kpi ${r[4]}" data-goto="${r[3]}"><span>${r[0]}</span><strong>${r[1]}</strong><small>${r[2]} ↗</small></button>`).join('')}</div><div class="dashboard-grid"><section class="dashboard-panel"><header><h3>设施空间与运行状态</h3>${btn('open-facility','打开孪生','space')}</header>${scene({small:true})}</section><section class="dashboard-panel"><header><div><h3>${graph.name} · ${graph.metric}</h3><small>24 小时读数</small></div><strong class="dashboard-reading">${valueText(graph)} <small>${graph.unit}</small></strong></header>${chart(graph,{large:true})}<div class="dashboard-chart-foot">预警 ${graph.warning} / 超限 ${graph.limit} ${graph.unit}<button class="inline-link" data-stream="${graph.id}">查看完整趋势 ↗</button></div></section><section class="dashboard-panel"><header><h3>需关注的资产</h3><span class="op-muted">${attention.length+offline.length} 项</span></header>${[...attention,...offline].length?[...attention,...offline].map(a=>`<button class="attention-row" data-stream="${a.id}"><span>${a.name}<small>${a.metric} · ${label('spaces',a.space)}</small></span>${statusPill(a)}<strong>${valueText(a)} <small>${a.unit}</small></strong></button>`).join(''):'<div class="op-empty">当前没有需关注项</div>'}</section><section class="dashboard-panel"><header><h3>数字交付完整性</h3>${btn('asset-handover','查看缺失项')}</header>${completeMeter(aa)}<div class="dashboard-delivery">${missingTotal(aa)} 项参数待补齐 · ${aa.filter(a=>missing(a).length).length} 个资产受影响</div></section></div></div>`;}
const missingTotal=aa=>aa.reduce((n,a)=>n+missing(a).length,0);
function documents(){const aa=assets();host.innerHTML=top(state.docTab==='docs'?'文档':'模型文件','管理源模型，并将运维手册、交付资料关联到资产')+`<div class="op-tabbar"><button class="${state.docTab!=='docs'?'active':''}" data-doc-tab="models">源模型 (1)</button><button class="${state.docTab==='docs'?'active':''}" data-doc-tab="docs">关联文档 (${aa.filter(a=>a.manual).length})</button><span class="toolbar-spacer"></span>${btn(state.docTab==='docs'?'link-document':'import-model',state.docTab==='docs'?'关联文档':'导入模型','upload')}</div><div class="op-document-content">${state.docTab==='docs'?`<table class="op-table"><thead><tr><th>文档名称</th><th>关联资产</th><th>类型</th><th>版本</th><th>操作</th></tr></thead><tbody>${aa.filter(a=>a.manual).map(a=>`<tr><td><strong>${esc(a.manual)}</strong><small>运维资料 / ${a.id}</small></td><td>${a.name}</td><td>使用维护手册</td><td><span class="version-pill">V1</span></td><td><button class="inline-link" data-document="${a.id}">预览</button></td></tr>`).join('')}</tbody></table>`:`<div class="source-model-row"><span class="model-file-icon">${facility().model.endsWith('ifc')?'IFC':'RVT'}</span><div><h2>${facility().model}</h2><p>来源：预置竣工模型示例 / ${facility().name} · 交付包待关联</p><span class="op-muted">场景：后续运营快照　版本：V1　预置时间：2026-10-10 16:30</span></div><span class="toolbar-spacer"></span><span class="op-status normal">预置模型</span>${btn('model-properties','模型详情','panel')}</div><div class="model-overview"><div>${scene({small:true})}</div><aside><h3>模型组织</h3><dl class="op-props"><dt>资产</dt><dd>${aa.length} 个</dd><dt>空间</dt><dd>${facility().spaces.length} 个</dd><dt>系统</dt><dd>${facility().systems.length} 个</dd><dt>默认可见</dt><dd>是</dd></dl>${btn('asset-handover','查看数据检查','review')}</aside></div>`}</div>`;}
function handover(){const aa=assets();host.innerHTML=top('数据检查','指定信息要求、映射与补齐资产数据，再验证交付完整性')+`<div class="handover-flow"><div><b>01</b><span>指定数据要求</span><button class="inline-link" data-op="template">查看模板</button></div><i>›</i><div><b>02</b><span>采集与映射</span><button class="inline-link" data-op="mapping">参数映射</button></div><i>›</i><div class="active"><b>03</b><span>验证并移交</span><button class="inline-link" data-op="verify">重新检查</button></div></div><div class="handover-summary">${completeMeter(aa)}<div><h3>${missingTotal(aa)?'有 '+missingTotal(aa)+' 项信息待补齐':'交付数据完整'}</h3><p>${aa.filter(a=>missing(a).length).length} 个资产受影响 · 模板：公路机电资产基础模板</p></div><span class="toolbar-spacer"></span><button class="cde-primary" data-op="verify">${icon('review')}检查交付</button></div><div class="handover-table"><table class="op-table"><thead><tr><th>资产名称 / 编码</th><th>分类</th><th>必填参数</th><th>缺失项</th><th>状态</th><th>操作</th></tr></thead><tbody>${aa.map(a=>`<tr><td><strong>${a.name}</strong><small>${a.id}</small></td><td>${a.classification}</td><td>${D.required.length-missing(a).length} / ${D.required.length}</td><td>${missing(a).map(r=>r[1]).join('、')||'—'}</td><td><span class="op-status ${missing(a).length?'warning':'normal'}">${missing(a).length?'待补齐':'完整'}</span></td><td><button class="inline-link" data-edit="${a.id}">${missing(a).length?'补齐数据':'查看数据'}</button></td></tr>`).join('')}</tbody></table></div><footer class="op-footer"></footer>`;}
function history(){host.innerHTML=top('历史记录','追溯设施模型、资产属性与连接配置的变更')+subTools('<span class="op-muted">设施活动 · 最近 7 天</span>',btn('export-history','导出记录','file'))+`<div class="op-document-content"><table class="op-table"><thead><tr><th>时间</th><th>操作</th><th>对象</th><th>人员</th><th>来源</th></tr></thead><tbody>${[['10-11 10:00','查看运营快照',facility().name,'张工','Autodesk Tandem'],['10-11 09:40','配置监测阈值',assets().find(a=>a.stream).id,'王工','连接与数据流'],['10-10 17:20','补充资产属性',assets()[0].id,'李工','资产清单'],['10-10 16:30','导入竣工模型',facility().model,'张工','成果资料库'],['10-10 15:00','应用设施模板','公路机电资产基础模板','张工','数据检查']].map(r=>`<tr>${r.map(v=>`<td>${v}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
function home(){host.innerHTML=top('主页')+`<div class="tandem-home"><h2>最近访问</h2><div class="tandem-recent-grid"><section><span class="tandem-card-label">设施</span><h3>${esc(facility().name)}</h3><div class="tandem-recent-image">${miniFacility(state.facility)}</div><button class="cde-primary" data-op="open-facility">打开设施</button></section><section><span class="tandem-card-label">已保存视图</span><h3>${esc(facility().view)}</h3><dl class="op-props"><dt>资产</dt><dd>${assets().length}</dd><dt>空间</dt><dd>${facility().spaces.length}</dd><dt>系统</dt><dd>${facility().systems.length}</dd></dl><button class="text-button" data-op="open-facility">打开查看器</button></section><section><span class="tandem-card-label">仪表板</span><h3>资产运行状态</h3>${completeMeter(assets())}<button class="text-button" data-op="open-dashboard">打开仪表板</button></section></div><h2>设施</h2><div class="tandem-home-list">${D.facilities.map(f=>`<button data-facility="${f.id}">${icon('building')}<span><strong>${esc(f.name)}</strong><small>${esc(f.owner)}</small></span>${icon('arrow')}</button>`).join('')}</div></div>`;}
function manage(){const kind=state.manageTab||'templates',definitions={templates:['设施模板','名称','适用分类','必填参数'],classifications:['分类体系','分类','资产数量','参数集'],parameters:['参数','名称','数据类型','要求']};const rows=kind==='templates'?[['公路机电资产基础模板','机电设施',D.required.length+' 项']]:kind==='classifications'?[...new Set(D.assets.map(a=>a.classification))].map(c=>[c,D.assets.filter(a=>a.classification===c).length,'公路机电资产基础参数']):D.required.map(([k,t])=>[t,k==='commissioned'||k==='warranty'?'日期':'文本','必填']);host.innerHTML=top('管理')+`<div class="op-tabbar">${Object.entries(definitions).map(([id,d])=>`<button data-manage-tab="${id}" class="${kind===id?'active':''}">${d[0]}</button>`).join('')}</div><div class="op-document-content"><table class="op-table"><thead><tr>${definitions[kind].slice(1).map(h=>`<th>${h}</th>`).join('')}<th>操作</th></tr></thead><tbody>${rows.map(row=>`<tr>${row.map(v=>`<td>${esc(v)}</td>`).join('')}<td><button class="text-button" data-op="template">查看定义</button></td></tr>`).join('')}</tbody></table></div>`;host.querySelectorAll('[data-manage-tab]').forEach(b=>b.onclick=()=>{state.manageTab=b.dataset.manageTab;render();});}
function setup(){host.innerHTML=top('接入配置','从源模型和交付资料到运营资产，再连接监测数据')+'<div id="opsSetupWorkspace"></div>';OPS_SETUP.render($('#opsSetupWorkspace'));}
function render(){let view=location.hash.slice(1)||'facilities';if(!nav.some(n=>n[0]===view))view='facilities';navRender(view);$$('[data-opsnav]').forEach(a=>{a.classList.toggle('active',a.dataset.opsnav===view);a.dataset.opsnav===view?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current');});document.title=nav.find(n=>n[0]===view)[2]+'｜Autodesk Tandem';({home,setup,facilities,manage,twin,inventory,spaces,systems,streams:()=>{state.streamTab="streams";streams();},connections:()=>{state.streamTab="connections";streams();},dashboard,documents:()=>{state.docTab="models";documents();},docs:()=>{state.docTab="docs";documents();},handover,history})[view]();hydrate(host);if($('#opGlobalSearch'))$('#opGlobalSearch').onkeydown=e=>{if(e.key==='Enter'){state.search=e.target.value;state.inspector=false;go('inventory');}};}
function editAsset(){const a=selected();const d=dialog('编辑资产数据',`<div class="dialog-file">${icon('settings')}<strong>${esc(a.name)}</strong><span>${a.id}</span></div>${D.required.map(([key,t])=>`<label class="field">${t}<input name="${key}" value="${esc(a[key])}" placeholder="${t}${a[key]?'':'（待补齐）'}"></label>`).join('')}`,'保存属性',el=>{D.required.forEach(([k])=>a[k]=$(`[name="${k}"]`,el).value.trim());render();notify('已更新本次演示中的资产数据');});}
function previewManual(){const a=selected();dialog('运维文档预览',`<div class="manual-preview"><small>运维资料 · V1</small><h2>${esc(a.manual||'设备使用维护说明书')}</h2><div class="manual-stamp">资料示例</div><h3>关联资产</h3><p>${a.id} · ${a.name}</p><h3>设备基础信息</h3><p>制造商：${esc(a.manufacturer)||'待补齐'}<br>型号：${esc(a.model)||'待补齐'}<br>所属空间：${label('spaces',a.space)}</p><h3>维护记录与资料</h3><p>正式文档可包含产品说明、调试报告、保养要求和厂家联系信息。此页用于展示文档与资产的关联关系。</p></div>`,'关闭',()=>{});}
function thresholdDialog(){const a=selected();if(!a.stream){notify('该资产尚未配置数据流');return;}const d=dialog('数据流阈值',`<div class="dialog-file">${icon('clock')}${a.name} · ${a.metric}</div><label class="field">预警上限（${a.unit}）<input id="warnValue" type="number" step="any" value="${a.warning}"></label><label class="field">超限上限（${a.unit}）<input id="limitValue" type="number" step="any" value="${a.limit}"></label><p>读数高于预警上限显示预警，高于超限上限显示超限；离线数据单独显示。</p><p id="thresholdError" class="missing-field" role="alert"></p>`,'应用阈值',()=>{});$('#dialogConfirm',d).onclick=()=>{const w=+$('#warnValue').value,l=+$('#limitValue').value;if(!$('#warnValue').value||!$('#limitValue').value||!Number.isFinite(w)||!Number.isFinite(l)||w<0||l<=w){$('#thresholdError').textContent='请填写有效数值，超限上限必须大于预警上限。';return;}a.warning=w;a.limit=l;render();d.close();notify('已应用演示阈值，状态与看板同步更新');};}
function viewsDialog(){const available=D.views.filter(v=>state.facility==='tunnel'||v.id!=='vent');const d=dialog('已保存视图',`<p>保存和恢复当前筛选条件、模型着色与视角。</p><div class="saved-view-grid">${available.map(v=>`<button class="saved-view-card" data-view="${v.id}">${icon('camera')}<strong>${esc(v.name)}</strong><small>${v.system?'按系统筛选':v.status?'按状态筛选':'全部空间与资产'}</small></button>`).join('')}</div><label class="field">保存当前视图<input id="saveViewName" placeholder="输入视图名称"></label>`,'保存当前视图',el=>{const name=$('#saveViewName',el).value.trim();if(!name)return;D.views.push({id:'custom-'+D.views.length,name,system:state.system,space:state.space,status:state.status,color:state.color,zoom:state.zoom,search:state.search});state.view=name;render();notify('已保存本次演示中的视图');});}
function applyView(id){const v=D.views.find(v=>v.id===id);if(!v)return;resetFilters();state.system=v.system;state.space=v.space;state.status=v.status;state.search=v.search||'';state.color=v.color||'status';state.zoom=v.zoom||1;state.selected=filtered()[0]?.id||assets()[0].id;state.view=v.name;$('#cdeDialog')?.close();go('twin');}
function downloadCsv(rows,name){const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const actions={
 'facility-picker':()=>dialog('切换设施',D.facilities.map(f=>`<button class="op-saved-row" data-facility="${f.id}">${icon('building')}<strong>${f.name}</strong><span>${f.type}</span>${state.facility===f.id?'✓':''}</button>`).join(''),'关闭',()=>{}),
 'open-facility':()=>{resetFilters();go('twin');},'open-dashboard':()=>{resetFilters();go('dashboard');},
 'inventory-full':()=>go('inventory'),'toggle-inspector':()=>{state.inspector=!state.inspector;render();},
 'toggle-filters':()=>{state.filterOpen=!state.filterOpen;render();},'toggle-inventory':()=>{state.inventory=!state.inventory;render();},
 reset:()=>{resetFilters();state.view='设施总览';render();},views:viewsDialog,
 'zoom-in':()=>{state.zoom=Math.min(1.6,state.zoom+.1);render();},'zoom-out':()=>{state.zoom=Math.max(.6,state.zoom-.1);render();},'zoom-reset':()=>{state.zoom=1;render();},
 'edit-asset':editAsset,'locate-asset':()=>{state.inspector=true;go('twin');},'preview-manual':previewManual,'asset-handover':()=>go('handover'),
 'asset-system':()=>{state.system=selected().system;state.space='';state.status='';go('systems');},
 'asset-stream':()=>{if(!selected().stream){notify('该资产未配置数据流');return;}state.streamTab='streams';go('streams');},
 'stream-to-twin':()=>{resetFilters();state.inspector=true;state.tab='streams';go('twin');},
 'space-to-twin':()=>{state.inspector=false;go('twin');},
 thresholds:thresholdDialog,
 'design-source':()=>LC.open({facility:state.facility,asset:state.selected}),
 'construction-source':()=>{if(LC.assets[state.selected])location.href=LC.buildUrl(state.selected);else LC.open();},
 'link-document':()=>dialog('关联运维文档',`<div class="dialog-file">${icon('settings')}${selected().name}</div><label class="field">文档来源<select><option>项目成果资料库</option><option>本地文件（展示）</option></select></label><label class="field">文档名称<input id="manualName" value="${esc(selected().classification)}使用维护说明书.pdf"></label><label class="field">关联字段<select><option>运维手册</option></select></label>`,'关联文档',d=>{const name=$('#manualName',d).value.trim();if(name)selected().manual=name;render();notify('已建立本次演示中的文档关联');}),
 'new-facility':()=>dialog('新建设施','<label class="field">设施名称<input placeholder="例如：XX高速隧道机电设施"></label><label class="field">设施类型<select><option>隧道</option><option>桥梁</option><option>站房</option></select></label><label class="field">设施模板<select><option>公路机电资产基础模板</option></select></label><p>下一步：导入模型，完成分类和参数映射。</p>','查看现有示例',()=>go('twin')),
 'import-model':()=>dialog('导入源模型','<label class="field">导入来源<select><option>项目成果资料库</option><option>本地 Revit / IFC 文件</option></select></label><label class="field">模型<input value="'+facility().model+'"></label><label class="field">模型阶段<select><option>竣工交付</option></select></label><label class="radio-row"><input type="checkbox" checked>在默认视图中显示</label><p>模型导入后，需要分类、映射参数并核对资产信息。</p>','查看已导入示例',()=>{state.docTab='models';go('documents');}),
 'model-properties':()=>dialog('源模型详情',`<div class="dialog-file">${icon('file')}${facility().model}</div><dl class="op-props"><dt>来源项目</dt><dd>XX高速公路</dd><dt>交付版本</dt><dd>V1</dd><dt>模型阶段</dt><dd>竣工交付</dd><dt>资产数量</dt><dd>${assets().length}</dd><dt>导入方式</dt><dd>预置模型示例 · 尚未关联已验收交付包</dd></dl>`,'关闭',()=>{}),
 'import-assets':()=>dialog('导入资产数据','<div class="dropzone">'+icon('upload')+'<br>选择 CSV / XLSX 资产数据表<label class="field"><input type="file" accept=".csv,.xlsx" aria-label="选择资产导入文件"></label></div><p>以资产编码匹配现有资产，随后映射参数字段。</p>','查看参数映射',()=>actions.mapping()),
 'export-assets':()=>downloadCsv([['资产编码','名称','分类','空间','系统','运行状态','读数','单位'],...filtered().map(a=>[a.id,a.name,a.classification,label('spaces',a.space),label('systems',a.system),status(a)[1],valueAt(a)??'',a.unit])],facility().name+'-资产清单-示例.csv'),
 'new-connection':()=>dialog('创建连接',`<label class="field">连接名称<input value="${selected().id}-设备连接"></label><label class="field">宿主资产<select>${assets().map(a=>`<option>${a.id} · ${a.name}</option>`).join('')}</select></label><label class="field">采样频率<select><option>5 分钟</option><option>15 分钟</option></select></label><label class="field">来源<select><option>运营数据网关</option><option>Tandem Connect / API 接入展示</option></select></label><p>连接关联宿主资产、空间和系统，数据流记录对应的时序读数。</p>`,'查看现有连接',()=>{state.streamTab='connections';go('streams');}),
 template:()=>dialog('设施模板与分类要求',`<h3>公路机电资产基础模板</h3><p>根据资产类别定义交付时需要提供的信息。</p><div class="template-classifications">${[...new Set(assets().map(a=>a.classification))].map(c=>`<span>${c}</span>`).join('')}</div><table class="op-table"><thead><tr><th>参数</th><th>类型</th><th>要求</th></tr></thead><tbody>${D.required.map(([k,t])=>`<tr><td>${t}</td><td>${k==='manual'?'文档链接':k==='warranty'||k==='commissioned'?'日期':'文本'}</td><td>必填</td></tr>`).join('')}</tbody></table>`,'查看参数映射',()=>actions.mapping()),
 mapping:()=>dialog('参数映射',`<h3>模型属性 → 运营资产参数</h3><table class="op-table"><thead><tr><th>来源模型属性</th><th>目标参数</th><th>状态</th></tr></thead><tbody>${[['Manufacturer','制造商'],['Model','设备型号'],['SerialNumber','序列号'],['CommissioningDate','投运日期']].map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td><span class="op-status normal">已映射</span></td></tr>`).join('')}<tr><td>手动补充 / 文档关联</td><td>质保日期、运维手册</td><td>待验证</td></tr></tbody></table><p>参数映射为配置展示，当前未读取真实 BIM 属性。</p>`,'查看交付检查',()=>go('handover')),
 verify:()=>dialog('交付完整性检查',`${completeMeter(assets())}<p>${missingTotal(assets())?'仍有 '+missingTotal(assets())+' 项参数待补齐，涉及 '+assets().filter(a=>missing(a).length).length+' 个资产。':'所有示例必填参数均已填写。'}</p><p>这里只检查必填字段及文档名称是否填写，不验证附件内容、数据准确性或接收方验收。</p>`,'查看检查清单',()=>go('handover')),
 'space-template':()=>dialog('设施空间层级',`<h3>${facility().name}</h3>${facility().spaces.map(([id,n])=>`<p>└　${n} · ${assets().filter(a=>a.space===id).length} 个资产</p>`).join('')}<p>本原型针对公路场景采用洞区、泵房、配电室或楼层划分。</p>`,'关闭',()=>{}),
 'configure-dashboard':()=>dialog('配置仪表板','<h3>看板内容</h3>'+['设施模型与状态','重点数据流趋势','需关注的资产','数字交付完整性'].map(t=>`<label class="radio-row"><input type="checkbox" checked>${t}</label>`).join('')+'<p>此页面展示卡片配置方式。</p>','返回看板',()=>go('dashboard')),
 'export-history':()=>notify('活动导出入口展示，当前记录为静态样例'),
 sources:()=>dialog('参考与演示说明',`<h3>以 Tandem 的设施数字孪生工作流为参考</h3><p>设施 → 模型、空间与资产 → 分类与参数 → 系统关系 → 连接与数据流 → 运行分析。</p><p>本项目将这些界面逻辑适配为公路运营场景，沿用Forma Data Management的公共界面风格。模型为程序绘制的示意图，传感器读数为固定示例，未连接真实 BIM、IoT 或设备控制系统。</p><p>设施模型导入、运营参数补齐与验证是独立步骤，不表示Forma Data Management成果会自动实时同步。</p><p><a href="https://help.autodesk.com/cloudhelp/ENU/Tandem-Getting-Started/files/tandem-navigate-ui.html" target="_blank" rel="noopener">Tandem 官方界面说明 ↗</a></p><p><a href="https://help.autodesk.com/cloudhelp/ENU/Tandem-Getting-Started/files/tandem-key-concepts.html" target="_blank" rel="noopener">Tandem 关键概念 ↗</a></p>`,'知道了',()=>{})
};
// Delegate events so every route and context panel shares the same selection state.
document.addEventListener('click',e=>{
 const el=e.target.closest('button,a,g[data-scene-asset],tr[data-select]');if(!el)return;
 if(el.dataset.opsnav){if(['systems','streams','dashboard','documents','handover','facilities','history','spaces'].includes(el.dataset.opsnav))resetFilters();return;}
 const op=el.dataset.op;if(op&&actions[op]){e.preventDefault();actions[op]();return;}
 if(el.dataset.facility){$('#cdeDialog')?.close();switchFacility(el.dataset.facility);return;}
 if(el.dataset.facilityCard){switchFacility(el.dataset.facilityCard);return;}
 if(el.dataset.view){applyView(el.dataset.view);return;}
 if(el.dataset.goto){resetFilters();go(el.dataset.goto);return;}
 if(el.dataset.select||el.dataset.sceneAsset){state.selected=el.dataset.select||el.dataset.sceneAsset;state.inspector=true;render();return;}
 if(el.dataset.inspectorTab){state.tab=el.dataset.inspectorTab;render();return;}
 for(const [key,data] of [['space','space'],['system','system'],['status','status']])if(el.hasAttribute('data-'+data)){state[key]=el.dataset[data];state.selected=filtered()[0]?.id||assets()[0].id;render();return;}
 if(el.dataset.openSpace){resetFilters();state.space=el.dataset.openSpace;state.selected=filtered()[0]?.id||assets()[0].id;go('spaces');return;}
 if(el.dataset.stream){$('#cdeDialog')?.close();state.selected=el.dataset.stream;state.time=23;state.streamTab='streams';go('streams');return;}
 if(el.dataset.connection){state.selected=el.dataset.connection;const a=selected();dialog('连接配置',`<h3>${a.connection}</h3><dl class="op-props"><dt>宿主资产</dt><dd>${a.name}</dd><dt>所属空间</dt><dd>${label('spaces',a.space)}</dd><dt>系统</dt><dd>${label('systems',a.system)}</dd><dt>数据流</dt><dd>${a.metric}</dd><dt>频率</dt><dd>5 分钟</dd><dt>状态</dt><dd>${statusPill(a)}</dd></dl>`,'查看数据流',()=>go('streams'));return;}
 if(el.dataset.range){state.range=el.dataset.range;render();return;}
 if(el.dataset.mode){state.mode=el.dataset.mode;state.color=state.mode==='heat'?'status':state.color;render();return;}
 if(el.dataset.trace){state.trace=el.dataset.trace;render();return;}
 if(el.dataset.docTab){go(el.dataset.docTab==='docs'?'docs':'documents');return;}
 if(el.dataset.streamTab){go(el.dataset.streamTab==='connections'?'connections':'streams');return;}
 if(el.dataset.edit){state.selected=el.dataset.edit;editAsset();return;}
 if(el.dataset.document){state.selected=el.dataset.document;previewManual();return;}
 if(el.dataset.facilityTab){$$('[data-facility-tab]').forEach(b=>b.classList.toggle('active',b===el));$('.facilities-layout').hidden=el.dataset.facilityTab!=='owned';$('.facilities-empty')?.remove();if(el.dataset.facilityTab!=='owned')host.insertAdjacentHTML('beforeend',`<div class="op-empty facilities-empty">当前没有${el.dataset.facilityTab==='shared'?'共享给我的':'已移交'}设施</div>`);}
});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('[data-scene-asset],tr[data-select]')){e.preventDefault();e.target.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
host.addEventListener('dblclick',e=>{const r=e.target.closest('[data-select]');if(r){state.selected=r.dataset.select;state.inspector=true;go('twin');}});
window.addEventListener('hashchange',render);
document.addEventListener('click',e=>{const b=e.target.closest('[data-setup-entry]');if(b)OPS_SETUP.open(b.dataset.setupEntry);});
window.OPS={state,assets,filtered,facility,selected,status,missing,render};
$$('#cdeHeader [data-action="notifications"]').forEach(el=>{el.removeAttribute('data-action');el.dataset.op='ops-notifications';});
['import-model','new-connection','mapping'].forEach((id,i)=>actions[id]=()=>OPS_SETUP.open(['model','sensor','asset'][i]));
actions['ops-notifications']=()=>dialog('设施运行关注项',assets().filter(a=>['warning','critical','offline'].includes(status(a)[0])).map(a=>`<button class="op-saved-row" data-stream="${a.id}"><strong>${a.name}</strong>${statusPill(a)}</button>`).join('')||'<p>当前设施没有需关注的状态。</p>','查看仪表板',()=>go('dashboard'));
LC.restoreOps(D);
const incoming=new URLSearchParams(location.search),assetId=incoming.get('asset'),facilityId=incoming.get('facility');
const targetAsset=D.assets.find(a=>a.id===assetId),targetFacility=D.facilities.find(f=>f.id===facilityId);
if(targetAsset&&(!facilityId||targetAsset.facility===facilityId)){state.facility=targetAsset.facility;state.selected=targetAsset.id;state.view=facility().view;}
else if(!assetId&&targetFacility){state.facility=targetFacility.id;state.selected=assets()[0].id;state.view=facility().view;}
render();
if((assetId&&!targetAsset)||(facilityId&&!targetFacility)||(targetAsset&&facilityId&&targetAsset.facility!==facilityId))notify('对象关联无效：资产或设施不匹配，已返回默认示例');
})();
