/* Project onboarding UI. Drafts never imply a real BIM import or sensor connection. */
window.OPS_SETUP=(()=>{
const {esc,dialog}=CDE;const drafts={};let activeStep='model';
const steps=[['model','导入源模型','RVT / IFC → 元素与空间'],['asset','关联资产数据','元素 → 资产编码与文档'],['sensor','接入传感器','测点 → 连接 → 数据流'],['verify','核验并使用','来源核验 → 孪生与看板']];
const ctx=()=>{const o=OPS,a=o.selected(),f=o.facility();return{o,a,f,d:drafts[f.id]||(drafts[f.id]={})};};
function action(id,text){return `<button class="cde-primary" data-setup="${id}">${text}</button>`;}
function render(host){const {o,a,f,d}=ctx();host.innerHTML=`<div class="setup-summary"><div><small>设施配置 / 数据来源</small><h2>先建立关联，再查看运行</h2><p>模型属性、交付台账与监测读数分别进入设施，以明确的对象标识连接。</p></div><span class="op-sample">预置样例 · 配置草稿不改变运行数据</span></div><div class="setup-steps">${steps.map(([id,t,sub],i)=>`<button data-setup-tab="${id}" class="${activeStep===id?'active':''}"><b>0${i+1}</b><span>${t}<small>${sub}</small></span></button>`).join('')}</div><div class="setup-body"><section class="setup-work"><div id="setupStep"></div></section><aside class="setup-lineage"><header><h3>当前样例的来源链</h3><select id="setupAsset" aria-label="查看资产来源">${o.assets().map(x=>`<option value="${x.id}" ${x.id===a.id?'selected':''}>${x.id} · ${esc(x.name)}</option>`).join('')}</select></header>${[['源模型',f.model,'V1 · 预置模型；正式交付包待关联'],['模型元素',a.sourceId,'模型内元素标识；与业务资产编码分开'],['运营资产',a.id,a.classification+' / '+f.spaces.find(s=>s[0]===a.space)?.[1]],['业务与文档',a.manual||'运维手册待补齐',['FAN-01','PUMP-01','DB-01'].includes(a.id)?'已建立施工设备示例映射':'施工设备来源未建立映射'],['连接 / 数据流',a.connection||'未配置连接',a.stream?`${a.stream} · ${a.metric} (${a.unit})`:'无数据流；不会显示正常读数'],['监测读数',a.stream?'网关样例 → 预置时间序列':'未接入',a.online===false?'样例离线；不是实时设备故障':'2026-10-11 快照；未接入真实传感器']].map(([t,v,s])=>`<div class="setup-chain"><small>${t}</small><strong>${esc(v)}</strong><p>${esc(s)}</p></div>`).join('')}<button class="text-button" data-setup="trace">核验跨阶段来源 ↗</button></aside></div>`;host.querySelector('#setupAsset').onchange=e=>{o.state.selected=e.target.value;render(host);};host.onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.setupTab){activeStep=b.dataset.setupTab;render(host);}if(b.dataset.setup)open(b.dataset.setup);};paintStep(host);}
function paintStep(host){const {a,f,d}=ctx(),s=host.querySelector('#setupStep');const texts={
model:`<small class="setup-kicker">01 / 建立空间底图</small><h2>从哪里导入模型？</h2><p>本地 Revit / IFC，或 Forma Data Management 中的指定项目文件版本。导入后检查模型坐标、默认可见性和元素信息。</p><div class="setup-source"><b>${esc(f.model)}</b><span>当前场景采用预置示意模型 · V1</span><p>不是本次上传的解析结果，原始交付文件和批准版本仍需核验。</p></div>${action('model','＋ 导入模型')}<a href="#documents">查看模型与文档 ↗</a><h3>导入之后</h3><p>确认模型元素与空间，再使用设施模板定义资产分类和参数。模型名称相同不等于版本相同，也不自动匹配施工资料。</p>`,
asset:`<small class="setup-kicker">02 / 形成资产信息</small><h2>元素、台账与文档如何关联？</h2><p>用“源模型 + 元素标识”定位几何对象，以业务资产编码匹配台账；重复或未匹配编码需要人工处理。</p><table class="op-table"><thead><tr><th>数据来源</th><th>关联依据</th><th>目标</th></tr></thead><tbody><tr><td>${esc(f.model)}</td><td>${a.sourceId}</td><td>${a.id} · ${esc(a.name)}</td></tr><tr><td>交付资产台账</td><td>AssetCode → ${a.id}</td><td>制造商、型号、序列号等参数</td></tr><tr><td>运维文档</td><td>文档版本 / 运维手册字段</td><td>${esc(a.manual||'待补齐')}</td></tr></tbody></table>${action('asset','配置资产关联')}<a href="#handover">检查参数完整性 ↗</a><h3>关联核验</h3><p>空间和系统说明对象的位置与归属；文档链接说明资料来源。资产编码不能替代模型元素标识，也不能证明竣工验收已通过。</p>`,
sensor:`<small class="setup-kicker">03 / 绑定监测测点</small><h2>传感器读数如何进入资产？</h2><p>现场传感器 → 网关 / 集成服务 → 连接与数据流 → 指定宿主对象 → 趋势与看板。</p><div class="setup-source"><b>${esc(a.connection||'待创建连接')} → ${esc(a.stream||'待定义数据流')}</b><span>宿主：${a.id} · ${esc(a.metric||'待选择监测参数')}</span><p>配置测点标识、宿主、数值字段、时间戳和单位后，再验证样例载荷。配置存在与设备在线是两种状态。</p></div>${action('sensor','＋ 接入传感器')}<a href="#streams">查看连接与数据流 ↗</a><h3>两条接入路径</h3><p>已有平台可经网关 / API 推送；需要协议适配与转换时可使用集成服务（例如 Tandem Connect）。本原型只演示字段绑定，不填写密钥或发送数据。</p>`,
verify:`<small class="setup-kicker">04 / 检查数据链</small><h2>准备好了什么，还缺什么？</h2><table class="op-table"><thead><tr><th>检查项</th><th>当前结果</th></tr></thead><tbody><tr><td>源模型与版本</td><td>预置 V1；正式交付包待关联</td></tr><tr><td>模型元素 → 资产</td><td>${a.sourceId} → ${a.id}（示例映射）</td></tr><tr><td>必填字段</td><td>${OPS.missing(a).length?OPS.missing(a).map(x=>x[1]).join('、')+'待补齐':'字段已填写，准确性仍待核验'}</td></tr><tr><td>监测来源</td><td>${a.stream?'预置数据流；真实接入待配置':'未接入传感器'}</td></tr><tr><td>本次配置草稿</td><td>${['model','asset','sensor'].filter(k=>d[k]).length} / 3 项，不代表上线</td></tr></tbody></table><div class="setup-actions"><a class="cde-primary" href="#twin">查看数字孪生</a><a href="#handover">继续交付核验 ↗</a><a href="#dashboard">查看运行看板 ↗</a></div><p>正式接入需要真实模型处理、对象核验、数据传输和验收。本页面不会把配置草稿变成已批准或已在线状态。</p>`};s.innerHTML=texts[activeStep]+`<div class="setup-drafts"><h3>本次配置草稿</h3><p>${activeStep==='verify'?(Object.values(d).map(v=>esc(v)).join('<br>')||'尚未保存配置草稿。'):d[activeStep]?esc(d[activeStep]):'当前步骤尚未保存草稿。可浏览预置来源链，也可从上方入口逐步配置。'}</p><small>草稿仅在当前页面内保留，刷新后恢复预置样例。</small></div>`;}
function open(kind){if(kind==='trace'){LC.open();return;}const {a,f,o,d}=ctx();if(!['model','asset','sensor'].includes(kind))return;let step=0;const draft={source:'local',file:'',host:a.id,point:'SENSOR-'+a.id,field:'value',time:'timestamp',protocol:'网关 / API',unit:a.unit||'',model:f.model,manufacturerSource:'Manufacturer'};
const titles={model:'导入模型',asset:'配置资产关联',sensor:'接入传感器'};const titlesSteps=kind==='model'?['选择来源','检查导入设置','确认下一步']:kind==='asset'?['选择对象','核对参数来源','确认关联']:['绑定宿主与测点','映射监测字段','验证样例载荷'];
const modal=dialog(titles[kind],'<div id="setupWizard"></div>','');modal.classList.add('setup-dialog');
function draw(){const target=o.assets().find(x=>x.id===draft.host);const w=modal.querySelector('#setupWizard');w.innerHTML=`<div class="setup-wizard-steps">${titlesSteps.map((t,i)=>`<span class="${i===step?'active':''}">${i+1} ${t}</span>`).join('')}</div><div class="setup-wizard-context">${esc(f.name)} · ${esc(target.id)} · 前端配置示例</div>`;
if(kind==='model')w.innerHTML+=step===0?`<label class="field">模型来源<select id="setupSource"><option value="local" ${draft.source==='local'?'selected':''}>本地 RVT / IFC 文件</option><option value="cde" ${draft.source==='cde'?'selected':''}>Forma Data Management 文件引用（示例）</option></select></label><label class="field">选择文件<input type="file" id="setupModelFile" accept=".rvt,.ifc"></label><button class="text-button" id="setupUseSample">使用预置示例文件</button><p id="setupFileLabel">${esc(draft.file||'尚未选择文件')}</p><p>文件选择只读取名称，不上传或解析模型。选择公共数据环境来源时使用示例文件引用，不连接外部账号。</p>`:step===1?`<h3>${esc(draft.file)}</h3><label class="field">版本 / 来源<input value="V1 · ${draft.source==='cde'?'公共数据环境引用示例':'本地文件索引'}" readonly></label><label class="field">坐标检查<select><option>沿用源模型坐标，导入后核对位置</option></select></label><label class="radio-row"><input type="checkbox" checked> 默认视图可见</label><p>Revit 可按阶段 / 视图选择导入范围；IFC 按文件内容导入。这里不模拟真实几何处理。</p>`:`<h3>保存模型导入草稿</h3><p>${esc(draft.file)} → ${esc(f.name)}</p><p>下一步：检查元素与空间，应用设施模板并配置资产关联。现有示意模型保持原状。</p>`;
if(kind==='asset')w.innerHTML+=step===0?`<label class="field">目标资产<select id="setupHost">${o.assets().map(x=>`<option value="${x.id}" ${x.id===draft.host?'selected':''}>${x.id} · ${esc(x.name)}</option>`).join('')}</select></label><div class="setup-source"><b>${esc(f.model)} / ${target.sourceId}</b><p>元素标识来自模型；AssetCode 来自交付台账。当前使用显式预置映射，不按名称自动匹配。</p></div>`:step===1?`<table class="op-table"><thead><tr><th>来源字段（示例）</th><th>目标资产参数</th><th>当前值</th></tr></thead><tbody>${[['AssetCode','资产编码',target.id],['Manufacturer','制造商',target.manufacturer],['SerialNumber','序列号',target.serial],['文档链接','运维手册',target.manual]].map(r=>`<tr>${r.map((v,i)=>`<td>${i===0&&v==='Manufacturer'?'<select id="setupManufacturerMap" aria-label="制造商来源字段"><option>Manufacturer</option><option>交付台账.制造商</option><option>人工补齐</option></select>':esc(v||'待补齐')}</td>`).join('')}</tr>`).join('')}</tbody></table><p>来源台账尚未实际读取。重复编码或无法匹配的行应进入人工核验，不覆盖既有资产。</p>`:`<h3>确认对象关系</h3><p>${esc(f.model)} / ${target.sourceId} → ${target.id}</p><p>空间：${esc(f.spaces.find(x=>x[0]===target.space)?.[1])}<br>系统：${esc(f.systems.find(x=>x[0]===target.system)?.[1])}<br>文档：${esc(target.manual||'待关联')}</p><p>此处保存关联方案；实际补齐参数或文档请进入资产清单 / 数据交付。</p>`;
if(kind==='sensor')w.innerHTML+=step===0?`<label class="field">宿主资产<select id="setupHost">${o.assets().map(x=>`<option value="${x.id}" ${x.id===draft.host?'selected':''}>${x.id} · ${esc(x.name)}</option>`).join('')}</select></label><label class="field">外部测点标识<input id="setupPoint" value="${esc(draft.point)}"></label><label class="field">接入路径<select id="setupProtocol"><option>网关 / API</option><option ${draft.protocol!=='网关 / API'?'selected':''}>集成服务 / Tandem Connect</option></select></label><p>宿主将读数关联到设施中的对象；外部测点标识用于区分现场数据来源。</p>`:step===1?`<h3>${target.id} · ${esc(target.metric||'监测参数')}</h3><label class="field">数值字段<input id="setupValueField" value="${esc(draft.field)}"></label><label class="field">时间戳字段<input id="setupTimeField" value="${esc(draft.time)}"></label><label class="field">单位<input id="setupUnit" value="${esc(draft.unit)}"></label><p>采样间隔：5 分钟（示例）。单位需要与参数一致；数值与时间戳字段不能相同。</p>`:`<h3>样例校验通过 · 未连接现场</h3><pre>${esc(JSON.stringify({point:draft.point,host:target.id,[draft.time]:'2026-10-11T10:00:00+08:00',[draft.field]:target.value??0,unit:draft.unit},null,2))}</pre><p>目标：${target.connection||'待创建连接'} / ${target.stream||'待创建数据流'}<br>路径：${esc(draft.protocol)}</p><p>这里只核验字段配置并生成样例，不执行网络连通性或实时读数测试。保存草稿不会将离线设备标成在线。</p>`;
w.innerHTML+='<p id="setupError" role="alert"></p>';modal.querySelector('footer').innerHTML=`<small>步骤 ${step+1} / 3 · 配置演示</small><button class="text-button" id="setupBack">${step?'上一步':'取消'}</button><button class="cde-primary" id="setupNext">${step===2?'保存配置草稿':'下一步'}</button>`;
const input=id=>modal.querySelector('#'+id);if(input('setupSource'))input('setupSource').onchange=e=>draft.source=e.target.value;if(input('setupModelFile'))input('setupModelFile').onchange=e=>{draft.file=e.target.files[0]?.name||'';input('setupFileLabel').textContent=draft.file;};if(input('setupUseSample'))input('setupUseSample').onclick=()=>{draft.file=f.model;input('setupFileLabel').textContent=draft.file;};if(input('setupHost'))input('setupHost').onchange=e=>{draft.host=e.target.value;const x=o.assets().find(a=>a.id===draft.host);draft.unit=x.unit||'';draft.point='SENSOR-'+x.id;draw();};
input('setupBack').onclick=()=>{if(step){step--;draw();}else modal.close();};input('setupNext').onclick=()=>{if(kind==='model'&&step===0&&!/\.(ifc|rvt)$/i.test(draft.file)){input('setupError').textContent='请选择 RVT / IFC 文件或使用预置示例。';return;}if(kind==='asset'&&step===1)draft.manufacturerSource=input('setupManufacturerMap').value;if(kind==='sensor'){if(step===0){draft.point=input('setupPoint').value.trim();draft.protocol=input('setupProtocol').value;if(!draft.point){input('setupError').textContent='请填写外部测点标识。';return;}}if(step===1){draft.field=input('setupValueField').value.trim();draft.time=input('setupTimeField').value.trim();draft.unit=input('setupUnit').value.trim();if(!draft.field||!draft.time||!draft.unit||draft.field===draft.time||['point','host','unit'].includes(draft.field)||['point','host','unit'].includes(draft.time)){input('setupError').textContent='请填写不同的数值、时间戳字段及单位；字段不能占用 point、host、unit。';return;}}}if(kind==='sensor'&&step===1&&target.unit&&draft.unit!==target.unit){input('setupError').textContent='单位需与目标参数一致：'+target.unit+'；单位转换应在接入前完成。';return;}if(step<2){step++;draw();}else{d[kind]=kind==='model'?`${draft.file} · ${draft.source==='local'?'本地':'CDE'}导入方案已记录`:kind==='asset'?`${target.sourceId} → ${target.id}；制造商来源：${draft.manufacturerSource}；关联方案已记录`:`${draft.point} → ${target.id} · ${draft.field} / ${draft.unit} · 待真实接入`;o.state.selected=target.id;modal.close();activeStep=kind==='model'?'asset':kind==='asset'?'sensor':'verify';location.hash='setup';o.render();}};}
draw();}
return{render,open};
})();
