/* Model and document indexes retain imported revisions independently of the CDE. */
window.TANDEM_FILES=(()=>{
'use strict';
const {esc,icon,dialog,notify}=CDE,key='tandem-files-v1';let store;try{store=JSON.parse(sessionStorage.getItem(key)||'null');}catch{}
store=store||{facilities:{},links:{},history:[]};store.facilities=store.facilities||{};store.links=store.links||{};store.history=store.history||[];
const now=()=>new Date().toISOString(),clone=x=>JSON.parse(JSON.stringify(x)),id=()=>crypto.randomUUID(),current=()=>OPS.facility(),fmt=d=>String(d||'').replace('T',' ').slice(0,16),size=n=>n?(n/1024).toFixed(1)+' KB':'—';
store.activeModels=store.activeModels||{};let activeModel=store.activeModels,query='';
function collection(facility){const f=typeof facility==='string'?OPS_DATA.facilities.find(f=>f.id===facility):facility||current();if(!store.facilities[f.id]){const models=[{id:'seed-'+f.id,title:f.model.replace(/\.[^.]+$/,''),filename:f.model,format:f.model.split('.').pop().toUpperCase(),source:'seed',version:'V1',importedAt:'2026-09-18T08:00:00',updatedAt:'2026-09-18T08:00:00',visible:true,phase:'竣工',seed:true,versions:[]}],docs=[];for(const a of OPS_DATA.assets.filter(a=>a.facility===f.id&&a.manual)){let doc=docs.find(d=>d.name===a.manual);if(!doc){doc={id:'doc-'+id(),name:a.manual,source:'seed',format:'PDF',version:'V1',added:'2026-09-18T08:00:00',size:0};docs.push(doc);}if(!Object.hasOwn(store.links,a.id))store.links[a.id]=[{documentId:doc.id,parameter:'运维手册',type:'Link',label:doc.name}];}store.facilities[f.id]={models,docs};save(false);}return store.facilities[f.id];}
function save(render=true){try{sessionStorage.setItem(key,JSON.stringify(store));}catch{}if(render&&window.OPS)OPS.render();}
function log(action,name){store.history.unshift({at:now(),action,name,facility:current().id,actor:'张工'});}
function models(f){return collection(f).models;}
function docs(f){return collection(f).docs;}
function sourceFile(m){return m.sourceId&&window.DESIGN_DATA?.object(m.sourceId);}
function sourceStatus(m){if(m.source!=='docs')return '';const source=sourceFile(m);return !source?'源文件已删除':source.version!==m.version?'可更新至 '+source.version:'已是最新版本';}
function restoreLinks(){for(const f of OPS_DATA.facilities)collection(f);for(const a of OPS_DATA.assets){if(!Object.hasOwn(store.links,a.id))continue;const linked=(store.links[a.id]||[]).filter(link=>docs(a.facility).some(d=>d.id===link.documentId));store.links[a.id]=linked;a.documentLinks=clone(linked);a.manual=linked.filter(l=>l.parameter==='运维手册').map(l=>l.label).join('；');}}
function geometryVisible(f){return models(f).some(m=>m.seed&&m.visible);}
function currentModel(f){const list=models(f);return list.find(m=>m.id===activeModel[(f||current()).id])||list[0];}
function guarded(d,fn){try{fn();d.close();}catch(e){d.querySelector('[role=alert]').textContent=e.message;}}
function prepare(d){d.classList.add('tm-dialog');const small=d.querySelector('footer small');if(small)small.textContent='';return d;}
function openImport(updateId){const facility=current(),existing=models(facility).find(m=>m.id===updateId);if(existing?.source==='docs'){const next=sourceFile(existing);if(!next){notify('源文件已删除，请先在成果资料库恢复');return;}if(next.version===existing.version){notify('当前已是最新版本');return;}const snap=clone(next),d=prepare(dialog('更新模型版本',`<div class="tm-target">${icon('file')}<strong>${esc(existing.title)}</strong></div><dl class="op-props"><dt>已导入版本</dt><dd>${esc(existing.version)}</dd><dt>来源版本</dt><dd>${esc(snap.version)}</dd><dt>来源文件</dt><dd>${esc(snap.name)}</dd></dl><p>更新后将保留旧版本记录。</p><p class="tm-error" role="alert"></p>`,'更新',()=>{}));d.querySelector('#dialogConfirm').onclick=()=>guarded(d,()=>{existing.versions.unshift(clone({...existing,versions:[]}));existing.version=snap.version;existing.sourceSnapshot=snap;existing.updatedAt=now();log('更新模型版本',existing.title+' '+existing.version);save();notify('已更新至 '+existing.version);});return;}
let method=existing?'local':'docs',pending=null,picked='',title=existing?.title||'',visible=existing?.visible??true,phase=existing?.phase||'竣工';const d=prepare(dialog(existing?'更新模型版本':'导入模型','<div id="tmImportBody"></div>','导入',()=>{}));
function draw(){const fs=(window.DESIGN_DATA?.files()||[]).filter(f=>['RVT','IFC','MODEL'].includes(f.format));const revit=method==='docs'?fs.find(f=>f.id===picked)?.format==='RVT':/\.rvt$/i.test(pending?.name||existing?.filename||'');d.querySelector('#tmImportBody').innerHTML=`${existing?'':`<div class="tm-import-tabs"><button data-tm-method="docs" class="${method==='docs'?'active':''}">Autodesk Docs</button><button data-tm-method="local" class="${method==='local'?'active':''}">文件上传</button></div>`}${method==='docs'?`<div class="tm-account-fields"><label class="field">账户<select id="tmAccount"><option>XX高速建设管理处</option></select></label><label class="field">项目<select id="tmProject"><option>XX高速公路</option></select></label></div><label class="field">源模型<select id="tmSourceFile"><option value="">选择 RVT / IFC 模型</option>${fs.map(f=>`<option value="${esc(f.id)}" ${picked===f.id?'selected':''}>${esc(f.name)} · ${esc(f.version)}</option>`).join('')}</select></label>${picked?`<div class="tm-source-path">${esc(DESIGN_DATA.path(picked))}</div>`:''}${!fs.length?'<div class="tm-empty">项目中暂无模型文件</div>':''}`:`<div class="tm-drop" id="tmDrop">${icon('upload')}<strong>${pending?esc(pending.name):'拖放 RVT / IFC 文件'}</strong><label class="tm-file-picker">选择文件<input id="tmModelFile" type="file" accept=".rvt,.ifc" aria-label="选择模型文件"></label>${pending?'<span>'+size(pending.size)+'</span>':''}</div>`}<label class="field">模型标题<input id="tmModelTitle" value="${esc(title)}" placeholder="输入标题" maxlength="120"></label>${revit?`<div class="tm-account-fields"><label class="field">阶段<select id="tmPhase"><option ${phase==='竣工'?'selected':''}>竣工</option><option ${phase==='新建'?'selected':''}>新建</option><option ${phase==='现有'?'selected':''}>现有</option></select></label><label class="field">三维视图<select><option>默认三维视图</option></select></label></div>`:''}<label class="radio-row"><input type="checkbox" id="tmVisible" ${visible?'checked':''}> 在默认视图中可见</label><p class="tm-import-boundary">此演示保存模型来源与版本索引，不解析 RVT / IFC 几何。上游版本变化后需手动更新。</p><p class="tm-error" role="alert"></p>`;
d.querySelectorAll('[data-tm-method]').forEach(b=>b.onclick=()=>{capture();method=b.dataset.tmMethod;draw();});d.querySelector('#tmSourceFile')?.addEventListener('change',e=>{capture();picked=e.target.value;const f=fs.find(f=>f.id===picked);title=f?.name.replace(/\.[^.]+$/,'')||'';draw();});function accept(files){const file=[...files][0];if(!file)return;if(!/\.(rvt|ifc)$/i.test(file.name)||!file.size){d.querySelector('[role=alert]').textContent='请选择非空 RVT 或 IFC 文件';return;}capture();pending=file;if(!existing)title=file.name.replace(/\.[^.]+$/,'');draw();}d.querySelector('#tmModelFile')?.addEventListener('change',e=>accept(e.target.files));const drop=d.querySelector('#tmDrop');if(drop){drop.ondragover=e=>{e.preventDefault();drop.classList.add('dragging');};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=e=>{e.preventDefault();accept(e.dataTransfer.files);};}d.querySelector('#dialogConfirm').textContent=existing?'更新':'导入';}
function capture(){title=d.querySelector('#tmModelTitle')?.value.trim()||'';visible=d.querySelector('#tmVisible')?.checked??true;phase=d.querySelector('#tmPhase')?.value||'—';}
d.querySelector('#dialogConfirm').onclick=()=>guarded(d,()=>{capture();if(!title)throw Error('请输入模型标题');const source=method==='docs'?DESIGN_DATA.object(picked):null;if(method==='docs'&&!source)throw Error('请选择有效源模型');if(method==='local'&&!pending)throw Error('请选择 RVT / IFC 文件');if(!existing&&method==='docs'&&models(facility).some(m=>m.sourceId===picked))throw Error('该模型已导入，请通过“更新版本”更新');const filename=source?.name||pending.name,format=source?.format==='MODEL'?'IFC':source?.format||filename.split('.').pop().toUpperCase();if(existing){existing.versions.unshift(clone({...existing,versions:[]}));existing.title=title;existing.filename=filename;existing.version='V'+((parseInt(existing.version.slice(1))||1)+1);existing.size=pending.size;existing.updatedAt=now();existing.visible=visible;existing.phase=phase;log('更新模型版本',title+' '+existing.version);}else{const m={id:'model-'+id(),title,filename,format,source:method==='docs'?'docs':'local',sourceId:source?.id||null,sourceSnapshot:source?clone(source):null,sourcePath:source?DESIGN_DATA.path(source.id):'',version:source?.version||'V1',size:source?.size||pending?.size||0,visible,phase,importedAt:now(),updatedAt:now(),versions:[],seed:false};models(facility).push(m);activeModel[facility.id]=m.id;log('导入模型',title+' '+m.version);}save();notify(existing?'模型版本已更新':'模型已导入');});draw();}
function removeModel(modelId){const m=models().find(m=>m.id===modelId);if(!m)return;const d=prepare(dialog('删除模型',`<div class="tm-target">${icon('file')}<strong>${esc(m.title)}</strong></div><p>从当前设施移除此模型。来源文件将保留。</p><p class="tm-error" role="alert"></p>`,'删除',()=>{}));d.querySelector('#dialogConfirm').onclick=()=>guarded(d,()=>{collection().models=models().filter(x=>x.id!==m.id);delete activeModel[current().id];log('删除模型',m.title);save();notify('模型已删除');});}
function renameModel(modelId){const m=models().find(m=>m.id===modelId);const d=prepare(dialog('重命名模型',`<label class="field">模型标题<input id="tmRename" value="${esc(m.title)}"></label><p class="tm-error" role="alert"></p>`,'保存',()=>{}));d.querySelector('#dialogConfirm').onclick=()=>guarded(d,()=>{const name=d.querySelector('#tmRename').value.trim();if(!name)throw Error('请输入模型标题');m.title=name;log('重命名模型',name);save();});}
function details(m){const src=sourceStatus(m);return `<section class="tm-model-detail"><header><span class="tm-format">${esc(m.format)}</span><div><h2>${esc(m.title)}</h2><p>${esc(m.filename)}</p></div></header><dl class="op-props"><dt>导入方式</dt><dd>${m.source==='docs'?'Autodesk Docs':m.source==='local'?'文件上传':'预置模型'}</dd><dt>已导入版本</dt><dd><span class="version-pill">${esc(m.version)}</span></dd><dt>导入时间</dt><dd>${fmt(m.importedAt)}</dd><dt>最后更新</dt><dd>${fmt(m.updatedAt)}</dd><dt>阶段</dt><dd>${esc(m.phase)}</dd><dt>默认可见</dt><dd>${m.visible?'是':'否'}</dd>${m.source==='docs'?`<dt>来源文件</dt><dd><a href="file-management.html?selected=${encodeURIComponent(m.sourceId)}">${esc(m.sourcePath)} ↗</a></dd><dt>来源状态</dt><dd class="${src.startsWith('可更新')?'tm-update-available':''}">${src}</dd>`:''}</dl>${m.versions.length?`<h3>版本历史</h3><div class="tm-version-history"><div><span>${esc(m.version)}</span><b>当前版本</b><time>${fmt(m.updatedAt)}</time></div>${m.versions.map(v=>`<div><span>${esc(v.version)}</span><b>历史版本</b><time>${fmt(v.updatedAt)}</time></div>`).join('')}</div>`:''}</section>`;}
let previewScene;
function renderModels(host,scene){previewScene=scene;const list=models(),chosen=currentModel();host.innerHTML=`<div class="tm-files-toolbar"><h2>模型 <span>${list.length}</span></h2><button class="cde-primary" data-tm-import>＋ 导入模型</button></div><div class="tm-files-layout"><section class="tm-model-list">${list.length?list.map(m=>`<article class="tm-model-row ${chosen?.id===m.id?'selected':''}"><div class="tm-model-main"><button class="tm-model-select" data-tm-select="${m.id}"><span class="tm-format">${esc(m.format)}</span><span><strong>${esc(m.title)}</strong><small>${esc(m.version)} · ${m.source==='docs'?'Autodesk Docs':m.source==='local'?'本地文件':'设施模型'}</small>${sourceStatus(m).startsWith('可更新')?`<em>${sourceStatus(m)}</em>`:''}${sourceStatus(m)==='源文件已删除'?'<em class="tm-source-missing">源文件已删除</em>':''}</span></button><label class="tm-visible-switch" title="默认视图可见"><input type="checkbox" data-tm-visible="${m.id}" ${m.visible?'checked':''} aria-label="${esc(m.title)}默认可见"><span></span></label><button class="quiet-button tm-more" data-tm-more="${m.id}" aria-label="${esc(m.title)}更多操作">⋮</button></div></article>`).join(''):'<div class="tm-empty">尚未导入模型</div>'}</section><section class="tm-model-overview">${chosen?details(chosen):'<div class="tm-empty">选择或导入模型</div>'}${chosen?.seed&&chosen.visible?`<div class="tm-model-preview">${scene()}</div>`:chosen?`<div class="tm-index-preview">${icon('building')}<strong>${esc(chosen.title)}</strong><span>${chosen.visible?'模型索引':'已从默认视图隐藏'}</span></div>`:''}</section></div>`;bind(host);}
function modelMenu(anchor,mid){document.querySelector('.tm-menu')?.remove();const m=models().find(m=>m.id===mid),menu=document.createElement('div');menu.className='tm-menu';menu.innerHTML=`<button data-tm-menu="details">详情</button><button data-tm-menu="update">更新版本</button><button data-tm-menu="rename">重命名</button><button data-tm-menu="delete">删除</button>`;document.body.append(menu);const r=anchor.getBoundingClientRect();menu.style.left=Math.max(10,r.right-menu.offsetWidth)+'px';menu.style.top=Math.min(r.bottom+3,innerHeight-menu.offsetHeight-10)+'px';menu.querySelector('button').focus();menu.onclick=e=>{const a=e.target.dataset.tmMenu;if(!a)return;menu.remove();if(a==='details'){activeModel[current().id]=mid;OPS.render();}if(a==='update')openImport(mid);if(a==='rename')renameModel(mid);if(a==='delete')removeModel(mid);};menu.onkeydown=e=>{if(e.key==='Escape'){menu.remove();anchor.focus();}};}
function addDocument(){let method='local',pending=null,sourceId='';const d=prepare(dialog('添加文档','<div id="tmDocImport"></div>','添加',()=>{}));function draw(){const list=(window.DESIGN_DATA?.files()||[]).filter(f=>!['MODEL','RVT','IFC'].includes(f.format));d.querySelector('#tmDocImport').innerHTML=`<div class="tm-import-tabs"><button data-tm-docmethod="local" class="${method==='local'?'active':''}">文件上传</button><button data-tm-docmethod="docs" class="${method==='docs'?'active':''}">Autodesk Docs</button></div>${method==='local'?`<label class="field">文档<input type="file" id="tmDocumentFile" aria-label="选择文档文件"></label><p>${pending?esc(pending.name):''}</p>`:`<label class="field">项目文档<select id="tmDocumentSource"><option value="">选择文档</option>${list.map(f=>`<option value="${f.id}" ${sourceId===f.id?'selected':''}>${esc(f.name)} · ${esc(f.version)}</option>`).join('')}</select></label>`}<p class="tm-error" role="alert"></p>`;d.querySelectorAll('[data-tm-docmethod]').forEach(b=>b.onclick=()=>{method=b.dataset.tmDocmethod;draw();});d.querySelector('#tmDocumentFile')?.addEventListener('change',e=>{pending=e.target.files[0];});d.querySelector('#tmDocumentSource')?.addEventListener('change',e=>sourceId=e.target.value);}
d.querySelector('#dialogConfirm').onclick=()=>guarded(d,()=>{const f=method==='docs'?DESIGN_DATA.object(sourceId):pending;if(!f||f.size===0)throw Error('请选择有效文档');if(docs().some(x=>x.name===f.name))throw Error('设施中已存在同名文档');const doc={id:'doc-'+id(),name:f.name,source:method,sourceId:method==='docs'?f.id:null,sourceSnapshot:method==='docs'?clone(f):null,versions:[],format:f.format||f.name.split('.').pop().toUpperCase(),version:f.version||'V1',size:f.size||0,added:now()};docs().push(doc);log('添加文档',doc.name);save();notify('文档已添加');});draw();}
function linkedAssets(docId){return OPS.assets().filter(a=>(store.links[a.id]||[]).some(l=>l.documentId===docId));}
function linkDocument(docId,assetId){const documentList=docs(),first=documentList.find(d=>d.id===docId)||documentList[0];if(!first){addDocument();return;}const asset=OPS.assets().find(a=>a.id===assetId)||OPS.selected();const d=prepare(dialog('关联文档',`<label class="field">文档<select id="tmLinkDocument">${documentList.map(x=>`<option value="${x.id}" ${x.id===first.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><label class="field">资产<select id="tmLinkAsset">${OPS.assets().map(a=>`<option value="${a.id}" ${a.id===asset.id?'selected':''}>${esc(a.name)} · ${a.id}</option>`).join('')}</select></label><label class="field">参数<select id="tmLinkParameter"><option>运维手册</option><option>调试报告</option><option>产品资料</option></select></label><div class="tm-link-type">数据类型 <b>Link</b></div><p class="tm-error" role="alert"></p>`,'关联',()=>{}));d.querySelector('#dialogConfirm').onclick=()=>guarded(d,()=>{const doc=docs().find(x=>x.id===d.querySelector('#tmLinkDocument').value),a=OPS.assets().find(x=>x.id===d.querySelector('#tmLinkAsset').value),parameter=d.querySelector('#tmLinkParameter').value;if(!doc||!a)throw Error('请选择文档及资产');store.links[a.id]=(store.links[a.id]||[]).filter(l=>!(l.parameter===parameter&&l.documentId===doc.id));store.links[a.id].push({documentId:doc.id,parameter,type:'Link',label:doc.name,version:doc.version});restoreLinks();log('关联文档',doc.name+' → '+a.id+' / '+parameter);save();notify('Link 参数已关联');});}
function updateDocument(docId){const doc=docs().find(d=>d.id===docId),source=doc&&sourceFile(doc);if(!doc||!source||source.version===doc.version){notify(source?'当前已是最新版本':'源文件不可用，保留已导入版本');return;}const snap=clone(source),d=prepare(dialog('更新文档版本',`<div class="tm-target">${icon('file')}<strong>${esc(doc.name)}</strong></div><dl class="op-props"><dt>已导入版本</dt><dd>${esc(doc.version)}</dd><dt>来源版本</dt><dd>${esc(snap.version)}</dd><dt>关联资产</dt><dd>${linkedAssets(docId).map(a=>esc(a.name)).join('、')||'—'}</dd></dl><p class="tm-error" role="alert"></p>`,'更新',()=>{}));d.querySelector('#dialogConfirm').onclick=()=>guarded(d,()=>{doc.versions=doc.versions||[];doc.versions.unshift(clone({...doc,versions:[]}));doc.version=snap.version;doc.size=snap.size||doc.size;doc.sourceSnapshot=snap;doc.updated=now();for(const links of Object.values(store.links))for(const link of links)if(link.documentId===docId)link.version=doc.version;restoreLinks();log('更新文档版本',doc.name+' '+doc.version);save();notify('文档已更新至 '+doc.version);});}
function unlinkDocument(docId,assetId){const asset=OPS_DATA.assets.find(a=>a.id===assetId);if(!asset)return;store.links[assetId]=(store.links[assetId]||[]).filter(l=>l.documentId!==docId);restoreLinks();log('移除文档链接',assetId);save();notify('已移除资产链接');}
function previewDoc(docId){const doc=docs().find(d=>d.id===docId);if(!doc)return;prepare(dialog(doc.name,`<div class="tm-doc-preview"><span class="tm-format">${esc(doc.format)}</span><h3>${esc(doc.name)}</h3><dl class="op-props"><dt>版本</dt><dd>${esc(doc.version)}</dd><dt>添加时间</dt><dd>${fmt(doc.added)}</dd><dt>来源</dt><dd>${doc.source==='docs'?'Autodesk Docs':doc.source==='local'?'文件上传':'运维资料'}</dd><dt>关联资产</dt><dd>${linkedAssets(docId).map(a=>esc(a.name)+' · '+a.id).join('<br>')||'未关联'}</dd></dl></div>`,'关闭',()=>{}));}
function deleteDocument(docId){const doc=docs().find(d=>d.id===docId);if(!doc)return;const count=linkedAssets(docId).length,d=prepare(dialog('删除文档',`<p>${esc(doc.name)}</p><p>${count?'同时移除 '+count+' 个资产的文档链接。':'此文档尚未关联资产。'}来源文件将保留。</p><p class="tm-error" role="alert"></p>`,'删除',()=>{}));d.querySelector('#dialogConfirm').onclick=()=>guarded(d,()=>{collection().docs=docs().filter(x=>x.id!==docId);for(const k in store.links)store.links[k]=store.links[k].filter(l=>l.documentId!==docId);restoreLinks();log('删除文档',doc.name);save();notify('文档已删除');});}
function renderDocs(host){host.innerHTML=`<div class="tm-files-toolbar"><h2>文档 <span>${docs().length}</span></h2><label class="tm-doc-search">${icon('search')}<input id="tmDocSearch" placeholder="搜索文档" aria-label="搜索文档" value="${esc(query)}"></label><button class="cde-primary" data-tm-adddoc>＋ 添加文档</button></div><div class="tm-doc-table"><table class="op-table"><thead><tr><th>文档名称</th><th>版本</th><th>关联资产</th><th>添加时间</th><th>操作</th></tr></thead><tbody id="tmDocsRows"></tbody></table><div id="tmDocsEmpty" class="tm-empty" hidden>没有匹配的文档</div></div>`;paintDocs(host);host.querySelector('#tmDocSearch').oninput=e=>{query=e.target.value;paintDocs(host);};bind(host);}
function paintDocs(host){const list=docs().filter(d=>d.name.toLowerCase().includes(query.toLowerCase()));host.querySelector('#tmDocsRows').innerHTML=list.map(d=>`<tr><td><button class="tm-doc-name" data-tm-preview="${d.id}">${icon('file')}${esc(d.name)}</button></td><td><span class="version-pill">${esc(d.version)}</span>${sourceStatus(d).startsWith('可更新')?'<small class="tm-update-available">'+sourceStatus(d)+'</small>':''}</td><td>${linkedAssets(d.id).map(a=>`<button class="inline-link" data-tm-asset="${a.id}">${esc(a.name)}</button>`).join('、')||'—'}</td><td>${fmt(d.added)}</td><td><button class="inline-link" data-tm-link="${d.id}">关联资产</button><button class="inline-link tm-update-doc" data-tm-updatedoc="${d.id}" ${d.source==='docs'&&sourceFile(d)&&sourceFile(d).version!==d.version?'':'disabled'}>更新版本</button><button class="inline-link tm-delete-doc" data-tm-deletedoc="${d.id}">删除</button></td></tr>`).join('');host.querySelector('#tmDocsEmpty').hidden=!!list.length;}
function linksFor(a){return (store.links[a.id]||[]).map(l=>({...l,document:docs(a.facility).find(d=>d.id===l.documentId)})).filter(l=>l.document);}
function assetLinks(a){return linksFor(a).map(l=>`<div class="tm-asset-document"><button class="op-doc-card" data-tm-preview="${l.documentId}">${icon('file')}<span>${esc(l.label)}<small>${esc(l.parameter)} · Link · ${esc(l.document.version)}</small></span></button><button class="tm-unlink" data-tm-unlink="${l.documentId}" data-tm-unlinkasset="${a.id}" aria-label="移除 ${esc(l.label)} 的资产链接">×</button></div>`).join('')||'<div class="op-empty">尚未关联文档</div>';}
function bind(host){host.querySelectorAll('[data-tm-import]').forEach(b=>b.onclick=()=>openImport());host.querySelectorAll('[data-tm-visible]').forEach(b=>b.onchange=()=>{const m=models().find(x=>x.id===b.dataset.tmVisible);m.visible=b.checked;log('调整模型可见性',m.title);save();});host.querySelectorAll('[data-tm-select]').forEach(b=>{b.onclick=()=>{activeModel[current().id]=b.dataset.tmSelect;save(false);const m=currentModel();host.querySelectorAll('.tm-model-row').forEach(row=>row.classList.toggle('selected',row.querySelector('[data-tm-select]').dataset.tmSelect===m.id));host.querySelector('.tm-model-overview').innerHTML=details(m)+(m.seed&&m.visible?'<div class="tm-model-preview">'+previewScene()+'</div>':'<div class="tm-index-preview">'+icon('building')+'<strong>'+esc(m.title)+'</strong><span>'+(m.visible?'模型索引':'已从默认视图隐藏')+'</span></div>');};b.ondblclick=()=>renameModel(b.dataset.tmSelect);});host.querySelectorAll('[data-tm-more]').forEach(b=>b.onclick=()=>modelMenu(b,b.dataset.tmMore));host.querySelectorAll('[data-tm-adddoc]').forEach(b=>b.onclick=addDocument);}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!e.target.closest('.tm-menu,[data-tm-more]'))document.querySelector('.tm-menu')?.remove();if(!b)return;if(b.dataset.tmLink)linkDocument(b.dataset.tmLink);if(b.dataset.tmUpdatedoc)updateDocument(b.dataset.tmUpdatedoc);if(b.dataset.tmUnlink)unlinkDocument(b.dataset.tmUnlink,b.dataset.tmUnlinkasset);if(b.dataset.tmDeletedoc)deleteDocument(b.dataset.tmDeletedoc);if(b.dataset.tmPreview)previewDoc(b.dataset.tmPreview);if(b.dataset.tmAsset){OPS.state.selected=b.dataset.tmAsset;OPS.state.inspector=true;OPS.state.tab='documents';location.hash='inventory';}});
document.addEventListener('design-data-changed',()=>{if(window.OPS&&['#documents','#docs','#setup'].includes(location.hash))OPS.render();});
return{store,models,docs,openImport,removeModel,sourceStatus,currentModel,geometryVisible,renderModels,renderDocs,linkDocument,addDocument,updateDocument,assetLinks,linksFor,restoreLinks,save};
})();
